SORMAS-Foundation/SORMAS-Project

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/CreateNewContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
… new contact creation form"
Fixes #
=> SORQA-434 Automatize "Test Contacts > Spelling correction on new contact creation form [0] (DE)"

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/contacts/ContactsDashboardStatisticsComponent.java
=> #9086 - Use full height for disease component

sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleNotificationCheckboxSet.java
=> #10081 - fix notification text hidden by checkbox

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntryUserRoles.feature
=> SORDEV-10360 with user roles

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/LoginPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/users/EditUserPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/users/UserManagementPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/User.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/EditUserSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/InvalidActions.feature
refactored code and implemented new tests
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1596
=> #9868-InvalidUiTests

sormas-base/pom.xml
Fixes #10099 
@MateStrysewske fixes a vulnerability
=> [#10099] bump postgres

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
=> #9997 fix api

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> Qu auto/sorqa 402fix2

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageMapper.java
=> #10119 consider empty result

sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjbTest.java
=> #10091 - Fix sending entities to reporting tool multiple times

sormas-e2e-tests/build.gradle, sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/strings/LanguageDetectorHelper.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/SurveillanceDashboardPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Continent.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/LanguageChecks.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
1. Implemented LanguageDetectorHelper
2. Created language checks feature
3. Moved language related tests into feature file
4. Updated tests to use new implementation
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1615/allure/
=> 10130-IsolateLanguageTests

sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java
=> Hide complications header without complication fields #9625

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> sorqa-402 fix2

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
=> sorqa-440 fix 2

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> selector fix

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/report/AggregateReportDto.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/disease/DiseaseConfigurationFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/AggregateReportEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/AggregateReportsEditLayout.java
Reverts hzi-braunschweig/SORMAS-Project#10168
=> Revert "Feature 9770 allow editing aggregated reports for expired age groups"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/users/CreateNewUserPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> Qu auto/sorqa 461

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #3845 - Add lazy loading to event participants grid

sormas-app/app/src/main/java/de/symeda/sormas/app/contact/edit/ContactEditFragment.java
=> #10087 - Add deactivated disease to dropdown list

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #3845 - Add lazy loading to event participants grid - update sorting

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #10171 - Set reporting user when cloning case

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/CreateNewAggregateReportSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
…future aggregate reports"
Fixes #
=> qu-auto/SORQA-473 Automatize "Prevent submission of future aggregate reports [1]"

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasOptionsForm.java
=> #9840 S2S_contacts_change behaviour if share with hand over the ownership = true

sormas-api/src/main/java/de/symeda/sormas/api/user/DefaultUserRole.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/AbstractUserRoleForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/AbstractUserRoleView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleFormHelper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleNotificationsForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleTemplateSelectionField.java
- fill default user role on creation of user role
Fixes #9645
=> #9645 - pre-fill popup with linked default user role

sormas-app/app/src/main/java/de/symeda/sormas/app/settings/SettingsFragment.java
=> #10132 - Fix app crashing when changing language

sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/strings/LanguageDetectorHelper.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/keycloak/KeycloakAdminConsolePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakAdminConsoleSteps.java
added fixes for multiple corner cases
=> #10197-LowerLanguageScanConfidence

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/CreateNewAggreagateReportPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/CreateNewAggregateReportSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-475 Automatize "Make region and district required for aggregate reports [0.5]"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/HealthFacilityValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/envconfig/dto/Environment.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/envconfig/manager/RunningConfiguration.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/CaseApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/PersonApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/CaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/PersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/EditSharesPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/SharesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> Qu auto/s2 s poc

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/tasks/TaskManagementPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
=> SORQA-357 fixing issues

sormas-app/app/proguard-rules.pro, sormas-app/app/src/androidTest/java/de/symeda/sormas/app/lbds/LbdsDtoHelperTest.java
=> Bugfix 9739 lbds minification

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/exposure/ExposureService.java, sormas-backend/src/main/resources/META-INF/persistence.xml, sormas-backend/src/test/resources/META-INF/persistence.xml, sormas-ui/src/test/resources/META-INF/persistence.xml
=> #3915 Set Hibernate to BIND mode

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> Qu auto/sorqa 348

sormas-api/src/main/java/de/symeda/sormas/api/EditPermissionType.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/document/DocumentListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/LayoutWithSidePanel.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentLayout.java
=> #9804: Make documents available after share

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java
=> stabilization SORQA-499 and SORQA-507

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java
=> stabilization SORQA-500

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
=> [#9708] remove getByUuid from facade

.github/workflows/sormas_app_ci.yml, sormas-app/app/build.gradle
=> #10261 upgraded minSdkVersion to 26

sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> SORQA-506 stabilization

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/EditImmunizationPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
added fix
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1732/allure/
=> #10274-FixDeUserLoginTests

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/infrastructure/InfrastructureHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/classification/CaseClassificationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseConfigurationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRoleFacadeEjb.java
=> #8541 Allow read infrastructure data for mobile app users

sormas-ui/src/test/resources/META-INF/persistence.xml
=> #9708 - fix hibernate lazy init issues in UI module tests

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
=> stabilization SORQA-513

sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/ArchitectureTest.java
=> #8541 - add @Permit all on more infrastructure read methods

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/entries/CreateNewTravelEntryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/vaccination/CreateNewVaccinationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> stabilization SORQA-516

sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java
=> #10156 - Clear recovery dates when hidden

sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java
=> #10241 Bugfix QuarantineOrderLayout: ItemCaptionGenerator for ComboBoxes

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java
=> #10341 - Only enable filter if existing

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java, sormas-api/src/main/resources/validations.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRoleFacadeEjb.java
=> fixed #10305

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java
=> stabilization SORQA-529

sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature
=> stabilization SORQA-519 - ignored test with Data Protection Dictionary

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CreateNewCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java
=> Qu auto/sorqa 530

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
=> Qu auto/sorqa 531

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/share/incoming/SormasToSormasShareRequestDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGridComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractFilterForm.java
Fixes #9755
Delete rejected or revoked requests on receiving side
=> #9755 S2S_Revision of the 'share requests' directory_ Part 1 - delete rejected or revoked requests on receiving side

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
=> #10259 [Reporting Tool] Error during Archive / De-archive cases

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/TravelEntryService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
=> stabilization SORQA-535

sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjbTest.java
Fixes #10324
Backported https://github.com/hzi-braunschweig/SORMAS-Project/pull/10379
=> #10324 demis2 sormas not specified tested disease hotfix

sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfo.java, sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/Pseudonymizer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
=> S2S_Cannot accept case sent with "Exclude personal data" #10225

sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/services/TravelEntryService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjbTest.java
=> #10306 Limit query to first found travel entry

sormas-base/pom.xml
=> [#10372] bump snakeyml

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
thanks for the pointer, checks are no as before.
Fixes #9091
=> [#9091] fix valdiation for templated urls

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
=> #8502 - Clear completeness bypassing JPA level

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditAllowedDetailView.java
Fixes #10392 
A friendly reminder for getting my eyes re-checked again :)
=> [#10392] fix missing negation

sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/ReportDataGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/ReportDataView.java
#10128 Refresh aggregate reports after edit and deletion
=> #10128 Refresh aggregate reports after edit and deletion

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
- Fixed method: ContactFacadeEjb.getContactCountsByCasesForDashboard
Fixes #3915
=> #3915 Fixed not matching parameter types in query

sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserRoleFacadeEjbTest.java
=> #10305: Added unit test

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/web/AggregateReport.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/AggregateReportService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/CreateNewAggregateReportSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-465 Automatize "Test Don't summarize aggregated report numbers with those of sub jurisdictions in the aggregate report view [3]"

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #10084 S2S_New Right_ S2S_Process - revoke S2S rights from all users

sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java
=> #10404 - Occupation types let contact and event participant imports fail

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/AbstractDashboardView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DashboardDataProvider.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/contacts/ContactsDashboardView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/contacts/components/ContactsFilterLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/SurveillanceDashboardView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/SurveillanceDiseaseCarouselLayout.java
Fixes #10381 
I picked the commits of #10476 and retested that the dahsboard views still work (and only load data once).
=> #10381 improve dashboard refresh hotfix

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> Bugfix 10496 set present condition accordingly to unknown

sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
=> #10190 allow contact creators access to updateVaccinationStatuses(...)

sormas-ui/src/main/java/de/symeda/sormas/ui/events/AbstractEventView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGrid.java
=> #10438 - Allow users without task access to access events

sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java
=> #10481 - fix the display of email and phone descriptions

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java
=> #10509 - Filters on the Persons Directory are not working

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> #10429 - Allow deletion of cases without contact access

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> SORQA-564 stabilization

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/PersonApiService.java
=> #7749FixTestsSettingPresentCondition

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseGridDetailed.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java
=> Bug 10501 event view rights restrictions

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/SormasToSormasShareInfoFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java
=> #10084 S2S_New Right_ S2S_Process - improvements after testing

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventActionsView.java
=> #10533 - disable event actions page if no event edit user right

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java
=> #10511 - update the person entry lists to use the right user rights

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> Bugfix 10561 poe supervisor is not able to create cases

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureConfigurationFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java
Fixes #10084
Fix for https://github.com/hzi-braunschweig/SORMAS-Project/issues/10084#issuecomment-1271155365
=> #10084 S2S_New Right_ S2S_Process - show/hide ownership filter based on feature configuration

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/config/ConfigProvider.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/user/UserDao.java
=> #10504 - load user roles on fetching a specific user in user dao

sormas-backend/src/main/java/de/symeda/sormas/backend/bagexport/BAGExportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
=> #2332 Renamed READ_ONLY constant, added Javadoc

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
#9852 Event participants newly created for archived events are archived too, addressing feedback of #10413
=> #9852 Events participants created as archived

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java
=> #10527 - fix campaign dashboard when no grouping is specified

sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventListComponent.java
=> #10554 fix contact no events label

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> #10514 -  clear facility name & description

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/EnvLangsTranslations.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/strings/LanguageDetectorHelper.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakLoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
=> #10614-FixLoginTests

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> #10624 Bugfix: Use batched entries instead of the whole list

sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerInterceptor.java
Fixes #9889 
log line looks like this:
```json
{
"resourceType":"AuditEvent",
"action":"D",
"period":{"start":"2022-09-26T15:20:31+02:00","end":"2022-09-26T15:20:48+02:00"},
"recorded":"2022-09-26T15:20:50.144+02:00",
"agent":[{"type":{"coding":[{"system":"https://www.hl7.org/fhir/valueset-participation-role-type.html","code":"110150","display":"Application"}]},"name":"SYSTEM"}],
"source":{"site":"sormas_b","type":[{"system":"http://terminology.hl7.org/CodeSystem/security-source-type","code":"4","display":"Application Server"}]},
"entity":[
"what":{
"reference":"public void de.symeda.sormas.backend.caze.CaseService.deletePermanent(de.symeda.sormas.backend.common.AbstractDomainObject)"
},
"detail":[{"type":"param","valueString":"R7G5UD-WPLSSS-JKHO56-ZO6JSMSE"}]
]}
```
=> [#9889] log deletion

sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> Bugfix 10622 visit contact permanent deletion inconsistency

sormas-ui/src/main/java/de/symeda/sormas/ui/SormasErrorHandler.java, sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/AbstractDocgenerationLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractFilterForm.java
=> #6116 remove print stack trace usage

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/LoginPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakLoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Keycloak.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
Added fixes and refactored duplicated login methods
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1861/allure/
=> #10659-FixKeycloakLoginTests

sormas-e2e-tests/src/test/java/org/sormas/e2etests/runner/CucumberTestRunner.java, sormas-e2e-tests/src/test/resources/features/sanity/web/EventUserRoles.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/PersonsUserRoles.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntryFiltersUserRoles.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntryUserRoles.feature
=> Qu auto/sorqa 571

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonSimilarityCriteria.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/filter/ImmunizationFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSearchField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/birthdate/BirthDateHelper.java
=> Feature 8485 change person search

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> #10514-clear the facility name and description field when is necessary

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
=> #10208 eagerly fetch clinical course of case

sormas-api/src/test/java/de/symeda/sormas/api/EntityDtoAccessHelperTest.java, sormas-backend/src/main/java/de/symeda/sormas/backend/hospitalization/HospitalizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/DtoHelper.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
=> #10208 gracefully handle child dtos that don't have a uuid

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/ContactsDashboardPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature
=> Qu auto/sorqa 586

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDetailedTableViewSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
=> SORQA-581 Stabilize "Test Allow users on national level or with no jurisdiction level to edit all tasks"

sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java, sormas-api/src/main/resources/validations.properties
=> fixed #10700

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/filter/ImmunizationFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractForm.java
=> #8485 - fix visibility of birthdate filters

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeletableUtils.java
=> #10612 Set the full width for reason in Delete with Reason Popup

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
Added a certain health facility when a user with optional health facility permission created a new case
Fixes #10517
=> #10517 Facility is not pre-filled

sormas-api/src/main/java/de/symeda/sormas/api/externaldata/ExternalDataDto.java, sormas-api/src/test/java/de/symeda/sormas/api/ArchitectureTest.java
=> fixed #10731

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> #10698 - Add missing vaccination columns

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
ignore Scenario: Refine the update mechanism between case outcome and person other cause date
=> ignore flaky test

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasRuntimeException.java, sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/entities/SormasToSormasEntityInterface.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/SormasToSormasCaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/SormasToSormasContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/SormasToSormasEventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/rest/SormasToSormasRestClient.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/ShareRequestInfoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/SormasToSormasShareInfoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/IterableHelper.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeletableUtils.java
=> Feature 10625 s2 s show warning and remove share requests when case contact is deleted

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/SymptomsTabPage.java, sormas-e2e-tests/src/main/java/recorders/StepsLogger.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java
=> #10565-OtherNonHemorrhagicSymptom-FixNamings

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJoins.java
=> fix sorting by phone and email #10687

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
Added phone and e-mail validation for 'Source of Information' details on Event page
Fixes #7877
=> #7877 missing phone and e-mail validation 

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGrid.java
=> Bugfix 10701 s2 s display comment in share directory

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/labmessage/SampleReportReferenceDto.java
=> [#10690] support serialization of SampleReportReferenceDto

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/CreateNewAggreagateReportPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/webdriver/RemoteDriverFactory.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/web/AggregateReport.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/AggregateReportService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/CreateNewAggregateReportSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
… aggregate module (mSERS)"
Fixes #
=> qu-auto/SORQA-477 Automatize "Addition of age categories to aggregate module (mSERS)"

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql
=> Automatic deletion based on end of process date #8996

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-612 Stabilize "Test Move health conditions from clinical course to the case"

sormas-app/app/build.gradle, sormas-base/pom.xml
=> [#10823] bump commons text

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java
=> [#9708] better use of createPseudynomizer

sormas-api/src/main/java/de/symeda/sormas/api/externaldata/ExternalDataDto.java
=> fixed #10811

sormas-api/src/main/java/de/symeda/sormas/api/externaldata/ExternalDataDto.java, sormas-api/src/test/java/de/symeda/sormas/api/ArchitectureTest.java
The class ExternalDataDto implements HasUuid. Remove the exception from ArchitectureTest.
Fixes #10750
=> #10750 ExternalDataDto needs to implement HasUuid 

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseJurisdictionType.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/enum.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseCriteriaHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java
=> #10837 - Add jurisdiction type filter to case filter form

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
=> Dependencies for CASE_CREATE user right #10735

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-592 Stabilize "Verify that the Aggregate Report View does not sum the Aggregate Report Numbers with those of sub jurisdictions"

sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-632 Stabilize "Add a duplicate warning when creating and editing aggregate reports"

sormas-api/src/test/java/de/symeda/sormas/api/utils/UtilDateTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasCaseFacadeEjbTest.java
=> #10868 - put back the unit tests from development

sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-635 Stabilize "Test Group aggregated reporting data (mSERS) by jurisdiction and epi week"

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
=> UserRight.CASE_VIEW: Add dependency TASK_VIEW #10735

sormas-e2e-tests/build.gradle, sormas-e2e-tests/gradle/wrapper/gradle-wrapper.properties
=> gradle update

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/entries/EditTravelEntryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/tasks/TaskManagementPage.java
=> qu-auto/SORQA-649 Stabilize "Test Assigned to user list of task should consider related entities jurisdiction"

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
Yet another useful optimization found while working on #9708
Needs rebase on #10861
=> [#9708] toPseudonymizedDtos can be implemented in super class

sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java, sormas-api/src/main/java/de/symeda/sormas/api/deletionconfiguration/DeletionConfigurationFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/DeletionConfigurationFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java
=> #10901 - Execute automatic deletion from UI

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
set facility category disabled if facility is disabled
Fixes #10775
=>  #10775 National Clinician - Case Person & Travel Entry Person - Can Edit Facility Category but cannot save

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/AboutPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
=> #10702-FixAboutTestOverRelease

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/surveillancereport/SurveillanceReportList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/surveillancereport/SurveillanceReportListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/LayoutWithSidePanel.java
=> #8463 - Users with read permission should be able to see more details (Side-components)

sormas-backend/src/main/java/de/symeda/sormas/backend/exposure/Exposure.java
=> lazy fetching of Exposure.contactToCase #10695

sormas-api/src/main/java/de/symeda/sormas/api/epidata/EpiDataDto.java
=> 10208_exposures_are_not_coppied_when_convert_contact_to_case

sormas-rest/src/main/java/de/symeda/sormas/rest/logging/RequestResponseLogger.java
=> RequestResponseLogger: Reduce Log-Level to TRACE #9899

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java
=> qu-auto/SORQA-651 Stabilize "Add a person search option on creation forms"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java
=> qu-auto/SORQA-652 Stabilize "Test for navigating through Case, Contact and Immunization cards on Edit Person Page"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
=> qu-auto/SORQA-653 Stabilize "Test pseudonymization in immunization"

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
The window for selecting the import method disappear after the user selected the import method.
Fix #9133
=> Users can use options from dropdowns when opening import windows -fix #9133

sormas-backend/src/test/java/de/symeda/sormas/backend/JUnitFrameworkTest.java, sormas-base/pom.xml
=> #10793 Make JUnit4 available for testcontainers, avoid other usage

sormas-e2e-tests/src/test/resources/features/sanity/api/Api.feature
=> precon decorator changed

sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/ShareRequestInfoService.java
=> #10931 [S2S] fix automatic deletion when S2S revoke is needed  

sormas-api/src/test/resources/logback-test.xml, sormas-backend/src/test/resources/logback-test.xml, sormas-ui/src/test/resources/logback-test.xml
=> #10214 - log only warnings and errors in tests too from ehcache

sormas-backend/src/test/java/de/symeda/sormas/backend/common/HistoryTablesTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/StartupShutdownServiceTest.java
=> #10801 improve history tables test

sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/classification/CaseClassificationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/district/DistrictFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/region/RegionFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/SormasToSormasShareInfoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/symptoms/SymptomsFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
=> [#9708] provide toDtos and toRefDtos and use it in the code base

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> #10933-FixIgnoredEventTests

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> #4621 - fix lowercase database field in Android

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseListEntryDto.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactListEntryDto.java, sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantListEntryDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/transformers/CaseListEntryDtoResultTransformer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/transformers/ContactListEntryDtoResultTransformer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListEntry.java
=> #6054 Additional info in person form side boxes

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java, sormas-base/setup/sormas.properties
=> #9965 Fix: Define default allowed filetypes

sormas-backend/src/main/java/de/symeda/sormas/backend/ExtendedPostgreSQL94Dialect.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/H2Function.java
=> #10987 [SurvNet] Filter 'only cases changed since last shared with reporting tool' does not work

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/TravelEntryApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/TravelEntrySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/api/Api.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntry.feature
=> Qu auto/oldfake fixes

sormas-backend/src/test/resources/logback-test.xml, sormas-ui/src/test/resources/logback-test.xml
=> #10214 - log only errors in tests too from ehcache

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/processed/ProcessedDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ProcessedCaseDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ProcessedContactDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/ProcessedEventDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/ProcessedEventParticipantDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ProcessedImmunizationDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ProcessedSampleDataPersister.java, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasCaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasContactFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasEventFacadeEjbTest.java
=> #10544 S2S_Changing person sync - update only persons not owned

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java
The only number which is higher than the number of PRs for #9708 is the number of hotfixes for `1.76`.
=> [#9708] use toPseudonymizedDtos more often

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/AboutPage.java
=> qu-auto/SORQA-683 Stabilize "Check Data Protection Dictionary existence and download"

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/finding.md, docs/CONTRIBUTING.md
=> #10897 new ticket type finding

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java
=> qu-auto/SORQA-686 Stabilize "Add a Task from event and verify the fields"

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> Add investigation & outcome date to detailed Case Export

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasePersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseEditComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryPersonView.java
=> #10543 S2S reduction of possibility to edit person data - disable person form when there is no owned associated object

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
=> qu-auto/SORQA-690 Stabilize "Test Allow users on national level or with no jurisdiction level to edit all tasks"

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java
Found while working on #9708
Fixed a nasty looking warning in my IDE.
=> [#9708] fix illegal managed bean warning

sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/DocGenerationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderDocumentsComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseImmunizationsComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java
...
yet another refactoring for #9708
We usually name this `AdoName` + `Criteria` except in this case.
=> [#9708] rename to VaccinationCriteria for consistency

sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java
=> [#9708] fix fallout from renaming vaccination criteria

sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/DirectoryImmunizationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjbTest.java
=> #11068 - Filter immunizations by UUID

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
=> fix sorqa-696

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
=> qu-auto/SORQA-691 Stabilize "Document Templates create quarantine order"

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AdoptAddressLayout.java
=> #7062 added default style to show adress button

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/environmentdata/manager/EnvironmentManager.java
added checks and improved exceptions
=> #11080UpdateResponseErrorCodeCheck : 

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
=> qu-auto/SORQA-694fix Stabilize "Add two positive Pathogen Test Result of different diseases to a Sample of a Case"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java
=> Qu auto/sorqa 702

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-704 Stabilize "Addition of age categories to aggregate module (mSERS)"

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/PatientDiaryClient.java
=> #8640: Avoided NPE

sormas-backend/src/main/java/de/symeda/sormas/backend/FacadeHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #11098 - fix NPE exception which blocks Survnet import

sormas-ui/src/main/java/de/symeda/sormas/ui/externalsurveillanceservice/ExternalSurveillanceShareComponent.java
=> #11110 fix npe when event is created

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageController.java
=> Bugfix 11107 external message icon not visible

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java, sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/ExternalMessageProcessingUIHelper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java
=> #6053 add create/link buttons to person sideboxes

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/FacilitiesTabPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/FacilitySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Country.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Facility.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Keycloak.feature
@precon changes + new tests added
=> SORQA-707 @precon changes + new tests added

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> sorqa-699 fix

sormas-e2e-tests/build.gradle, sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/strings/LanguageDetectorHelper.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/environmentdata/manager/EnvironmentManager.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/runner/CucumberTestRunner.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
added fix into language library
=> #1111FixHospitalInformantLoginTest

sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
=> fix, changed user

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java
=> qu-auto/SORQA-708 Stabilize "Test Allow editing and deletion of aggregate report data"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/commonSteps/ResponseChecksSteps.java
=> #10575AdjustAPIResponseChecks

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
=> fix sorqa-646

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> fix sorqa-709

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseIndexDto.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactIndexDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AbstractContactGrid.java
=> #9611 Move visits calculations to DTOs for Cases and Contacts

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
=> Bugfix case deletion

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/commonSteps/ResponseChecksSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-616 Stabilize "Test Reduced entry option for vaccinations"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-616fix Stabilize "Test Reduced entry option for vaccinations"

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/SormasToSormasCaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/SormasToSormasContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/SormasToSormasEventFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java
=> #8471 S2S_automatic update in the share-box - force new transaction on the backend share method

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/commonSteps/ResponseChecksSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> #5762LinkEventToCaseTest

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/AboutPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature
=> qu-auto/SORQA-683 fix 

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java
=> Bugfix 6053 test findings

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitService.java
=> #11187 - Don't sync visits if user has no contact view right

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> Qu auto/sorqa 727

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> qu-auto/SORQA-739 Stabilize "Test Adjustments to the jurisdiction definition process of event participants"

sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> qu-auto/SORQA-738 Stabilize "Link Event to a Case"

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantQueryContext.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/DirectoryImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/services/TravelEntryService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/performance/PerformanceLogAnalysisGenerator.java
=> Change 11013 two step get index list

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/LoginPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2172/allure/#suites/fa2cf888db23ffdcb968782d71907083Updated
=> #10635CreateLoginLanguageCheckTest

sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-747 Stabilize "Test Limited disease user property should not be applied to mSERS aggregated reporting"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> qu-auto/SORQA-746 Stabilize "Create and edit a new event"

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/components/linelisting/LineListingLayout.java
=> #10395 make 'Facility name' field not mandatory in Case Line Listing

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryController.java
removed the second trigger for DirtyCheckPopup
Fixes #9811
=> #9811-TravelEntryDataForm: DirtyCheckPopup is triggered twice

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/CreateNewAggregateReportSteps.java
=> qu-auto/SORQA-761 Stabilize "Add a duplicate warning when creating and editing aggregate reports"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java
=> qu-auto/SORQA-763 Stabilize "Verify that the Aggregate Report View does not sum the Aggregate Report Numbers with those of sub jurisdictions"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/CountriesTabPage.java
=> qu-auto/SORQA-759 Stabilize "Check German infrastructure data for countries"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/CreateNewTravelEntrySteps.java
=> qu-auto/SORQA-765 Stabilize "Create a case for a travel entry"

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> fixed #11120

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasePersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/CaseEpiDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSideComponentsElement.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/PaginationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java, sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss
=> #6052 - Display side component in all person views

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/CountriesTabPage.java
=> no of countries xpath change

sormas-e2e-tests/src/test/java/org/sormas/e2etests/runner/CucumberTestRunner.java
=> rerunAttempts = 3

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
=> qu-auto/SORQA-559 Stabilize "Test Travel Entry conversion to case"

sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
=> Qu auto/sorqa 577

sormas-e2e-tests/src/test/java/org/sormas/e2etests/runner/CucumberTestRunner.java
updated rerun param to 1 to decrease long regression run
=> #10673-UpdateRerunParameter

sormas-ui/src/main/java/de/symeda/sormas/ui/user/UsersView.java
=> #11240 - fixing the counter is UsersView

sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> wrong test, ignored, need to fix by other team

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/CountriesTabPage.java
=> qu-auto/SORQA-759 Stabilize 'Check German infrastructure data for countries'

sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java
Fixes #11161
Please do the merge if it passes the review.
=> #11161 [S2S] Share box 'Share with' text field is duplicated after revoking a share request - cleanup displaying share info on the UI

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDetailedTableViewSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseViews.feature
=> qu-auto/SORQA-782 Stabilize "Create a new Case and check details in Detailed view table"

sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskController.java
=> #11226 - set assignedUserBy in bulk edit mode

sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/epidata/EpiDataFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
=> #11192 Can't send Exposures via REST - fixed NullPointer exception when saving exposure without location

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> Qu auto/sorqa 786

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/users/UserRolesPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserRolesSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> qu-auto/SORQA-775 Stabilize "Edit and create user roles"

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
=> #11313 - fix item counter in case of bulk edit mode

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/ContactService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/ExposureDetailsService.java
Fixes - Germany Western Europe
=> germany western europe

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/mSers/MSersDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mSERS.feature
=> qu-auto/SORQA-791 Stabilize "Test Add a view to list aggregate report data and to highlight duplicates"

sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposuresField.java
=> #11337 - fix NPE

sormas-e2e-tests/gradle.properties
Tested on representative example with @Case
=> Qu auto/enable configuration cache

sormas-e2e-tests/gradle.properties
=> org.gradle.unsafe.configuration-cache=false

sormas-e2e-tests/gradle.properties
=> org.gradle.caching=false

sormas-e2e-tests/gradle.properties
=> increased heap size + caching

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGridFilterForm.java
=> #11263 - delete unnecessary style

sormas-e2e-tests/src/test/resources/features/sanity/web/Country.feature
=> removed NC from precon; Germany in Western Europe from Central Europe

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/vaccination/CreateNewVaccinationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-795 Stabilize "Test Reduced entry option for vaccinations"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/immunizations/EditImmunizationPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/EditImmunizationSteps.java
=> qu-auto/SORQA -Test Immunizations III: Vaccination lists and forms

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/SymptomsTabPage.java
=> qu-auto/SORQA-Verify that Page can not be saved if a future date is set for Date of symptom onset

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactImporter.java
=> #11335 - fix invalid other facility exception

sormas-e2e-tests/gradle.properties
=> remove gradle cache test

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGrid.java
=> #10537 - Layout lab message directory

sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasCaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasContactFacadeEjbTest.java
=> #10852: Added tests

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
=> qu-auto/SORQA-810 Stabilize "Event group screen from Event Directory Page"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> Qu auto/sorqa 815

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/SharesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-639 Delete a case in source system with handing ownership before acceptance

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/SharesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
=> qu-auto/SORQA-641 Stabilize "Delete a contact in source system with handing ownership before acceptance"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
=> qu-auto/SORQA-521 Stabilize "Test Lab officers should have full access to entities whose sample was assigned to the lab officers lab"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> sorqa-544 SORDEV-7491

.github/workflows/ci.yml
=> [#7542] use trivy

.github/workflows/ci.yml, sormas-base/pom.xml
=> [#7542] add sonar cloud CI pass

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-822 Stabilize "Delete created case"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/EditSamplePage.java, sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationWithLoincTemplate.json, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/demis/DemisApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/messages/MessagesDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> SORDEV-9470

sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/EventActionIndexDtoReasultTransformer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/QueryContext.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupQueryContext.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleQueryContext.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/incoming/SormasToSormasShareRequestFacadeEJB.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskQueryContext.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbUnitTest.java
Fixes #11014
Details to be added on the ticket when closing it
**Task**
* Number of tasks: 131680
* Performance before refactoring:
* Performance after refactoring:
**Sample**
* Number of samples: 819469
* Performance before refactoring:
* Performance after refactoring:
**ExternalMessage**
* Number of messages: 39424
* Performance before refactoring: 
* Performance after refactoring:
**Action**
* Number of actions: 262144
* Performance before refactoring:
* Performance after refactoring: 
**EventGroup**
* Number of event groups: 163840 
* Performance before refactoring:
* Performance after refactoring: 
**Share requests index list method was not  refactored because it is more performant as it is now.**
* Number of share requests: 112640
* Performance before refactoring:
* Performance …
=> #11014 Two step getIndexList for other entities

.github/workflows/ci.yml
=> [#7542] only comment on PR event, not on branch push

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractView.java
Fixes #9054 missing null check
=> #9054 added missing null check

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> SORDEV-8862

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleAssociationType.java, sormas-api/src/main/resources/captions.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSideComponentsElement.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListComponent.java
=> #10714 - Add samples card to person view

sormas-ui/src/main/java/de/symeda/sormas/ui/user/AbstractUserRoleView.java
=> #11476 apply user role template should be disabled for users without user role edit right

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/messages/MessagesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-831 Automatize "[4851] [DEMIS Interface] Introduce option to reject lab messages [3]"

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-834 Stabilize "Check reference definition for cases"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
=> qu-auto/SORQA-832 Stabilize "Testing Event group adding for new event"

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureDaoHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureFieldsDependencyHandler.java, sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_case_new_layout.xml
=> #11427 - Remove required flag from facility details

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/event/EventParticipant.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
=> #11428 - Automatically load location fields for event participants

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java
=> qu-auto/SORQA-812fix

sormas-app/app/src/main/java/de/symeda/sormas/app/util/DataUtils.java
=> #11497 - Use buildCaption when building infrastructure items

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> Qu auto/sorqa 575

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationTemplateReportId.json, sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationTemplateTelcom.json, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/demis/DemisApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/messages/MessagesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-836 Automatize "[4106] Improve the mapping/prefilling the new case/new sample forms when processing a DEMIS LabMessage"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
=> qu-auto/SORQA Stabilize "Test Access to the event directory filtered on the events of a group"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/demis/DemisApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/messages/MessagesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> SORDEV-12445

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> SORDEV-6171

sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> Qu auto/sorqa 841

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-842 Stabilize "Test Handle New Profile: Process entities related to the same reportId"

sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-844 Add one test from each instances (s2s, s2d) to precon tests

docs/TROUBLESHOOTING.md
Fixes #11467
* clean separation of production and development aspects
* better differentation between SQL performance and java code performance
* guide on how to create sql analysis on dev system
* tips on how to interpret analysis
* tips on how to speed of iteration time when improving a query
* table of contents
=> #11467 updated performance section of troubleshooting guide

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-843fix Stabilize "Test delete option in Lab Messages"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> SORDEV-5629

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
=> #11482 s2s enable delete button for read only entities

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-846 Automatize "[DEMIS2SORMAS] Test messages directory status quick filters"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditContactsPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/CreateNewEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/EventService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> SORDEV-9104

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> Qu auto/sorqa 850

sormas-e2e-performance-tests/SormasPoc.jmx
=> 11474-FixPerfFailingTests

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/tasks/TaskManagementPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
=> Qu auto/sorqa 851

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> sordev-11838

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonSimilarityCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java
=> #11527 - Reintroduce proper similarity name search

sormas-e2e-tests/src/test/resources/features/sanity/web/UserRoles.feature
=> qu-auto/SORQA-856 Stabilize "Validate newly created User Role cannot be deleted if assigned towards an user"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/LoginPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> qu-auto/SORQA-858 Stabilize "Change password of SORMAS user (by admin)"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/TravelEntryApiService.java, sormas-e2e-tests/src/test/resources/features/sanity/api/Api.feature
=> Qu auto/1402 api fix travel entries

sormas-base/pom.xml, sormas-base/setup/keycloak/keycloak-setup.sh, sormas-ui/src/main/java/de/symeda/sormas/ui/security/MultiAuthenticationMechanism.java, sormas-ui/src/main/java/de/symeda/sormas/ui/security/config/OpenIdAuthenticationExtension.java
Needed param changes in keycloak-setup.sh
Fixes #10387
=> #10387 Update to keycloak 21.0.1

sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntry.feature
=> qu-auto/SORQA-862 Stabilize "Test DEA TravelEntry import"

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> combobox language changes

sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntryFilters.feature
=> Qu auto/sorqa 787

sormas-e2e-tests/src/test/resources/features/sanity/web/EventAction.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Statistics.feature
=> qu-auto/SORQA-854 Implement Tag Export and Statistic Feature for Automated Tests

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #10298 Visibility of event participants after archiving the event

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/DistrictsSteps.java
=> sleep for create new disctrict

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/keycloak/KeycloakAdminConsolePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/keycloak/KeycloakLoginPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakAdminConsoleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakLoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Keycloak.feature
=> qu-auto/SORQA-859 Stabilize "SORMAS - Keycloak Synchronisation (manual sync)" and "SORMAS - Keycloak Synchronisation (automatic sync)" for release env

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/keycloak/KeycloakLoginPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakLoginSteps.java
=> qu-auto/SORQA-859fix

sormas-backend/README.md, sormas-backend/src/test/README.md
=> #11568 documentation on how to do backend unit testing

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #11555 calculate classification for cases created from event participant

sormas-e2e-tests/src/test/resources/features/sanity/web/UserRoles.feature
=> unignore @10422 - test back to stable

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsViewConfiguration.java
=> #10298 fix relevance status filter on the event participants list

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/keycloak/KeycloakAdminConsolePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/keycloak/KeycloakAdminConsoleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> qu-auto/SORQA-660 Stabilize "Create a new SORMAS user, check login and disable"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
=> qu-auto/SORQA-872 Stabilize "Test for exporting and importing case contact"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-873 Stabilize "Test Handle New Profile: Process entities related to the same reportId"

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> qu-auto/SORQA-875 Stabilize "Add reason for deletion to confirmation dialogue"

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventActionsGrid.java
Only display delete reason column when user has the respective user right
Fixes #11638
=> #11638 - Fix delete reason column

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/labmessage/processing/AbstractLabMessageProcessingFlow.java
=> #11449: fixed sorting, added prefilling of events

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> @#10111 test stabilization

sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/area/AreaFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/community/CommunityFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/continent/ContinentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/country/CountryFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/district/DistrictFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/pointofentry/PointOfEntryFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/region/RegionFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/subcontinent/SubcontinentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java
Found while working on #9708 
Instead of cascading the service injection, we just inject the `UserService` in the abstract parent class.
=> [#9708] remove user service injection

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java
Disable buttons when person is deselected
Fixes #11567
=> #11567 - Fix person merge buttons

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
Align backend event location validation with UI validation
Fixes #11502
=> #11502 - Fix backend event location validation

.github/dependabot.yml
Fixes https://github.com/hzi-braunschweig/SORMAS-Project/issues/11676
=> [#7507] Add dependabot config for GH Actions

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #10053 - Don't create duplicate investigation tasks

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/CommunitiesSteps.java
=> SORDEV-8050 test stabilization

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/EditSharesPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/SharesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-550 Automatize "S2S_deactivate share parameter 'share associated contacts' (for cases) [2]"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/shares/SharesDirectorySteps.java
=> qu-auto/SORQA550fix Automatize "S2S_deactivate share parameter 'share associated contacts' (for cases) [2]"

sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/LanguageChecks.feature
ignore Check language options in Data Dictionary depending on the user language setting
ignore Check Data Protection Dictionary existence and download
=> ignore tests

docs/SORMAS2SORMAS.md
Fixes #11399 
@leventegal-she : Can you add one quick description of the ignore property to this PR?
=> [#11399] clarify sync behaviour

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesView.java
=> #11627 - Duplicate case query is triggered twice on every search

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
=> #11687 - Fix merge based on regions

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SORQA-552 Automatize "S2S_added sample after sharing a case/contact does not get shared [2]"

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataView.java
=> #11251 - Update travel entry on case creation

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> #11668 - Fix relevance filters for person samples

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbTest.java
=> #11704: Added diseaseVariant determination to LabMessages

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> Qu auto/sorqa 879

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature
=> qu-auto/SORQA-683fix2 Stabilize "Check Data Protection Dictionary existence and download" DE Only

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #10298 fix reset filters on the event participants page

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
=> fixed #11421 again

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> qu-auto/SIRQA-889 Stabilize "S2S_Processed lab messages should be transferred [2]"

sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-881 Stabilize "Test Handle New Profile: Process entities related to the same reportId"

sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsCaseGrid.java
=> #11720 - Fix statistic infrastructure captions

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/labmessage/processing/AbstractLabMessageProcessingFlow.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/AbstractProcessingFlow.java
=> #11454: Prefilling reportDate with messageDate

sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java
=> #11717 - [Statistics] Date range intervals are not calculated correctly

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/EditSamplePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/vaccinations/CreateNewVaccinationPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/vaccination/CreateNewVaccinationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> SORDEV-12095

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> fixed #11744

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/actions/EditActionPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> fix s2s mergen

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/CreateNewSamplePage.java
=> fix pathogen tests - lab id

sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java
=> #3428 - fix UI stylings for Event Actions

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
Fixes S2S_Processed lab messages should be transferred [2]
=> fix S2S_Processed lab messages should be transferred [2]

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventActionsPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> Qu auto/sorqa 910

sormas-ui/src/main/java/de/symeda/sormas/ui/hospitalization/PreviousHospitalizationsField.java
=> fixed #11752

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Countries.java, sormas-api/src/main/resources/countries.properties, sormas-backend/src/main/resources/sormas_import_all_countries.csv
=> #5680 - Add Ivory Coast to default country import

sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/services/TravelEntryService.java
=> fixed #11779

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
=> #11457: Added reinfection to CaseCreateForm

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> id changed for Link to Event from Bulk Actions button

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/EventParticipantApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventParticipantSteps.java
=> event participant api fix

sormas-api/src/main/java/de/symeda/sormas/api/contact/MergeContactIndexDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
=> #5550 - Pseudonymize data in cases merge view

sormas-api/src/main/java/de/symeda/sormas/api/utils/LocationHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
=> #8213 - Reset continent on country removal

sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/strings/LanguageDetectorHelper.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
S2S - Share a Contact having a sample implementation
=> Qu auto/sorqa 902

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
=> #5550 - pseudonymize AgeAndBirthDateDto from MergeContactIndexDto

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventParticipantSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
test implementation SORQA-372 SORDEV-10280
=> test implementation SORQA-372 SORDEV-10280

sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/SampleShareDataBuilder.java
=> #4959 fix for accepting case with samples

sormas-api/src/main/java/de/symeda/sormas/api/contact/MergeContactIndexDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/MergeContactsGrid.java
=> fixed #11793

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java
=> #7647 make tsv column readonly

sormas-performance-gatling/src/main/java/gatling/envconfig/configprovider/ConfigFileReader.java
=> #11543-GatlingPOC

sormas-api/src/main/java/de/symeda/sormas/api/document/DocumentDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/EventDocumentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/QuarantineOrderFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/eventimport/EventImportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/document/DocumentFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DocumentUploadFinishedHandler.java
=> Change 4959 fix notnull field erros

sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
Fixes - test delete option in lab message
=> fix Test delete option in Lab Message

sormas-e2e-tests/build.gradle, sormas-e2e-tests/src/main/java/org/sormas/e2etests/helpers/parsers/XMLParser.java
implemented and tested XML parser for survnet xml tests
=> #11876-AddXMLParser

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
=> #11872 - Consider both entries for merge view filters

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteRestoreController.java
=> #11327 - Show warning hint before restore popup

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
=> #11872 - Exclude deleted cases from duplicate merging

sormas-api/src/main/java/de/symeda/sormas/api/contact/MergeContactIndexDto.java
=> #11893 - Do not compare merge contacts by uuid

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/AboutPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Survnet.feature
=> qu-auto/SORQA-963 Automatioze "Test SurvNet Converter installed correctly". Added two new methods to check the survnet converter version.

sormas-api/src/test/java/de/symeda/sormas/api/utils/DateHelperTest.java
Changes one failing test concerning #11032
=> #11032 Make DE PM suffix test work with JDK 11 and 17

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/commonSteps/ResponseChecksSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature
=> #SORQA-939

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/share/ShareRequestIndexDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/outgoing/ShareRequestInfoFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestsView.java
=> #11962 S2S - Error when ordering by Sender name in Outgoing tab

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/aCommonComponents/GeneralActions.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/aCommonComponents/GeneralActionsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/SharedCases.feature
addressed updates, implemented universal method for not enabled fields, updated wrongly developed method checking if fields are read only
RUN:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2820/allure/#suites/3110d698bec0ca1c90cf6c698c6d9772/d8e5403d85bc3a3d/
Fails due to sharing issue.
=> #SOR-4489v2 : 

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/survnet/SurvNetSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Survnet.feature
=> qu-auto/sorqa 957 qu-auto/SORQA-957 Test send simple Case from SORMAS to "Meldesoftware". Fix xmlFile Document moved to specific methods.

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/sample/SampleEpiCurveComponent.java
=> #12001 Sample bar chart shows wrong results

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryList.java
=> #12043 - add missing check for TRAVEL_ENTRY_EDIT

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasePersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSideComponentsElement.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryPersonView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryListComponent.java
=> #11518 - Enable the cards on the person page based on the rights

.github/workflows/ci.yml, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
=> #12061 - Fix merge filter performance issues

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/vaccination/CreateNewVaccinationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Vaccination.feature
=> qu-auto/SORQA-238hms qu-auto/SORQA-238 Automatize "Test Adjusted vaccination status calculation". Remaining steps have been added.

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-base/setup/sormas.properties
=> #12022: Make DEMIS reference in properties generic

sormas-api/src/main/java/de/symeda/sormas/api/EditPermissionType.java, sormas-api/src/main/java/de/symeda/sormas/api/MergeFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ProcessedCaseDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/services/TravelEntryService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEditRightsTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/MergeContactsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/MergeContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractMergeGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/LayoutWithSidePanel.java
=> Feature 11517 cleanup merge error messages

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java
=> #12099 - Add person-related fields to external messages

docs/SERVER_CUSTOMIZATION.md, sormas-api/src/main/java/de/symeda/sormas/api/deletionconfiguration/DeletionReference.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> Feature 12067 report deletion reference

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
=> #12103 Users without deletion rights can not merge or pick cases

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/area/AreaDto.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/continent/ContinentDto.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/subcontinent/SubcontinentDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchiveHandlers.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchivingController.java
- fixed archive issues and android sync
Fixes #11463
=> #11463 Add bulk action progress window to "Archive" and "Dearchive" bulk actions 

sormas-api/pom.xml, sormas-backend/pom.xml, sormas-ui/pom.xml
=> #12219 Added guava where it is directly used

sormas-api/pom.xml, sormas-rest/pom.xml
Fixes #11963 (missing transitive dependencies of `sormas-api`).
=> #11963 fix scope of sormas api dependencies

sormas-app/versioning.gradle, sormas-base/dev.env.example
Fixes #12074
Solves flaws when running `build-with-app` or using `MVN_OPTIONS`
=> #12074 improve script

sormas-api/src/main/java/de/symeda/sormas/api/environment/EnvironmentCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/environment/EnvironmentIndexDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/environment/EnvironmentFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/ControllerProvider.java, sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java, sormas-ui/src/main/java/de/symeda/sormas/ui/ViewModelProvider.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentGridComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/RelevanceStatusFilter.java
=> #11534 Add an environment directory for the web app

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/survnet/SurvNetSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Survnet.feature
=> qu-auto/SORQA-1011 Automate "Bulk sending cases from SORMAS to "Meldesoftware""

docs/DEVELOPMENT_ENVIRONMENT.md, sormas-base/dev/build.sh, sormas-base/dev/collect-serverlibs.sh
Fixes #12074
I addressed the remarks in comment https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12074#issuecomment-1618367391, but I am sceptical if we should provide more howto to setup a run configuration (assumption: The developer knows how to operate his IDE).
=> #12074 review findings

sormas-backend/src/main/java/de/symeda/sormas/backend/user/CurrentUserService.java
=> #12182 - Fix lazy initialization issues

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
=> #12218 - Copy address on merge

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java
=> #12084 - False requirement field for Point of Entry

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGroupController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupListComponent.java
=> #11946- fix event group bugs

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/EventService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/survnet/SurvNetSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Survnet.feature
=> qu-auto/SORQA-1030 Implement "Check Event type Cluster when sending from SORMAS to Meldesoftware"

sormas-base/pom.xml
=> #12242 Dependency updates

sormas-e2e-tests/src/main/java/org/sormas/e2etests/webdriver/RemoteDriverFactory.java, sormas-e2e-tests/src/test/resources/features/sanity/web/SharedCases.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/SharedContacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/SharedPersons.feature
added admin users into existing tests and corrections
=> SORQA-993 : 

sormas-api/src/main/java/de/symeda/sormas/api/CountryHelper.java, sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/labmessage/TestReportDto.java, sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/TestReport.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/TestReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTest.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #12314 - Add new ct value fields

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/labmessage/TestReportDto.java, sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/TestReport.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/TestReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTest.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/externalmessage/SormasToSormasExternalMessageDtoValidator.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/labmessage/TestReportFacadeEjbMappingTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/validation/InfraValidationSoundnessTest.java
=> #12318 - Add prescriber fields to pathogen tests and test reports

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/country/CountryFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/country/CountryFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/externalmessage/SormasToSormasExternalMessageDtoValidator.java
=> #12325 - Add getCountryByIsoCode facade method

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/messages/MessagesDirectoryPage.java, sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationTemplateMultiplePathogen.json, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/demis/DemisApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/demisSteps/DemisSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-980 Demis - Process a Lab message that has multiple pathogen test in a sample

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/messages/MessagesDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/DemisWeb.feature
=> qu-auto/SORQA-1049 Stabilize "Demis - Process a Lab message that has multiple samples"

sormas-backend/src/main/resources/README.md
=> #11981 added readme to explain source of default infrastructure data

docs/CONTRIBUTING.md
=> #12243 process documentation for automatic dependency update PRs

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> #12332 - Remove unsupported feature config

sormas-api/src/main/java/de/symeda/sormas/api/customizableenum/CustomizableEnumType.java, sormas-api/src/main/java/de/symeda/sormas/api/environment/environmentsample/Pathogen.java, sormas-api/src/main/resources/enum.properties, sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #11840 Add a new customizable enum called Pathogen

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/environment/EnvironmentDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/component/dialog/SynchronizationDialog.java, sormas-app/app/src/main/res/layout/fragment_environment_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_environment_read_layout.xml
=> #12030 - Add a create/edit form for environments in the mobile app

sormas-ui/src/main/webapp/WEB-INF/web.xml
=> #12448 - Enable session timeout

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldConfiguration.java
=> #12391 Add new eSanté pathogen test fields to the user interface

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageMapper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/AbstractProcessingFlow.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java
=> Feature 12392 include new e santé fields in the processing logic of external messages

sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSample.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/RequestedPathogensConverter.java, sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #11721 - Change requested pathogen tests column type

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/api/Case.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/api/EpiData.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/api/HealthConditions.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/api/PointOfEntryDetails.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/api/PortHealthInfo.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/CaseApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/api/sormasrest/CaseHelper.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/CaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseImportExportSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/SharedCases.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntry.feature
created test, refactoring and fixes
=> SORQA-1063

sormas-app/app/src/main/java/de/symeda/sormas/app/login/LoginActivity.java
=> #12368 - Fix user redirection

sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationController.java
=> #12346 - Delete archived immunizations

sormas-api/src/main/java/de/symeda/sormas/api/environment/environmentsample/EnvironmentSampleDto.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/environment/environmentsample/EnvironmentSample.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/environment/environmentsample/EnvironmentSampleDtoHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSample.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleFacadeEjbTest.java
=> #12501 - Add report date to environment sample

sormas-app/app/src/main/java/de/symeda/sormas/app/report/aggregate/AggregateReportsFragment.java
=> #11262 - Fix invalid epi week selection end of year

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
=> #12257 - Fix bulk progress window counts

sormas-app/app/src/main/java/de/symeda/sormas/app/report/aggregate/AggregateReportsFragment.java
=> #11262 - Avoid crash on sync without epi week

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageMapper.java
=> #12366 - Map facility type

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
=> #12574 - Saving changes after archive is not possible

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java, sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGridFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessagesView.java
=> #12549 - Hide unused elements in LUX

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/contact/edit/ContactEditFragment.java, sormas-app/app/src/main/res/values/strings.xml
=> #8337 - Show icon to create a case from contact as we have in the webapp

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/user/UserDtoHelper.java
=> #9905- make sync work for users without role

sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestType.java, sormas-api/src/main/resources/enum.properties
=> #12698 - Add TMA as new test type

sormas-backend/src/main/java/de/symeda/sormas/backend/environment/Environment.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentService.java
=> #12669 - Sync environments based on samples

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonSimilarityCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java
=> #12750 - Remove matchMissingInfo property

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/ExternalMessageProcessingUIHelper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/HasName.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SamplesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/SampleController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/SampleDataView.java
=> #12485 - redirect after sample delete to associated case's page

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java
=> #11435 Assign multiple limited diseases to users

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/strings.properties, sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantNewActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantNewFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/util/Bundler.java, sormas-app/app/src/main/res/layout/fragment_event_participant_new_layout.xml, sormas-app/app/src/main/res/values/strings.xml, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantsLineListing/layout/LineListingLayout.java
=> #12604 - Add a line-listing feature to event participants

sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantsLineListing/layout/LineListingLayout.java
=> #12604 - Add a line-listing feature to event participants - fix caption

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDao.java
=> #4837 - Fix the case filtering

sormas-api/src/main/java/de/symeda/sormas/api/environment/environmentsample/EnvironmentSampleIndexDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestDto.java, sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java, sormas-api/src/main/resources/captions.properties, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/sample/PathogenTest.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/sample/PathogenTestDtoHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/component/controls/ControlTextReadField.java, sormas-app/app/src/main/java/de/symeda/sormas/app/environment/edit/EnvironmentEditSampleListFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/pathogentest/edit/PathogenTestEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/pathogentest/read/PathogenTestReadFragment.java, sormas-app/app/src/main/res/layout/fragment_pathogen_test_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_pathogen_test_read_layout.xml, sormas-app/app/src/main/res/layout/row_sample_test_layout.xml, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTest.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/pathogentestlink/PathogenTestList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/pathogentestlink/PathogenTestListEntry.java
=> Feature 12663 add tested pathogen name field

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/customizableenum/CustomizableEnumValueEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/customizableenum/CustomizableEnumValuesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java
=> #6340 - Update displayed diseases

sormas-app/app/src/main/res/layout/row_task_list_item_layout.xml, sormas-app/app/src/main/res/values/strings.xml
=> #12707 - Display environment task information

sormas-app/app/src/main/java/de/symeda/sormas/app/person/PersonContactDetailDialog.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonContactDetailEditForm.java
=> #12816 - Set initial visibilities and accesses

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-base/setup/sormas.properties
=> #12729 Detect duplicate persons by national health ID

sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventListComponent.java
=> #12802 - Fix event participant creation

sormas-app/app/src/main/java/de/symeda/sormas/app/component/dialog/SynchronizationDialog.java
=> #12856 - Fix sync dialog counts for environments

sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleService.java
=> #12853 - Restore environment samples

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/UserField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationEditForm.java, sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss
=> #12820 - Align contact information icon

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/event/EventParticipantDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java
=> #12794 - Link event to case with existent event participant

sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditPersonsInvolvedListFragment.java
=> #12848 - Fix access to event participant edit in app

sormas-api/src/main/java/de/symeda/sormas/api/user/DtoViewAndEditRights.java
=> #12836 - Fix pathogen test sync

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignFormDataEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaignstatistics/CampaignStatisticsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaignstatistics/CampaignStatisticsView.java
=> #12809 - Add support for HIDE_JURISDICTION feature to campaigns

sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantsLineListing/layout/LineListingLayout.java
=> #12901 - Hide jurisdiction fields for ep line listing

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/SampleDataView.java
=> #12854 - Properly display deleted samples

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/customizableenum/CustomizableEnumValueDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/customizableenum/CustomizableEnumValueDtoHelper.java
=> #12804 - Reset cache when pulling new values

sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/AbstractConfigurationView.java
=> #12914 - Fix config screen access

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java
=> #12917 - Do not update facility when Place of stay is HOME

sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationService.java
=> #12930 - Only disable config when enabled

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java
=> #12859 - Only display restore bulk action in delete grids

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/map/BaseDashboardMapComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/map/DashboardMapComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/sample/components/SampleDashboardMapComponent.java
=> #12852 - Show layers based on user rights

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java
=> #12869 - Force automatic lab message processing

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
=> #12662 - Don't show case creation prompt

sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleDataView.java
=> #12779 - Change environment sample redirection

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/PlaceOfStayEditForm.java
=> #11919 - Display correct information on hospitalization change

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
=> user facade update to fix double methods#12881

sormas-api/src/main/java/de/symeda/sormas/api/dashboard/DashboardCriteria.java
=> fix bug to pass test cases#12880

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/SampleController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/SampleEditPathogenTestListHandler.java
=> #12963 Incorrect saving message appears when saving a sample

sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposuresField.java
=> #12983 - Exposure data tab has error when edit/save

sormas-ui/src/main/java/de/symeda/sormas/ui/UiUtil.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/humansample/HumanSampleGridComponent.java
=> #12015 - Do not display bulk actions if the necessary rigths are missing

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
=> #11406 - Show only active entities in Person Info Cards

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/AbstractProcessingFlow.java, sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/ExternalMessageProcessingResult.java, sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/labmessage/AbstractLabMessageProcessingFlow.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/AutomaticLabMessageProcessor.java
=> #13037 Add debug logs for lab message processing

sormas-api/src/main/java/de/symeda/sormas/api/environment/EnvironmentIndexDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentGrid.java
=> #12280 - Introduce Reason for deletion in the Environments grid

sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentGridComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/RelevanceStatusFilter.java
=> #13074 - Fix the relevanceStatusFilter and the flickering on Environments Page

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
Fixes #13077 Error when creating cases with user role including Has optional health facility
=> #13077 - fixes error when creating a new case as hospital informant user with an associated facility

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java
=> #13120 - Error when trying to create a new environment sample

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #13121 - Error during Fresh Install of system at server update step

docs/I18N.md
Include contact email address and community link for requesting a new language to be added.
Fixes documentation (no issue number).
=> Update I18N.md with email and community link

sormas-app/pom.xml
=> #13132 - Building sormas with "with-app" profile fails

sormas-base/pom.xml
=> #13134 - jgitflow-maven-plugin disable pushReleases and pushHotfixes configuration

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/user/UserDto.java, sormas-api/src/main/resources/captions.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/user/KeycloakService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/User.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserGrid.java
=> #13080 keycloak username modification is not synced by sormas

sormas-api/src/main/java/de/symeda/sormas/api/CaseClassificationCalculationMode.java, sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseClassificationLogicTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java, sormas-base/setup/sormas.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #13150 automatic manual case classification customization per disease

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> RSV disease variants #13204

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java, sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java, sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/AbstractProcessingFlow.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #13203 Additional lab message fields

sormas-api/src/main/java/de/symeda/sormas/api/customizableenum/CustomizableEnumValueDto.java
=> Customizable enums creation form - save returns an error #13221

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonFilterForm.java
=> #13231 - Birthdate filter does not hold the selected values

sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java
=> bugfix 13239 error when accessing samples environment module

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> Bug #13205 unknown birthdate

sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyTokenCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyTokenDto.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyTokenIndexDto.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyToken.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyTokenFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyTokenIndexDtoResultTransformer.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyTokenService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/ControllerProvider.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/email/ExternalEmailSideComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/survey/SurveyListComponentLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/survey/SurveyTokenController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/survey/SurveyTokenDataForm.java
=> #13194 Add a "Survey" Card to the case view

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/facility/FacilityFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjbTest.java
=> #13206 use house number too for searching facility by address

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/caze/SurveyResponseStatus.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyReferenceDto.java, sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyTokenDto.java, sormas-api/src/main/resources/enum.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbCriteriaFilterTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/survey/SurveyFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/importer/SurveyTokenImporter.java
=> #13197 Add Survey filters to the cases view

sormas-api/src/main/java/de/symeda/sormas/api/environment/EnvironmentDto.java, sormas-api/src/main/java/de/symeda/sormas/api/environment/EnvironmentMedia.java, sormas-api/src/main/java/de/symeda/sormas/api/environment/VectorType.java, sormas-api/src/main/java/de/symeda/sormas/api/environment/environmentsample/EnvironmentSampleDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/enum.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/Environment.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSample.java, sormas-backend/src/main/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java
=> vectortypes added

sormas-api/src/main/java/de/symeda/sormas/api/Disease.java, sormas-api/src/main/java/de/symeda/sormas/api/disease/DiseaseConfigurationFacade.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/disease/DiseaseConfigurationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/disease/DiseaseConfigurationView.java
=> #13303 enable default contract tracing for measles disease

sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentController.java
=> removed duplicate code

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGridFilterForm.java
- Adapted the UI components:
- `ExternalMessageGrid`
- `ExternalMessageGridFilterForm`
Fixes #
=> #13293 - Adapt ExternalMessage and Message Directory UI

sormas-api/src/main/java/de/symeda/sormas/api/survey/SurveyTokenCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalemail/ExternalEmailFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyTokenService.java
=> 13325 survey token code not appearing in body of email

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> Altered the history tables

sormas-backend/src/main/java/de/symeda/sormas/backend/survey/SurveyTokenFacadeEjb.java
=> sorting issue fix in survey token page

sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/TherapyForm.java
=> Therapy form filter issue fix

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/gis/GisDashboardMapComponent.java
=> hide show events checkbox pending resolution

sormas-api/src/main/java/de/symeda/sormas/api/adverseeventsfollowingimmunization/AefiCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/dashboard/AefiDashboardCriteria.java, sormas-api/src/main/resources/enum.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/adverseeventsfollowingimmunization/AefiService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/adverseeventsfollowingimmunization/AefiDashboardService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/adverseeventsfollowingimmunization/components/AefiDashboardMapComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/gis/GisDashboardMapComponent.java
=> fixed issue with filter criteria updates from directory and maps

sormas-ui/src/main/java/de/symeda/sormas/ui/clinicalcourse/HealthConditionsForm.java
- `HealthConditionsForm` Unbound hidden fields on inaccessible check.
=> #13505 - Fixed binding error for health conditions form

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/TherapyForm.java
=> 13494 ipi antibiotic susceptibility test does not allow entry of test result but it is a mandatory field

sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/adverseeventsfollowingimmunization/AefiDashboardService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/adverseeventsfollowingimmunization/components/AefiTypeStatisticsGroupComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java, sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss
=> Bugfix #13518 aefi events displaying on map with backwards longitude latitude

sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseClassificationLogicTest.java, sormas-ui/src/test/resources/META-INF/persistence.xml
=> Task #13516 automated tests multiple tests are failing

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
=> Fixed the pathogen test failure for event

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> 13533 entry date is mandatory for old lux diseases

sormas-backend/src/main/java/de/symeda/sormas/backend/adverseeventsfollowingimmunization/AefiInvestigationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
`AefiInvestigationService`
- Added missing columns in AEFI
`EventFacadeEjb`
- Added missing columns in Events
=> Added missing columns in AEFI and Events

sormas-ui/src/main/java/de/symeda/sormas/ui/adverseeventsfollowingimmunization/aefilink/AefiListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationDataView.java
- Added check for null in `AefiListComponent`
- Disabled the creation of the AefiListComponent in `ImmunizationDataView` if the user does not have the right **ADVERSE_EVENTS_FOLLOWING_IMMUNIZATION_VIEW**
=> Fixed NPE in AEFI list component and guarded against no rights

sormas-api/src/main/java/de/symeda/sormas/api/hospitalization/HospitalizationDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/enum.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/hospitalization/Hospitalization.java, sormas-backend/src/main/java/de/symeda/sormas/backend/hospitalization/HospitalizationFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/DiagnosisCriteriaLabTestPanel.java, sormas-ui/src/main/java/de/symeda/sormas/ui/clinicalcourse/HealthConditionsForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/hospitalization/HospitalizationForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/pathogentestlink/PathogenTestListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/DrugSusceptibilityResultPanel.java, sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/TherapyForm.java
Fixes tb review result updates
=> tb review result updates
