sormas-api/src/main/java/de/symeda/sormas/api/disease/DiseaseBurdenDto.java
sormas-api/src/main/resources/captions_en_gh.properties
sormas-api/src/main/resources/descriptions_en_gh.properties
sormas-api/src/main/resources/enum_en_gh.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DiseaseBurdenGrid.java

Feature 1048 issues from the training

---

sormas-app/build.gradle
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DashboardFilterLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/EpiWeekAndDateFilterComponent.java

Dashboard add custom to time filters 1429

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
sormas-app/app/src/main/res/values/strings.xml
sormas-app/build.gradle

Allow app user change disease of case 1433

---

sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java

Inactive diseases should appear in dropdowns in edit mode

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_ar.properties
sormas-api/src/main/resources/captions_de-DE.properties
sormas-api/src/main/resources/captions_es-EC.properties
sormas-api/src/main/resources/captions_fa-AF.properties
sormas-api/src/main/resources/captions_fr-FR.properties
sormas-api/src/main/resources/captions_ps-AF.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java

export quarantine fields on cases and contacts + added quarantine information option on custom export

#1823 export quarantine fields on cases and contacts

---

sormas-app/app/src/main/java/de/symeda/sormas/app/util/LocationService.java
sormas-base/setup/sormas.properties

Locale underscore to hyphen change wasn't implemented in app. 
Was causing app to return null when getting current GPS/Network location.
#1919

#1919 Locale changed from underscore to hyphen

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGridComponent.java

web: show notification when sample is opened automatically

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/facility/FacilityFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilityEditForm.java

Also checked the code for community usage and didn't find any side effects
The system was prepared for facilities without community probably due to facility selection without community and due to the `other` and `home`  facility types

#1928 make community optional on health facility

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractView.java

Didn't find anything, it could be a Vaadin internal issue so I changed the method of getting the navigator on the line that failed. Hopefully this helps to avoid NPE.

#1745 use SormasUI.get().getNavigator() for navigation by criteria

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitJoins.java

refactored followup visit export pseudonymization to avoid extra queries for individual visits

#1158 refactored followup visit export pseudonymization

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/InfrastructureController.java

I pulled the check for empty bulk action to the beginning to fix this problem for all infrastructure types in `InfrastructureController`

Feature 2291 avoid empty bulk action

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AbstractContactView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactPersonView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactVisitsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/AbstractEventView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractDetailView.java

I half started new from the input @BarnaBartha delivered in his pull request.

Feature 2065 handle unappropiate parameters

---

DEVELOPMENT_ENVIRONMENT.md
SERVER_DEV_SETUP.md
sormas-base/dev-setup/.gitignore
sormas-base/dev-setup/server-setup-dev-docker.sh

Related to #2251 
executable without root access
- use ${HOME} as ${ROOT_PREFIX}
- install Payara in a custom path if needed (like server-setup.sh)
- configure Sormas domain in a custom path (like server-setup.sh)
- skip DB setup : use docker image
- run ant task

Add a dev server setup script

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_fr-FR.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldWrapper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/TextFieldWithMaxLengthWrapper.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/label.scss
sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss

Improve field « EVENT DESCRIPTION»

---

sormas-api/src/main/java/de/symeda/sormas/api/statistics/StatisticsHelper.java

Technically I fixed the defect (and also did some refactoring along), but I am not sure if all `UserRole` values (like `ReST User` or `Import User`) are supposed to be listed here.

Feature 2449 fix reportinguserrole grouping keys

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

Add the display of the UUID as requested in issue #2608

Added UUID to Person Edit Form which is read-only

---

.travis.yml
DEVELOPMENT_ENVIRONMENT.md
SERVER_DEV_SETUP.md
SERVER_SETUP.md
sormas-base/dev-setup/server-setup-dev-docker.sh
sormas-base/pom.xml
sormas-base/setup/server-setup.sh

- update docs to mention Java 11
- make build for plain openjdk 11 pass
- upgrade CI pipeline to openjdk 11
fixes #2612

Fix Java 11

---

sormas-rest/README.md

Title says it all :) 
fixes #2712

#2712 Improve docs for sormas-rest module

---

sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

Issue #2651 - Updates case symptoms when creating/editing a visit

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/visit/VisitEditForm.java

#2682 colorize followup visits based on state of the latest visit of the day

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFollowUpEndDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-rest/src/main/java/de/symeda/sormas/rest/ExternalVisitsResource.java

Yes, I know. A lot of code duplication. This is because we want to remove the getLatestQuarantineEndDates(...) soon. I will take care of this removal.

Feature 2732 add get follow up until dates method to external visit resource

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

Issue #2652 - Handle follow-up visits when merging a case

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-api/src/main/java/de/symeda/sormas/api/visit/VisitFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/visit/VisitFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java

Issue #2738 - Set case symptoms when converting contact to case

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-api/src/main/resources/captions.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/PersonDtoHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/Person.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

Add Person.externalId in domain model and show in PersonEditForm on German Systems #2670

Add externalId to Person and show it on PersonEditForm on German Systems

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/hospitalization/HospitalizationForm.java

Fix Bug 2929 error when opening case in read-only mode

---

sormas-api/src/main/java/de/symeda/sormas/api/action/ActionDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_fr-FR.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/action/Action.java
sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionListEntry.java

Add Action title

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_fr-FR.properties
sormas-api/src/test/java/de/symeda/sormas/api/caze/CaseCriteriaTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractView.java

#3021 Add a link in the event view to see cases related to this event

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataView.java

Feature 1999 import campaign form data

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/eventLink/EventListComponent.java

solved Linking a case to an event breaks when there is no event in the db issue #2684

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AbstractAdoDao.java

#2628 don't generate empty sormas 2 sormas share info when creating case/contact in the mobile app

#2628 don't generate empty sormas 2 sormas share info when creating case/contact in the mobile app

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/DateHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/IterableHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java
sormas-backend/src/test/java/de/symeda/sormas/backend/util/IterableHelperTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java

Batching, JTA Transactions and logging is implemented. Performance is documented in #2894.

Feature 2894 case archiving with batches

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/CSVUtils.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/CSVUtilsTest.java
sormas-base/pom.xml

#2990 Add custom CSVWriter implementation to sanitize formula pattern

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java

Repairs spacing for sample side box.

[IMIS] #3322 spacing sideboxes

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

[IMIS] #3239 Dont copy phonenumber to email field when converting contact to case

---

sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionEditForm.java

Handle null value in ActionEditForm.

[IMIS] Fixes #3348 null value in create Event Actions

---

sormas-backend/src/main/java/de/symeda/sormas/backend/user/KeycloakService.java

#2976 fix conflicting org.json.JSONObject dependencies

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

#3201 Automatically authenticate in CLIMEDO when opening the page for a registered patient

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_fr-FR.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java

Change the title of the event directory according to view type #3206

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-rest/src/main/java/de/symeda/sormas/rest/ExternalVisitsResource.java

#3182 remove redundant GET quanatineEndDate from ExternalVisitsResource

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java

#3451 set follow up status to null for generated persons

---

sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/ExternalJournalFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryConfig.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryContactInformation.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryPersonData.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryPersonDto.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryPersonQueryResponse.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryPersonValidation.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryPhone.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryRegisterResult.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-base/setup/sormas.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

#3188 email phone check

---

sormas-api/src/main/java/de/symeda/sormas/api/location/LocationDto.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

::checkIsEmptyLocation
... so it is not transferred as json property

#3510 Rename helper method LocationDto::isEmptyLocation to

---

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactIndexDetailedDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseGridDetailed.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java

#3101 split address into street, number, additional info in contacts view

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java

closes #3463 
I don't know what else I can document here

#3463 update validation javadoc

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java

... to
::checkIsUnreferredPortHealthCase so it is not transferred as json
property

#3533 Rename helper method CaseDataDto::isUnreferredPortHealthCase

---

sormas-e2e-ui-tests/.gitignore
sormas-e2e-ui-tests/Object Repository/ReusableORs/Filters/span_Include contacts from other jurisdictions.rs
sormas-e2e-ui-tests/Reports/smart_xpath/approved.json
sormas-e2e-ui-tests/Reports/smart_xpath/waiting-for-approval.json
sormas-e2e-ui-tests/Scripts/Contacts/NewContactViaContactsView/Script1586946842046.groovy

added new checkbox (include contacts from other jurisdictions)

Feature 3262 add custom browser versions

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java

#3174 consider excluded countries when generating import templates

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseGridDetailed.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java

#3101 move postal code column before other address columns

---

sormas-api/src/main/java/de/symeda/sormas/api/region/CountryDto.java
sormas-api/src/main/java/de/symeda/sormas/api/region/CountryFacade.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/InfrastructureFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/region/CountryFacadeEjbTest.java
sormas-rest/src/main/java/de/symeda/sormas/rest/CountryResource.java

#2993 add CountryResource

---

sormas-app/pom.xml
sormas-backend/pom.xml
sormas-base/pom.xml
sormas-rest/pom.xml
sormas-ui/pom.xml

Only refactoring, no scope or packaging changes

Feature 3449 unify version management

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java

#3305 - Disabled "View data" option in charts

---

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigns/CampaignDashboardElementsGridComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigns/CampaignFormsGridComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditableGrid.java

#3503 fixed problems in campaign edit grids

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/AbstractConfigurationView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/DiseaseStatisticsComponent.java

#3171 - Added feature configuration for outbreaks

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/AbstractConfigurationView.java

#3572 - Show facility and POE config views based on enabled features

---

sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDataProvider.java

#3622 - Fixed bugs when there are no active campaigns in the database

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-app/app/src/main/java/de/symeda/sormas/app/BaseActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/contact/edit/ContactEditActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/contact/read/ContactReadActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/event/read/EventReadActivity.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AbstractContactGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGrid.java

#3552 - Added feature configuration for tasks

---

sormas-ui/src/main/webapp/VAADIN/themes/sormas/print.scss

Show selected optionGroup input background for printing #3197

---

sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/AbstractConfigurationView.java

#3572 hide views based on features

---

sormas-e2e-ui-tests/Scripts/Contacts/NewContactViaContactsView/Script1586946842046.groovy
sormas-e2e-ui-tests/Scripts/Login/partials/LoginActions/Script1585642814653.groovy
sormas-e2e-ui-tests/settings/internal/com.kms.katalon.composer.testcase.properties

Contact filtering changed to apply other jurisdiction checkbox later in time when no rows are identified

#3690 Contact filtering changed to apply other jurisdiction checkbox

---

SERVER_CUSTOMIZATION.md
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/geocoding/GeocodingService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasRestClient.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/ClientHelper.java

Dupplicates #3550 
Fixes #3605

#3605 added proxy support for hotfix

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDtoHelper.java
sormas-backend/src/main/resources/sql/sormas_schema.sql

Fix 3408 first contact date db migration

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasShareInfo.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3725

#3725 make Case/Contact/Sample links LAZY in SormasToSormasShareInfo to avoid exceeding psql select columns limit

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/contacts/ContactsDashboardView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/SurveillanceDiseaseCarouselLayout.java

#3406 refresh map data after expand/minimize epi curve chart

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRole.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3608

#3608 fix pseudonomization issue on returning data from one sormas instance to another

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseIndexDetailedDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/utils/CaseJoins.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseGridDetailed.java

Add symptoms onset and sample latest collection date columns in case directory #3272

---

README.md
sormas-base/pom.xml
sormas-rest/pom.xml
sormas-rest/src/main/java/de/symeda/sormas/rest/RestConfig.java
sormas-rest/src/main/java/de/symeda/sormas/rest/external/ExternalRestResourceConfig.java
sormas-rest/src/main/java/de/symeda/sormas/rest/external/ExternalVisitsResource.java

#3372 provide external API info at runtime

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/person/ArmedForcesRelationType.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java
sormas-api/src/main/resources/enum.properties
sormas-api/src/main/resources/enum_de-DE.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/PersonDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/person/read/PersonReadFragment.java
sormas-app/app/src/main/res/layout/fragment_person_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_person_read_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/Person.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

#3418 was in development before, but due to some undesired reverse commit, most files have been removed again.

#3418 Added ArmedForcesRelationType to everything but databases

---

.github/workflows/ci.yml
.travis.yml

[#3730] github actions ci

---

.github/workflows/ci.yml
README.md

Follow up on https://github.com/hzi-braunschweig/SORMAS-Project/issues/3730#issuecomment-745165678
---
Also updates the status badge

Feature 3730 gh actions ci

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java

closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3779

#3779 fix to call handleJournalPerson earlier

---

.github/workflows/ci.yml

@MartinWahnschaffeSymeda Title says it all :D we need to go back to verify b/c mvn test does not really setup serverlibs suitable for sormas-cargoserver, so an error is thrown

[#3730] back to verify

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java

#3718 allow members of same family to have the same email in Climedo

---

sormas-backend/src/test/java/de/symeda/auditlog/api/AuditorTest.java

#3805: double the expected duration for Auditor inspect entity

---

sormas-e2e-ui-tests/Object Repository/Events/NewEventView/input_district.rs
sormas-e2e-ui-tests/Scripts/Events/CreateNewClusterEvent/Script1602235346380.groovy
sormas-e2e-ui-tests/Scripts/Events/CreateNewEvent/Script1587017521693.groovy
sormas-e2e-ui-tests/Scripts/Events/CreateNewScreeningEvent/Script1602235370468.groovy

- vaadin drop down selection issue on long forms

#3690 District selection for new event creation on ui tests

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#3514 add outcome date to detailed case export

---

sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/InfrastructureImporter.java
sormas-ui/src/test/java/de/symeda/sormas/ui/importer/InfrastructureImporterTest.java
sormas-ui/src/test/resources/sormas_district_bom_test.csv

#3747 use BOMInputStream in DataImporter

---

sormas-api/src/main/java/de/symeda/sormas/api/action/ActionFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventHelper.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventActionsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventSelectionGrid.java

Add a detailed export to the action view of the event directory #3563

---

sormas-app/app/build.gradle
sormas-app/app/src/main/java/de/symeda/sormas/app/login/LoginActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/util/ErrorReportingHelper.java
sormas-app/build.gradle

Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
fix
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3356

#3356 Migrate to the newest Firebase version

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_de-DE.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/Case.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/Contact.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/contact/edit/ContactEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureHelper.java
sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_case_read_layout.xml
sormas-app/app/src/main/res/layout/fragment_contact_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_contact_read_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/Contact.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactJoins.java
sormas-backend/src/main/java/de/symeda/sormas/utils/CaseJoins.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3410

3410 survnet reporting district field

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/region/CountryDto.java
sormas-api/src/main/java/de/symeda/sormas/api/region/CountryFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/region/CountryReferenceDto.java
sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java
sormas-api/src/main/resources/strings.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/region/CountryDtoHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/datapersister/ProcessedCaseDataPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/datapersister/ProcessedContactDataPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/dataprocessor/SharedCaseProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/dataprocessor/SharedDataProcessorHelper.java

Fixes: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3817

#3817 fix saving all changes of returned cases/contacts

---

sormas-backend/src/main/java/de/symeda/sormas/backend/action/Action.java
sormas-backend/src/main/resources/sql/sormas_schema.sql

Change action's columns description and reply type to text #3848

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java

#3870 fix symptom jounal status filter in contacts view

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportService.java

This PR fixes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3902

3902 condition is always true

---

SERVER_UPDATE.md
sormas-base/pom.xml
sormas-base/setup/keycloak/themes/sormas/login/resources/css/styles.css

3766 update to keycloak 12

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java
sormas-api/src/main/java/de/symeda/sormas/api/systemevents/SystemEventDto.java
sormas-api/src/main/java/de/symeda/sormas/api/systemevents/SystemEventFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/systemevents/SystemEventStatus.java
sormas-api/src/main/java/de/symeda/sormas/api/systemevents/SystemEventType.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/systemevent/SystemEvent.java
sormas-backend/src/main/java/de/symeda/sormas/backend/systemevent/SystemEventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/systemevent/SystemEventService.java
sormas-backend/src/main/resources/META-INF/persistence.xml
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/systemevent/SystemEventFacadeEjbTest.java
sormas-backend/src/test/resources/META-INF/persistence.xml
sormas-base/setup/sormas.properties
sormas-ui/src/test/resources/META-INF/persistence.xml

Feature 3927 add system events entity 2

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java

#3821: user AbstractAdoService for building the contact and event filters for getting all persons to prevent NPE

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasOriginInfoFacade.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/survnet/SurvnetGateway.java

+ added CaseController method that checks whether any case is non-Covid-19 or not owned by the server

#3517 - Added bulk edit button

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java

Display person's birthdate in case/contact/eventParticipant view title #3827

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/epidata/ExposureDialog.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposureForm.java

#3680 - Link facility fields to type of place in exposures

---

sormas-base/setup/server-update.sh

#3996 - Create documents directory on server update

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java

Bugfix for #4091 , tested locally

#4091 Disallow sorting of last column of labmessages 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposureForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposuresField.java

#4055 fix exception when adding exposures as Case Officer

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java

Add a link to events within the same facility in the event data view #3887

---

sormas-app/app/src/main/res/layout/fragment_event_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_event_read_layout.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java

Open event's risk level to all event statuses #4047

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/EntrySelectionField.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

#4058: Add contact creation

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java

Allow regional users to assign tasks to national ones #4048

---

sormas-api/src/main/java/de/symeda/sormas/api/campaign/diagram/CampaignDiagramSeries.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java

Extended the campaign diagram definition to also have an optional name for each series. 
see https://github.com/hzi-braunschweig/SORMAS-Project/issues/3163

#3163 allow custom series caption

---

sormas-rest/pom.xml
sormas-rest/src/main/java/de/symeda/sormas/rest/security/MultiAuthenticationMechanism.java

#3293 Adjust OpenAPIDefinition namings and updated swagger to consider the security package

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseStatisticsFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/PopulationDataFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/QueryHelper.java
sormas-backend/src/test/java/de/symeda/sormas/backend/util/QueryHelperTest.java

Asking for code review, but let me merge it after hotfix 1.54.1 is done.

Feature 4075 move append in filter values

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java

#4210 add parameter to redirection URL

---

sormas-api/src/main/java/de/symeda/sormas/api/exposure/GatheringType.java
sormas-api/src/main/resources/enum.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java

Add the following variables to "type of gathering":
  - demonstration
  - carnival
  - fair
  - sporting event
Closes #4039

#4039 [SurvNet Interface] New exposure gathering types

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#4189 Fixed ownership check to only include selected cases

---

sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/TemplateEngine.java
sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/XDocTemplateEngine.java

restrict velocity engine features (#4231)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java

#3349: read value of the "diagramType" column in the database to decide which diagramtype to display

#3349: read value of the "diagramType" column in the database

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-base/setup/sormas.properties

Feature/4129 Server property for default user creation

---

sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java

#3661 add unique constraint to documents uuid

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java

#4285 show source of vaccination information dropdown in android app

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/Case.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_case_read_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3414

#3414 SurvNet Adaptations - Create new field “Blood donation in the last 6 months” for cases

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/ReportingType.java
sormas-api/src/main/resources/enum.properties

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3417
**Changing the label should be done via Crowdin**

#3417 Add new community facility value for Germany to ReportingType

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java

#4301 Add typing-ID to sample create form 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java

see https://github.com/hzi-braunschweig/SORMAS-Project/issues/3995

#3995 calculate y axis max value

---

sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java

Generate CSV Import templates in UTF-8 (#4322)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java

#4325 Add additional IN clause to contact count queries in event directory

---

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/ExternalLabResultsFacade.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

closes #4291 .
Related Adapter Merge Request: https://git.vitasystems.dev/sormas/sormas-demis-adapter/-/merge_requests/9

#4291 Resized labMessage window and added adapter specification comment

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

Change 4306 handle external journal only if active

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGrid.java

fix samples bulk edit mode for Admin Surveillance Supervisor (#4087)

---

sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java

#4365: Expose get duplicates with reportDateThreshold

---

sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java

Reverts hzi-braunschweig/SORMAS-Project#4367

Revert "#4365: Expose get duplicates with reportDateThreshold"

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/component/validation/ValidationHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/NumberValidator.java

#4276 Add date and dose validators for vaccinations

---

README.md

JAVA CI with Maven is linked to Actions now

Fixed Issue: #4372

---

sormas-api/src/main/java/de/symeda/sormas/api/exposure/ExposureDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormDataFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseVariantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/exposure/Exposure.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ExportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/DtoHelper.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-backend/src/test/java/de/symeda/sormas/backend/util/DtoHelperTest.java

#4338 - Fixed locations not being cloned on case merge

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

#4221: FollowUpEndDate API does not deliver the expected results

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4407

#4407 avoid external person validation when PIA is used

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/DateHelper.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4282

#4282 Fixed NullPointerException during date formatting

---

sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/I18nFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/I18nProperties.java
sormas-app/app/src/main/java/de/symeda/sormas/app/settings/SettingsActivity.java
sormas-backend/src/main/java/de/symeda/sormas/backend/i18n/I18nFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/SessionFilter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/login/LoginHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserController.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4403

#4403 Fixed mixed translations in ui/backend, export and mobile app

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/surveillancereport/SurveillanceReportFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportService.java
sormas-rest/src/main/java/de/symeda/sormas/rest/SurveillanceReportResource.java

#4426: Added SurveillanceReportResource with needed methods

---

sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java

[#4438] use correct sanitizer in HTML context

---

sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/DocumentTemplateFacadeEjb.java

resolve CaseReferenceDto and ContactReferenceDto (#4455)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/survnet/SurvnetGateway.java

Not sure what happened with the formater, I have the correct one installed :(
closes #4401

[#4401] remove unecessary notification

---

I18N.md

Update i18n README

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#4248: updating date on the Person view when changing date of death

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

closes #4236 
Should be merged after the release.

#4236 remove redundant code

---

sormas-ui/src/main/java/de/symeda/sormas/ui/visit/VisitEditForm.java

#3849 Use tel: link for phonenumbers

---

sormas-backend/pom.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/survnet/SurvnetGatewayFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/survnet/SurvnetGatewayFacadeEjbTest.java
sormas-base/pom.xml

#4269 survnetgatewayejb unit tests

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#4533: Map Sex.UNKOWN to all others in duplicate detection

---

sormas-backend/utils/importUsersExample.sql

#4513: add import user example script

---

sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java

#4444: Only show limited disease under circumstances

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java

#4346: Listing samples for a lab officer can be slow

---

sormas-app/app/src/main/res/layout/fragment_event_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_event_read_layout.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java

Allow Institutional Partners event source type to have contact information

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java

fixed #4545

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java

#4332: Copy followup comment when converting contact to case

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantIndexDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/jurisdiction/EventParticipantJurisdictionHelper.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipant.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/PathogenTestResultTypeRenderer.java

#3853: Show latest test result for event participants

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/CsvStreamUtils.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-base/setup/sormas.properties

#4316 - Identify performance problems in detailed export.

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/contact/edit/ContactEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/contact/read/ContactReadFragment.java

#4328 - Removed visibility restrictions from external token field

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/ContactResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/EventParticipantResource.java

#4625: retrieve contacts by person uuids trough API

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/importexport/ExportPropertyMetaInfo.java
sormas-api/src/main/java/de/symeda/sormas/api/importexport/ImportExportUtils.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/CustomExportController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/ExportConfigurationEditLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/ExportConfigurationsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/ExportConfigurationsLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4647

#4647 Fix broken custom export checkbox captions

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/eventimport/EventImportEntities.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/eventimport/EventImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java

restrict import columns (#4041)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java

fix nullpointer in case directory for POE supervisor (#4644)

---

sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleDto.java

#4560: remove Required annotation for SampleDto.lab

---

sormas-api/src/main/java/de/symeda/sormas/api/exposure/GatheringType.java
sormas-api/src/main/resources/enum.properties
sormas-api/src/main/resources/enum_de-CH.properties
sormas-api/src/main/resources/enum_de-DE.properties

add GatheringType.CONCERT (#4474)

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java

#4649 - Added feature configuration for person management

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

[#4507] tweak task reassignment on case change

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

Feature 4381 make lab message and creation forms independently scrollable

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventUserFilterCriteria.java

#4748 - Adjusted user filters to transfer all accessible events

---

.github/workflows/linter.yml
sormas-backend/doc/UserDataAccess.md
sormas-backend/src/main/resources/shapefiles/README.md
sormas-base/doc/SormasSyncProcess.md
sormas-base/doc/keycloak.md
sormas-base/doc/sormas-to-sormas.md
sormas-cargoserver/README.md
sormas-e2e-ui-tests/Performance Tests/Performance.md
sormas-e2e-ui-tests/README-TESTS.md
sormas-e2e-ui-tests/README.md
sormas-keycloak-service-provider/README.md
sormas-rest/README.md

Fixes #4635 by updating markdown files.

[#4635] Complete markdown linting of repo

---

sormas-backend/src/main/resources/sql/sormas_schema.sql

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4555

#4555 added sampling reason on samples - create sample if needed during DB migration

---

sormas-api/src/main/java/de/symeda/sormas/api/facility/FacilityType.java
sormas-api/src/main/resources/enum.properties

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4066

#4066 [SurvNet Interface] Add variables to facility type

---

sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java

Allow task notifications to be sent to all users #4598

---

sormas-api/src/main/java/de/symeda/sormas/api/disease/DiseaseConfigurationFacade.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/util/DiseaseConfigurationCache.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseConfiguration.java
sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseConfigurationFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

[#4218] add properties and make sure they are not null

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadFragment.java
sormas-app/app/src/main/res/layout/fragment_case_edit_hospitalization_layout.xml
sormas-app/app/src/main/res/layout/fragment_case_read_hospitalization_layout.xml

Closes #4701 and replaces #4789

#4701 Fix App hospitalization fields

---

sormas-api/src/test/java/de/symeda/sormas/api/utils/CharsetHelperTest.java

#4050 Fix FileReader compilation issue for java versions earlier than 11

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/JurisdictionHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java

#4582 Allow users to assign tasks to users of the next higher jurisdictionlevel

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java

#4634 - Added task context validation

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java

fix batch iterator usage (#4580)

---

.gitignore

[#4469] gitignore gradle in sormas-e2e-ui

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_de-DE.properties

Add country to i18n translations #4664

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java

#4795 Use null safe method for getting user language at import

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseLogic.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

[#4480] clear facilityType(Group) when switching from facility to home

---

sormas-cargoserver/README.md
sormas-cargoserver/build_deploy.sh

closes #4814 
Credits to @DavidBaldsiefen for the initial idea and code :)

[#4814] QOL script to build and deploy to cargo

---

sormas-api/src/main/resources/strings.properties
sormas-api/src/main/resources/strings_de-DE.properties

#4478 Change error message to better reflect reality 

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

Feature 4830 inform climedo of changes when cases and contacts get deleted

---

sormas-api/src/main/java/de/symeda/sormas/api/task/TaskIndexDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java

#4488 Allow community officers to see all tasks in their community

---

sormas-api/src/main/java/de/symeda/sormas/api/share/ExternalShareInfoDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/Pseudonymizer.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalsurveillanceservice/ExternalShareInfoList.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4771

#4771 fix survnet transfer history pseudonymized display and languge issue

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

#4360 Hide external id if SurvNet is enabled

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java

#4241 Calculate case followup-date based on symptomonset-date

---

sormas-api/src/main/java/de/symeda/sormas/api/CountryHelper.java
sormas-api/src/main/java/de/symeda/sormas/api/activityascase/ActivityAsCaseDto.java
sormas-api/src/main/java/de/symeda/sormas/api/activityascase/ActivityAsCaseType.java
sormas-api/src/main/java/de/symeda/sormas/api/event/TypeOfPlace.java
sormas-api/src/main/java/de/symeda/sormas/api/exposure/ExposureDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/fieldvisibility/FieldVisibilityCheckers.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/fieldvisibility/checkers/CountryFieldVisibilityChecker.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_de-DE.properties
sormas-api/src/main/resources/enum.properties
sormas-api/src/main/resources/enum_de-DE.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/component/dialog/FormDialog.java
sormas-app/app/src/main/java/de/symeda/sormas/app/epidata/ActivityAsCaseDialog.java
sormas-app/app/src/main/java/de/symeda/sormas/app/epidata/EpidemiologicalDataReadFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/epidata/ExposureDialog.java
sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditFragment.java
sormas-ui/src/main/java/de/symeda/sormas/ui/ActivityAsCase/ActivityAsCaseForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFacilityChangeForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/EpiDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldHelper.java

Change 4761 activity as case ifsg

---

sormas-api/src/main/java/de/symeda/sormas/api/EntityDtoAccessHelper.java
sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/patientdiary/PatientDiaryValidationError.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java

Feature 2744 climedo logic adaptations

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventIndexDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGrid.java

#4408 Add external id and external token columns to events directory

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleJurisdictionChecker.java

#4346: Workaround/Bugfix: Editing Samples not working

---

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasOptionsForm.java

#4107: Exclude pseudonymize options when ownership is handed over sormas2sormas and vice-versa

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java

#4880 sorting cases by reinfection no longer results in error

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java

Closes #4533 
The code @ChristopherRiedel added in https://github.com/hzi-braunschweig/SORMAS-Project/pull/4548 was put into the wrong function.

[#4533] unknown sex should map to all other sexes in duplicate detection

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java

#4479 - Extended parsing and added validation

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

Feature 3545 refactoring batching

---

sormas-api/src/main/java/de/symeda/sormas/api/person/SimilarPersonDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/importer/CaseImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventparticipantimporter/EventParticipantImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/importer/EventImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/CaseImportSimilarityResult.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/ContactImportSimilarityResult.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/PersonImportSimilarityResult.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java
sormas-ui/src/test/java/de/symeda/sormas/ui/caze/importer/CaseImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/contact/importer/ContactImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/eventparticipantimporter/EventParticipantImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/importer/EventImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/importexport/ImportExportTest.java

Change 4003 extend duplicate person popup

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantDto.java

rename isOwnershipHandedOver to ownershipHandedOver (#4899)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java

allow empty ct/cq value (#4896)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractFilterForm.java

hide IfSG values in TypeOfPlace filter in events directory (#4909)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/region/ContinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/RegionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/SubcontinentFacadeEjb.java

fixes #4908
For the reviewer: Please have a second thought on wether it is okay to remove "distinct" from the queries in `CountryFacadeEjb`, l.108, and `RegionFacadeEjb`, l.159.

fix infrastructure sort columns (#4908)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

fix collision of primary contact details (#4926)

---

SERVER_CUSTOMIZATION.md
sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java

Closes #3731 
This may be relevant for releasenotes, as european users might want to re-enable this feature (default setting is disabled)

#3731 GDPR featureconfiguration

---

sormas-api/src/main/java/de/symeda/sormas/api/action/ActionDto.java
sormas-api/src/main/java/de/symeda/sormas/api/action/ActionReferenceDto.java
sormas-api/src/main/java/de/symeda/sormas/api/document/DocumentRelatedEntityType.java
sormas-api/src/main/resources/enum.properties
sormas-base/pom.xml
sormas-ui/pom.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionListEntry.java
sormas-ui/src/main/java/de/symeda/sormas/ui/document/DocumentListComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DocumentMultiFileUpload.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DocumentUploadFinishedHandler.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DocumentUploadReceiver.java
sormas-widgetset/pom.xml
sormas-widgetset/src/main/resources/de/symeda/sormas/SormasWidgetset.gwt.xml

Be able to attach multiple files on Events and Actions

---

README.md

Include notice that users subject to GDPR should not make use of the Android app until further notice - cleared by GK and Datenschutz team 24.03.2021.  Please let me know if this would be better suited elsewhere?  The text could be used verbatim if a more suitable place is found.

Update README.md with GDPR info

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java

#4941 Fixed email validation inconsistency

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java

fix case sorting by primary phone (#4927)

---

SERVER_CUSTOMIZATION.md
sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/messaging/MessageSubject.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/messaging/MessagingService.java

Add a FeatureType for enabling or disabling sending a notification when a case is confirmed

---

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageIndexDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java

#4841 Added columns to lab sample directory: lab name, lab postal code, person postal code

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java

#4917 Set correct column caption for event participant lists

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/Person.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

#5012 - Fix removing person contact details not being possible

---

sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_case_read_layout.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

Change 3776 case layout

---

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

#4985: Disable externalId of person if externalSurveillanceTool is enabled

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureConfigurationFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/AbstractConfigurationView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CommunitiesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/DistrictsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilitiesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/PointsOfEntryView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/RegionsView.java

hide country filter when no surveillance is enabled (#5019)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/TemplateEngine.java
sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss

minor code quality issues (#5051)

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/login/DefaultPasswordUIHelper.java

closes #5081 
As described in #5081 (and mentioned in #5080) it would be useful to disable the default password check in certain conditions (like public demo servers).

#5081 add configuration option to skip default password check

---

sormas-base/setup/sormas.properties

Follow-Up to #5081 (PR: #5082)

Add info on skipDefaultPasswordCheck to sormas.properties #5081

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseContactsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AbstractContactGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java

Cloese https://github.com/hzi-braunschweig/SORMAS-Project/issues/5040

#5040 fixed case contacts refresh after import

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseGrid.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3947

#3947 add caption for reporting tool status column + make reporting tool columns unsortable

---

sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/ExternalJournalFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java

#4941 If no primary contact details, try to get a singular non-primary email and phone number

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/VaadinUiUtil.java

#4111 - Don't automatically load duplicates in merge duplicate view

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/messaging/MessagingService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/messaging/SmsService.java

#5091 - Don't try to send SMS when service is not configured

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

#5095 Correctly enforce place of stay validation

---

sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java

#4936: Update ESPG:4326 WKT with Axis definition to ensure their order

---

sormas-api/src/main/java/de/symeda/sormas/api/importexport/ImportExportUtils.java
sormas-api/src/main/java/de/symeda/sormas/api/importexport/ImportFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/importer/CaseImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/importer/LineListingImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/InfrastructureImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/PopulationDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/CaseContactsImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactsImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventparticipantimporter/EventParticipantImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/importer/EventImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DownloadUtil.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExportEntityName.java

Bugfix 5018 use custom system name in filenames

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/RegionsGrid.java

show country column in RegionsGrid only when needed (#5019)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

no geobutton highlighting with all location fields empty (#5051)

---

sormas-api/src/main/java/de/symeda/sormas/api/symptoms/SymptomsDto.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/5092

#5092 fix export of Coma/Somnolence symptom

---

sormas-api/src/main/java/de/symeda/sormas/api/importexport/DatabaseTable.java
sormas-api/src/main/resources/enum.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/DatabaseExportService.java

#5009: Add Person contact details export option to Database Export

---

sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java

fix default import for (sub)continents and countries(#5143)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

#4976 Added missing pathogen test mappings

---

.github/workflows/ci.yml

Feature 3383 fix actions

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-api/src/main/resources/captions.properties
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/PersonDtoHelper.java
sormas-app/app/src/main/res/layout/fragment_person_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_person_read_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/person/Person.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/messaging/SmsComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGroupDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ResizableTextAreaWrapper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/TextFieldWithMaxLengthWrapper.java

#3936: Add a general comment field to person

---

.github/workflows/ci.yml

[#3383] make sure have the latests branch

---

.github/workflows/ci.yml

[#3383] use upstream as origin already exists

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java

#5062 Add symptomjournalstatus to CaseService.createCriteriaFilter 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java

#4260 Check for userjurisdiction before enabling casecreation for eventparticipants

---

.github/workflows/ci.yml

[#3383] set token at checkout time

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/importexport/ImportColumn.java
sormas-api/src/main/resources/strings.properties

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/5132

#5132 superordinate event column missleading in import template

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

Fixes #5099 
See Issue Comment for a more detailed description of the fix

#5099 prevent case bulkactions from entering infinite loop

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasOriginInfo.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasOriginInfoService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4975

#4975 Don't allow editing persons shared without ownership

---

sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureDaoHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

ignore (sub)continent value changes if fields are invisible (#4981)

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

#5188 Add indicator on locationform regarding facilities and districts

---

.github/workflows/openapi_canary.yml

[3383] fix copenapi canary

---

sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/ExternalJournalFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java

Bug 5155 converting a contact to a case does not update the follow up duration in climedo

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposuresField.java

#4589 extend exposure table

---

sormas-cargoserver/build_deploy.sh

#5245 Add clean option to build_deploy.sh

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FilteredGrid.java

#5017 Add caption to editcolumn and move column to the left

---

sormas-e2e-ui-tests/Object Repository/Contacts/ContactInformationView/ChangeContactPersonData/div_edit.rs

#5235 - change in role attributes for custom component

---

sormas-api/pom.xml
sormas-api/src/main/java/de/symeda/sormas/api/campaign/ExpressionProcessorUtils.java
sormas-app/app/build.gradle
sormas-app/app/proguard-rules.pro
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/campaign/Campaign.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/campaign/CampaignDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/campaign/form/CampaignFormMeta.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/campaign/form/CampaignFormMetaDao.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AbstractAdoDao.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/CampaignFormDataFragmentUtils.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/edit/CampaignFormDataEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/edit/CampaignFormDataNewFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/edit/CampaignFormMetaDialog.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/list/CampaignFormDataListActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/read/CampaignFormDataReadFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java
sormas-app/app/src/main/java/de/symeda/sormas/app/util/MetaProperty.java
sormas-base/pom.xml
sormas-ui/pom.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/expressions/ExpressionProcessor.java

Feature 3905 campaign form data expressions mobile

---

sormas-app/app/src/main/java/de/symeda/sormas/app/BaseActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/component/validation/ValidationHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/visit/edit/VisitEditActivity.java
sormas-app/app/src/main/java/de/symeda/sormas/app/visit/read/VisitReadFragment.java

#5238 allow correct editing of contact followup information in android

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/EventResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/SampleResource.java

#5032 [Angular][Backend] Event and Sample Pagination #5200 and #5201

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseLogic.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactLogic.java

Fixes #5212
This is a quick fix in case a hotfix 1.59.1 is issued.

allow extension of followUpUntil beyond last visit (#5212)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

#5130 Do not disable first and last name when processing a lab message

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListComponent.java

#5277 include cases from other jurisdictions

---

sormas-api/src/main/java/de/symeda/sormas/api/importexport/DatabaseTable.java
sormas-api/src/main/resources/enum.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroup.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/DatabaseExportService.java

#5191: Added Event Groups as option for Database Exports

---

sormas-app/app/src/main/res/layout/row_event_list_item_layout.xml

#5286 Replace event description by title in event list in android app

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

Fixes #5190.
It might be useful to just look at the second commit.

Bug 5190 prompt to update case disease variant is not shown when processing lab messages

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseIdentificationSource.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java
sormas-api/src/main/resources/enum.properties

#5063 add enum values

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java

#5267 Closes pathogentest edit popup on discard

---

sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/CampaignFormDataFragmentUtils.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/edit/CampaignFormDataEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/edit/CampaignFormDataNewFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/campaign/read/CampaignFormDataReadFragment.java

#5309 - use campaign form meta translations in mobile application

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/vaccinationinfo/edit/VaccinationInfoEditFragment.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationInfoForm.java

Bug 5131 detailed import accepts empty space at vaccination doses

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java

Fixes #5283
Edit: Also prevents multiday-events from throwing warnings when the end date is in the future

#5283 Prevent illegal multiday contact dates from being saved

---

sormas-app/app/src/main/java/de/symeda/sormas/app/core/TaskNotificationService.java

#5317 - task notifications to consider feature config

---

sormas-rest/pom.xml
sormas-rest/src/main/java/de/symeda/sormas/rest/RestConfig.java
sormas-rest/src/main/resources/workflow-documentation.properties

#4799 add workflow description to API documentation

---

sormas-backend/src/main/resources/sql/sormas_schema.sql

#5061 - change json types to jsonb to avoid equality issue

---

sormas-e2e-ui-tests/Object Repository/Surveillance/NewCaseView/div_Sex_DDBox.rs
sormas-e2e-ui-tests/Scripts/Contacts/CreateCancelNewCall/Script1586946842043.groovy

#5235 - Modified Identifier for Sex field

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java

#5344 Add UUID to text search filters for samples

---

sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventNewActivity.java

#5262 Prevent NPE when adding case events without a disease in android

---

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

#5361 Add phone and email validators to person contact person

---

.github/ISSUE_TEMPLATE/task.md
docs/CONTRIBUTING.md

#5337: issue template for "task", added documentation

---

sormas-api/src/main/java/de/symeda/sormas/api/DiseaseHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

#4437 Show the variant in brackets as stated in the issue description

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java

#5353 - External Token is validating data from deleted records

---

sormas-app/app/src/main/java/de/symeda/sormas/app/component/dialog/LocationDialog.java
sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

#5374 Set facility-contactperson visiblity-dependency

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadFragment.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/test/java/de/symeda/sormas/ui/importexport/ImportExportTest.java

#5377 correctly handle pregnancy fields on gender change

---

sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/Campaign.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormData.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/diagram/CampaignDiagramDefinition.java
sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumValue.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/Event.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java

Refactors #5061 
Reduces duplication of String literals in the code (Sonar issue), makes search for usage easier and explains what this config is about in the Javadoc. No changes to effective compiled code.

#5061: Refactor: Define json values as Constants, added Javadoc

---

sormas-e2e-tests/README.md
sormas-e2e-tests/build.gradle

-->
Fixes #5439
Notes I couldn't add the ticket to the QA Project

 #5439/ Reworked windows commands

---

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactIndexDetailedDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java

#4807 Add RelationToCase filter and column to detailed contact grid

---

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactSimilarityCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantCriteria.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventparticipantimporter/EventParticipantImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/eventparticipantimporter/EventParticipantImporterTest.java

#5445 - Event Participants Filters not displayed anymore

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java

#5462: Exclude deleted cases from search by externalId

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java

#5233 Fix npe; save person in a separate transaction

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

use caseFollowUpDuration for cases (#3243)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java

#5466 correctly handle test results on sample creation

---

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactReferenceDto.java

add JsonIgnore to ContactReferenceDto.getCaptionAlwaysWithUuid (#5469)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesFilterComponent.java

#5278 split duplicate merge filters into three rows 

---

sormas-backend/src/main/resources/sql/sormas_schema.sql

#5465 - Indexing by `deleted` flag on all containing entities

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/Contact.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/contacts/EditContactSteps.java

Added ContactId for Contacts pojo in order to provide history search for Contacts

#5509/ Added ContactId for Contacts

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/common/StartupShutdownServiceTest.java

Feature 5541 fix postgres version check

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/CreateNewSamplePage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/SampleManagementPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/Sample.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/CaseService.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SampleService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/SampleManagementSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature

#5402 Create and Edit new sample 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java

#5554 add missing I18n lookups

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java

Fix follow up calculation for contacts (#5548)

---

sormas-api/src/main/java/de/symeda/sormas/api/document/DocumentDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/document/DocumentFacadeEjbTest.java

Fixes #5574
@StefanKock Please consider if it really is intended to allow uploads of any file type. If so, this PR fixes the related issue.

Allow upload of files with unknown mime type (#5574)

---

sormas-rest/src/main/java/de/symeda/sormas/rest/externaljournal/ExternalVisitsResource.java
sormas-rest/src/main/resources/workflow-documentation.properties

Fixes nothing, just extends documentation.

#4799 extend documentation

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java

Bugfix 5531 update case classification and sample information

---

sormas-api/src/main/java/de/symeda/sormas/api/region/CountryReferenceDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/ContinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/ContinentService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/SubcontinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/SubcontinentService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SharedDataProcessorHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/SharedEventProcessor.java

#4946 Share continent/subcontinent/country fields via s2s

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/CreateNewEventPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/Event.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/EventService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature

**Description**
- new event creation and validation (event services, pojo, builder) 
- validating a new event creation
- event status change and filter multiple times

#5401 event automation flow

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FilteredGrid.java

Feature 5612 increase lazy loading chunk

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/CaseService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature

Description:
1. Created locators for CaseDirectory and EditCase pages,
2. Corrected string in CaseService builder
3. Created new steps 
4. Created the test
Alure:
Review performed in closed PR:
https://github.com/hzi-braunschweig/SORMAS-Project/pull/5570

#5569 delete case

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventListComponent.java

add FeatureConfiguration for event hierarchies (#4527)

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/YesNoUnknownOptions.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/SymptomsTabPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Symptoms.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SymptomService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/EditCase.feature

#5617 create an automation test where the tab symptoms from case is covered

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Event.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/EventService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature

#5407 edit event automation flow

---

sormas-base/pom.xml

5316 - Update Vaadin version to 8.13.0

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-backend/src/main/resources/sql/sormas_schema.sql

#5662 - fix erroneous case changedate update

---

sormas-api/src/main/java/de/symeda/sormas/api/visit/VisitIndexDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/visit/VisitGrid.java

#3621 Display username in visit origin

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/common/CommonModule.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/comparators/PersonComparator.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/tasks/TaskManagementPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/api/Task.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Task.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/ContactApiService.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/TaskApiService.java
sormas-e2e-tests/src/main/resources/enum.properties
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/RestAssuredClient.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/state/ApiState.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/TasksSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/ColumnHeaders.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature

#5665 create an automation test where the data from the task is checked in the task management table

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java

4836_list_in_data_dictionary

---

sormas-api/src/main/java/de/symeda/sormas/api/importexport/DatabaseTable.java
sormas-api/src/main/resources/enum.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/DatabaseExportService.java

4624_database_export_actions

---

sormas-e2e-performance-tests/README.md

#5605 - Add performance testing readme file

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-base/setup/sormas.properties

#3704 Person duplication recognition does not trigger for persons with archived entities

---

sormas-e2e-performance-tests/README.md

#5613performance-updates-merges - added lost line during merge

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/HospitalizationTabPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/PreviousHospitalizationPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/api/Case.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Hospitalization.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/PreviousHospitalization.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/HospitalizationService.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/PreviousHospitalizationService.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/CaseApiService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/HospitalizationTabSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/PreviousHospitalizationSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/CaseHospitalization.feature

Added case hospitalization tab tests:
1. Changed API state for making hospitalization tab available;
2. Added Page Objects, methods and steps for checking hospitalization tab and previous hospitalization window.
3. Checked directly hospitalization window instead of tab table due to less data constraints in the table tab.
Please review!
Screenshot:

#5651/ Added case hospitalization tab tests

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-base/setup/sormas.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/map/DashboardMapComponent.java

#5666 Add map.usecountrycenter property

---

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserFacadeEjbTest.java

increase test coverage in preparation of refactoring in #5614

increase test coverage (#5614)

---

sormas-rest/src/main/java/de/symeda/sormas/rest/security/MultiAuthenticationMechanism.java

Ticks one box in #5599.
Just to reduce my diff in my concept PRs for S2S.

[#5599] reformat MultiAuthenticationMechanism

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserReference.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
sormas-backend/src/main/resources/META-INF/persistence.xml
sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskServiceTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserServiceTest.java
sormas-backend/src/test/resources/META-INF/persistence.xml
sormas-ui/src/test/resources/META-INF/persistence.xml

Feature 5614 refactor user service and usages

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventIndexDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java

Fixes #5742
`explain analyze`  sql command results:
* **Original query:**
Planning time: 0.431 ms
Execution time: 51.741 ms
* **Updated query:**
Planning time: 0.366 ms
Execution time: 0.716 ms

#5742 improve external shares count query

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageFacade.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessagesView.java

#5067 Select date from wich to fetch lab messages

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonSimilarityCriteria.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/strings.properties
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CriteriaBuilderHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/main/resources/META-INF/persistence.xml
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/ApplyResetButtonsComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/FormActionButtonsComponent.java

5078 person duplicate search

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

Feature 5543 calculate completeness avoid long wait time

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/sharedinfo/SharedInfoField.java

#1521 - Set required validation before togling it

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java

#5722 Documents of the discarded case / contact get lost while merging

---

sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java

4607_invalid_table_name_excel

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactServiceTest.java

#5789: Bugfix: limit result size

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageForm.java

5793_wrap_long_values

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

#1521 - Fixed contact saving

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#5324 Add a checkbox to avoid sending this case to SurvNet - move checkbox into responsible jurisdiction section

---

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasEntityInterface.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/SormasToSormasResource.java

#5671 fix sormas 2 sormas accept/reject after refactoring

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java

#5723 Comment fields are not merged

---

sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposuresField.java

fixed #5815

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#5721 Make sure merged cases only have one probable infection environment

---

sormas-app/app/src/main/res/layout/fragment_case_new_layout.xml

#5556 - Removed the place of stay caption for community field

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java

#5669 Fix country name encoding issue in sormas.properties

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature

Added test case for the contact source case changes.
[No print screen now due to allure library not working on macbook with M1 processors]

#5667/contact source case selected tests

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java

Merged to early the previous PR. I was addressing some of the review comments which requested adding some documentation to explain the usage of some hardcoded stuff in the solution. 
Please review!

#5667/ Added documentation changes

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/CreateNewActionSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature

remove commented line. 
Fixes #5675

remove commented line

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/NullableOptionGroupConverter.java

#5547 Set correct new value upon initial valuechange on nullableOptionGroup

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/AvailableAndCooperative.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/SourceOfTemperature.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/FollowUpTabPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Visit.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/FollowUpVisitService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/FollowUpStep.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFallowUpVisit.feature

#5749 Create New Visit from follow up cases

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java

#5862 Always reset all filters in events and eventgroup view

---

sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/PopulationDataFacadeEjb.java

#5537 Correctly fetch district population from Database

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

#5529 Correctly link events when merging cases

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

Bug 5775 events can be linked to pseudonymised cases

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java

[#5863] allow local external URLs

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/jurisdiction/JurisdictionValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java

Bugfix 5644 jurisdiction fixes

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/jurisdiction/JurisdictionValidator.java

#5644 - fix issue editing contact on mobile app

---

sormas-backend/src/main/resources/visualisation/transform_contact.R

#5678 Color all confirmed classifications identically in network diagram

---

sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_case_read_layout.xml
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#5915 Allow users to define custom outcomedate on unknown outcome

---

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/Pseudonymizer.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

Bug 5763 setting contacts to no contact / cancelling follow up in bulk edit mode can lead to data loss

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature

Added implementation for item 5686
used test for change source
added an extra change source step and check
added remove source case step
No allure report due to not working allure library on M1 macbook. Please check 15 times script running on your side.
On my side it worked well with 15 runs.

#5686-Added implementation for change and delete source case test

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/event/EventParticipantDao.java

#5849 - Fixed the query to retrieve event participant by case

---

sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/SourceContactListComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/CaseEpiDataView.java

Bugfix 5841 contacts with source case not shown

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventIndexDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantIndexDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantListEntryDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/therapy/PrescriptionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/therapy/TreatmentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/JurisdictionHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java

Feature 5651 event participant grid case

---

sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasCaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEventFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasLabMessageFacadeEjbTest.java

#5850 Make sure S2S tests are correctly executed

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbTest.java

Feature 5823 avoid user joins

---

sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionServiceTest.java

#5934 Add S2SEncryptionServiceTest

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/FacilityCategory.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/FacilityType.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/Gender.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactsLineListingPage.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/ContactsLineListing.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/ContactsLineListingService.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactsLineListingSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/LineListing.feature

#5835-add Contacts using Line Listing

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/campaign/CampaignDao.java

#5941 - Campaign drop down in mobile app defaults to wrong campaign

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java

#5559 - Adding back deleted event participants is not possible

---

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ServerAccessDataService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ShareDataBuilderHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java

Fixes #5800 
Important change is that `isFeatureEnabled` does not run any logic when involved. This allowed for cleanup in `ServerAccessDataService` and more correct error paths.

[#5800] simplier detection logic for S2S feature enabeled

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java

#4694 -fix event & event participant pages for lab officer

---

sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitService.java

#5951 - Unexpected error when create new visit in Contacts section

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java

#5544 - Fetch all the linked events for resulting case

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#5852 Refine the split of jurisdiction and place of stay - fix facility combo update

---

sormas-backend/src/main/java/de/symeda/sormas/backend/geocoding/GeocodingService.java

#5992 Handle timeouts when setting multiple geocoordinates

---

sormas-api/src/main/java/de/symeda/sormas/api/region/CommunityFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/region/CountryFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/region/DistrictFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/region/RegionFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CommunityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/DistrictFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/RegionFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/CommunityResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/CountryResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/DistrictResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/RegionResource.java

filter+pagination for coutries, regions, districts, communities

---

sormas-api/src/main/java/de/symeda/sormas/api/visit/VisitFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/PrescriptionResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/TreatmentResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/VisitResource.java

#5710 casefollowup

---

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataView.java

#5884 Add scrollbar to campaign form create/import dropdowns

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java

Let admin supervisor delete and archive events

---

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/CampaignController.java

#5984 Hide delete and archive button on campaign create form

---

sormas-e2e-performance-tests/SormasPoc.jmx

#6007_Fix/Update_create_case_performance_test

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java

Fix test #5958 and #5957

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

#5736 Correctly set null-facility on casecreateform

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

#6027 have freetext fields also search for internaltoken

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java

#6028 correctly differentiate placeofstay- and responsible-rdcf

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java

#6035 Exclude persons without associated entities from queries

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

#6016 Correctly update POEs based on district

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#6062 Fix NPEs when creating case as Hospital Informant

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#6069 Disable share-case-button when no Surveillance Tool is enabled

---

sormas-rest/src/main/java/de/symeda/sormas/rest/PrescriptionResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/TreatmentResource.java

change the getIndex endpoint to get a criteria with filter

---

sormas-app/app/build.gradle

update io.crowdcode.sormas.lbds dependency versions (#6081)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/Pseudonymizer.java
sormas-backend/src/test/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjbTest.java

#4756 - fix immunization jurisdiction filter + adapt person filter

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJoins.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java

#5999 - remove unnecessary join to cases

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFollowUpDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFollowUpDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbPseudonymizationTest.java

#5823: Join on case contact instead of subquery

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

#6070 Change type of caseIdIsmField to work with different formats

---

sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
sormas-rest/src/main/java/de/symeda/sormas/rest/ImmunizationResource.java

#4756 - Added the missing methods in the immunization facades

---

docs/TROUBLESHOOTING.md

#6108: Doc how to enable performance logging

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java
sormas-ui/src/test/java/de/symeda/sormas/ui/utils/ShowDetailsListenerTest.java

#5549 Add doubleclick timer to showDetailsListener

---

sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/views/about.scss

Fixes Review findings for #1829 and #4766

#1829 #4766 Increase Spacing for aboutsection 

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java

Introduce feature configurations for cases-contacts-samples, events and lab messages

---

sormas-app/app/src/main/java/de/symeda/sormas/app/component/validation/ValidationHelper.java

#6074 Make sure DateIntervalValidator only compares DayMonthYear

---

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/ShareTreeCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasEntityInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ShareDataBuilderHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SyncDataDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/CaseSyncData.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/ProcessedCaseDataPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/SormasToSormasCaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/contact/ContactSyncData.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/contact/ProcessedContactDataPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/contact/SormasToSormasContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/EventSyncData.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/ProcessedEventDataPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/SormasToSormasEventFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasCaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEventFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java
sormas-ui/src/test/java/de/symeda/sormas/ui/MockProducer.java

#6019 [Sormas2Sormas] Automatic Sync with every instance, when a shared dataset changed

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CountriesGrid.java

Make search on countriesgrid case-insensitive #6114

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#6152 Display correct uuid when case is not sharable with external reporting tool

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/CaseShareDataBuilder.java

Fix sharing samples when accept/reject feature is turned on

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsFilterForm.java

#3603 Hide country-specific values in ContactsFilterForm

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilitiesView.java

#6156 Update facilityCount whenever necessary

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonAssociation.java
sormas-api/src/main/resources/enum.properties
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryJurisdictionPredicateValidator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbUserFilterTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

#6170 fix findings

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/sharerequest/SormasToSormasShareRequestFacadeEJB.java

#6086 [SORMAS2SORMAS] Shares > Sorting by column Ownership handed over results in error

---

sormas-backend/src/main/java/de/symeda/sormas/backend/region/SubcontinentFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/ContinentsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/ContinentsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CountriesGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/SubcontinentsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/SubcontinentsView.java

Make (sub)continent grids eagerloaded #6169

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonAssociation.java
sormas-api/src/main/resources/enum.properties
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

Feature 6170 person all search warning

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java

Close popup upon buttonpress #4205

---

sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsFilterValuesElement.java

Increase statistics dropdown width #1795

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java

replace identity of dates with Objects.equals (#6177)

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/EventResource.java

#6196 event by UUID

---

sormas-app/app/src/main/java/de/symeda/sormas/app/lbds/LbdsIntentSender.java

fix headers for LBDS (#6207)

---

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

#6209 - Don't show person association types for disabled features

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/eventimport/EventImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/travelentryimport/TravelEntryImportFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/DataImporter.java

#6144 Import module should not consider white spaces for infrastructure data names

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactImporter.java

#6200 Fix duplicate community check on contact import

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGrid.java

#3890: Disabled sorting for new columns

---

sormas-api/src/main/java/de/symeda/sormas/api/symptoms/SymptomsHelper.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/SymptomsHelperTest.java

#6171 Always set the symptom value if it is the first time the symptom is reported

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/events/BulkEventDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java

Add Event Management status field into Bulk edit form for event #5783

---

sormas-rest/src/main/java/de/symeda/sormas/rest/SampleResource.java

#6218 Get sample by uuid

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java

#6222 - fix immunization table columns on android app

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageSlider.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/sormas.scss
sormas-ui/src/main/webapp/VAADIN/themes/sormas/views/lab-message.scss

[Lab Messages] improve the display of lab messages

---

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataView.java

#6162 Make campaign popup close upon buttonpress

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
sormas-backend/src/main/java/de/symeda/sormas/utils/EventJoins.java

#6236 Remove bad join from eventjoins

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java

#3788 Set exposure-case when converting contacts to cases

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/Immunization.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjbTest.java

#5946 - immunization automation

---

sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/importer/CaseImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/importer/LineListingImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/InfrastructureImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/CaseContactsImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactsImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventparticipantimporter/EventParticipantImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/importer/EventImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/AbstractImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/importer/TravelEntryImportLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DownloadUtil.java

#6244 - Use translated data dictionary in import popups

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-backend/src/main/resources/sql/sormas_schema.sql

#4763 Add missing vaccination columns

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java

#6261 Exclude deleted entities in dashboard

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java

#6280 - Made event identification source sortable

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java

#6275 Fix contact merging when person has multiple primary contactdetails

---

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureDaoHelper.java

#6260 Correctly set noneFacility in Androidapp

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/layout/LineListingLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/birthdate/BirthDateField.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/linelisting/person/PersonField.java

#6282 Fix case/contact linelisting

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

#6293 Make placeofstay editable for Community Officers

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java

#6290 Make followup-date sort properly 

---

sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java

#6273 update case share status filters

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryService.java

unlink deleted Cases from TravelEntries (#6284)

---

sormas-app/app/src/main/res/layout/fragment_event_edit_layout.xml

#6294 make event status non-nullable in androidapp

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryService.java

Fixed #6267

---

sormas-api/src/main/java/de/symeda/sormas/api/travelentry/TravelEntryFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntriesView.java

#6304 Add userfilter-less count to travelentryfacade

---

sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java

#6285 Correctly set different jurisdiction in TravelEntry form

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/EventParticipantResource.java
sormas-rest/src/main/java/de/symeda/sormas/rest/EventResource.java

#6255 event participants pagination filter

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageDto.java
sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessage.java
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-backend/src/test/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjbTest.java

#5622: Added reportId to LabMessage

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

#6303 Correctly update facilities on casecreateform 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/importer/TravelEntryImporter.java

Fixed #6307

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/caseimport/CaseImportEntities.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
sormas-api/src/main/java/de/symeda/sormas/api/travelentry/travelentryimport/TravelEntryImportEntities.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/res/layout/fragment_case_new_layout.xml
sormas-app/app/src/main/res/layout/fragment_contact_new_layout.xml
sormas-app/app/src/main/res/layout/fragment_person_edit_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/eventimport/EventImportFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/importer/ContactImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventparticipantimporter/EventParticipantImporter.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java

make sex required at person level (#6248)

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonAssociation.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonCriteria.java
sormas-api/src/test/java/de/symeda/sormas/api/person/PersonCriteriaTest.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJoins.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

Feature #6188 improve person queries

---

sormas-api/src/main/java/de/symeda/sormas/api/region/DistrictFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormDataFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/DistrictFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/DistrictService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDataProvider.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardFilterLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardView.java

#6111 Setting diagram definition percentage default "as true" throws an error when org units are selected on the dashboard

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-backend/src/main/resources/sormas_import_all_countries.csv
sormas-backend/src/main/resources/sql/sormas_schema.sql

#5689: Sub-continent association change Germany

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java

#6246 return distinct results from getSimilar*()

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/vaccination/VaccinationEntity.java
sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java

#4763 - Small fixes

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/Contact.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactJoins.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserReference.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
sormas-backend/src/main/java/de/symeda/sormas/utils/CaseJoins.java
sormas-backend/src/main/resources/META-INF/persistence.xml

#5229 Add multiple variables to detailed and custom export

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java

#6241 [S2S] Revoking accepted case results in inconsistent status of cases

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties

#6406 - Translation for point of entry details

---

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

6412 travel entry feature configuration

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/layout/LineListingLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/birthdate/BirthDateField.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/linelisting/person/PersonField.java

Person details not adopted in contact line listing from event participants

---

sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilityEditForm.java

#6366 - Add validation to contact person fields in configuration

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/components/linelisting/LineListingLayout.java

fixes #6360

---

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java

fixes #6391

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
sormas-api/src/main/resources/validations.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java

#6369 Validate case facility type

---

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/DEAFormBuilder.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java

#6388 - fix dea content rendering for empty or 1 entry json

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/access/SormasToSormasDiscoveryService.java
sormas-rest/src/main/java/de/symeda/sormas/rest/SormasToSormasResource.java

[#6421] more logging statements for S2S

---

sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java

Fixes a test sometimes failing.

#6246 fix unstable test

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java

fixes #6416

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java

#6424 - Added immunizations and travel entries to person UUIDs call

---

sormas-rest/src/main/java/de/symeda/sormas/rest/security/KeycloakFilter.java
sormas-rest/src/main/java/de/symeda/sormas/rest/security/MultiAuthenticationMechanism.java

[#6431] s2s should work with local keycloak enabled

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java

Missing infrastructure sheets in data dictionary

---

sormas-api/pom.xml
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasEncryptionFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/crypt/CmsCertificateConfig.java
sormas-backend/src/main/java/de/symeda/sormas/backend/crypt/CmsCreator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/crypt/CmsPlaintext.java
sormas-backend/src/main/java/de/symeda/sormas/backend/crypt/CmsReader.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ShareRequestData.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/crypt/CmsReaderTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java
sormas-rest/src/main/java/de/symeda/sormas/rest/SormasToSormasResource.java

#6433: fixes naive sign then encrypt in S2S

---

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/TestReportDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/TestReport.java
sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/TestReportFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java

Fixes #5917 
Is to be merged alongside [#34](https://git.vitasystems.dev/sormas/sormas-demis-adapter/-/merge_requests/34)

Feature 5917 automatically prefill typing

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/access/SormasToSormasDiscoveryService.java

Fixes #6385
I forgot to close the etcd client connection properly, we are using try-with-resource now...

[#6385] properly close etcd client connections

---

sormas-backend/src/main/resources/sql/sormas_schema.sql

#6269 Fix differing history tables

---

sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/TemplateEngine.java

#6407 - Sanitize specific characters in document template input

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java

fixes #6296

---

sormas-e2e-performance-tests/SormasPoc.jmx

Created performance tests for: post immunization, get all immunizations, get specific immunization. Added extra asserts.

#6364-Update-PerfTests-With-Immunizations-And-Persons

---

docs/DEVELOPMENT_ENVIRONMENT.md

Indicate to import project as a maven project

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java

#6454 change s2s share dialogue captions

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AdoService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java

#6449 solve the bug to allow creation of entities with null uuid

---

sormas-api/src/main/java/de/symeda/sormas/api/event/EventExportDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java

Add investigation start/end dates to event detailed export

---

sormas-e2e-performance-tests/SormasPoc.jmx

Change assertiontypes #6534

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java

#6458 Adapt case bulk classifications to locale

---

sormas-e2e-performance-tests/README.md
sormas-e2e-performance-tests/SormasPoc.jmx

#6538 use variables for e2e-performancetest-configuration

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

#6362 Increase performance of saving new persons

---

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntriesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryListComponent.java

Bugfix 6492 travel entry directory does not reload

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/components/statistics/summary/DiseaseSummaryComponent.java

#6510 - Show reference definition only for Germany

---

sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java

reset MockProducer properties before test (#6557)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java

#6571 - Fixed sorting by action date

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitLogic.java

#6553 - Fixed error for visits with symptomatic null

---

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java

fix display of duplicate person selection #6491

---

sormas-ui/src/main/java/de/symeda/sormas/ui/ActivityAsCase/ActivityAsCaseField.java

#6545 - Display other when details are empty

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/captions_de-DE.properties

#6439 Add missing caption for ownership handed over in Shares

---

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/EventPreviewGrid.java

#6576 [S2S] Event preview produces error when event does not have a disease

---

sormas-ui/src/main/java/de/symeda/sormas/ui/importer/AbstractImportLayout.java

#5459: fixed errors

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java

#6515 Test result positive for contacts in DEMIS lab messages is saved as pending

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java

#6498 Events > Bulk Actions > Send to reporting tool visible on non-DE systems

---

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestForm.java

fixed #6577

---

sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationDto.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/immunization/ImmunizationDao.java
sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationEditFragment.java
sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewFragment.java
sormas-app/app/src/main/res/layout/fragment_immunization_edit_layout.xml
sormas-app/app/src/main/res/layout/fragment_immunization_new_layout.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/DirectoryImmunizationService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/fields/pickorcreate/ImmunizationInfoLayout.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/filter/ImmunizationFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationCreationForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java

* Made facility fields not required
* Fixed missing label in web app
* Removed empty selection for management status
* Fixed management status overwrite in edit form
Fixes #4764

#4764 - Cleanup and bugfixes

---

sormas-api/src/main/java/de/symeda/sormas/api/importexport/ValueSeparator.java
sormas-api/src/main/resources/enum.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/importer/AbstractImportLayout.java

#5459: Include default separator in brackets

---

sormas-api/src/main/java/de/symeda/sormas/api/geo/GeoLatLon.java
sormas-backend/src/main/java/de/symeda/sormas/backend/geocoding/GeocodingService.java

#6506 Still error by setting geo coordinates via bulk action

---

sormas-api/src/main/java/de/symeda/sormas/api/outbreak/OutbreakFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/outbreak/OutbreakFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/outbreak/OutbreakService.java
sormas-rest/src/main/java/de/symeda/sormas/rest/OutbreakResource.java

#6659 outbreaks pagination

---

sormas-ui/src/main/java/de/symeda/sormas/ui/ActivityAsCase/ActivityAsCaseField.java

show typeOfPlaceDetails for typeOfPlace OTHER #6545

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestList.java

fixed #6579

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java

Fix updateFacility for facilityOrHomeValue HOME #6495 #6607

---

sormas-e2e-tests/scripts/runGivenTimes.sh

added allure installation script to add allure on the cenOS machine to generate allure reports

#6574-Add-Install-Allure-Script

---

sormas-e2e-tests/scripts/runGivenTimes.sh

removed allure script installation from loop script

#6547-Remove-Install-Allure-Script

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java

fixed #6628

---

sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java

#6578 improve mock producer

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java

#6379 delete cases sample

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java

#6708 - Filter by responsible user in events directory

---

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasCasePreview.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasContactPreview.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasEventParticipantPreview.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasEventPreview.java
sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasPersonPreview.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/CaseShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ContactShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/EventShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/PreviewGridHelper.java

#6640 [S2S] Data is not pseudonymized in share request preview

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/AccessDeniedException.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/visit/VisitFacadeEjbPseudonymizationTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/SormasErrorHandler.java

#6643 [S2S] Editing entities with handed over ownership automatically returns them

---

sormas-backend/src/main/java/de/symeda/sormas/backend/central/EtcdCentralClient.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/access/SormasToSormasDiscoveryService.java
sormas-backend/src/test/java/de/symeda/central/EtcdCentralClientTest.java

Fixes #6728 
Encapsulates the functionality better and will be very helpful in my other PRs fetching infra data from central.

[#6728] deserialize objects in etcd get* methods

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/VaadinUiUtil.java

Bugfix 6013 climedo integration cases & contacts lost symptom journal link

---

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java

handle follow-up until date for diseaeses without follow-up #5634

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

Bugfix 6631 reassign tasks

---

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryController.java

#6725 - Redirect to travel entry after creating it

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java

fixed #6561

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasOptionsForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldHelper.java

6684 send samples automatically with ownership
