sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGridComponent.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/orderedlayout.scss

#2144 
PROBLEM:
The filter layout on Table Pages does not wrap the child controls. Hence the need to scroll horizontally to access all filter controls
SOLUTION:
Layout wrap style added to css
added the style to filterLayout on Sample list page

The filter layout on Table Pages to wrap the filter controls

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

I do now a more specific exception when a too large epid number is checked. 
@MateStrysewskeSym 
- please review and merge this.
- Consider whether, how and by whom the length validiation can be made in `sormas-ui` and `sormas-app`.

Feature 2312 large epid number validated

---

sormas-base/pom.xml
sormas-rest/README.md
sormas-rest/build.xml
sormas-rest/src/main/java/de/symeda/sormas/rest/swagger/SwaggerConfig.java

This pull request proposes two enhancements to the current Swagger documentation process:
Let enums be specified by their own named schemas, instead of being specified as inline value constraints. This should be helpful for API clients since enum types become referencable by name. It should also reduce specification file overhead, since an enum's values are only defined once.
In order to gain access to the OpenAPI files describing the SORMAS REST API, one currently needs to check out the repository and execute the required tasks, which may pose a challenge for those not familiar with the SORMAS build system. It may be easier for potential API users if such specifications are included in the release bundles. Therefore, the `sormas-rest/build.xml` file is adjusted such that the generated …

Swagger adjustments

---

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserFacadeEjbTest.java

I fixed this defect. I think it could go into version 1.43, but does not have to.

#2272: Removed distinct when filtering, added appropriate unit tests

---

sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/CampaignGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/AreasGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CommunitiesGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/DistrictsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilitiesGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/PointsOfEntryGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/RegionsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/AbstractContactGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactFollowUpGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactGridDetailed.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FilteredGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java
sormas-ui/src/main/java/de/symeda/sormas/ui/visit/VisitGrid.java
sormas-ui/src/test/java/de/symeda/sormas/ui/utils/ShowDetailsListenerTest.java

I was not able to reproduce the NPE, but refactored all `ItemClickListener`s to the new `ShowDetailsListener` which does not execute the `itemHandler` if `event.getItem() == null`.

Feature 2240 unify grid itemclicklistener for navigate and avoid NPE

---

.travis.yml
sormas-backend/pom.xml
sormas-base/pom.xml
sormas-ui/pom.xml

Some maven warnings are fixed in this PR
fixes #2583

fix maven warnings

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleList.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListEntry.java

This is an example for #2654 with the goal to group related files/functionality together. Makes it easier for new contributors to navigate `ui/samples`.

[2654] add samplesLink package

---

sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractFilterForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/print.scss
sormas-ui/src/main/webapp/VAADIN/themes/sormas/styles.scss

Closes #3020
These CSS rules are not perfect because they use structural classes/elements to change the behavior instead of semantic classes.
Adding some CSS classes could help to have clearer and maintainable rules.
Result examples:
- [event_actions.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/5316422/event_actions.pdf)
- [event_participant.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/5316423/event_participant.pdf)

Issue #3020 Adds printable CSS

---

CONTRIBUTING.md

I added documentation for Product Backlog and Sprint Backlog how I propose them to be used.
Please review this and let's see if it fits for us in the Refinement before we merge this.

Feature 2958 update board documentation

---

sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/grid.scss

Set fixed background-color for VAADIN grid header cells to in-transparent white

[IMIS] fix for issue #2812

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/classification/ClassificationHtmlRenderer.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/HtmlHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/views/classification.scss

closes #3220 
- classification rules are now formatted correctly
- a new helper method `unescapeBasicTags(String escapedString)` has been added, which will re-enable `<b><i><li><ul><br>` tags in an escaped html-string
- cases classified by System will now show so correctly

[IMIS] #3220 Fix classification-rule HTML formatting, add helper method to unescape specific tags

---

sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java

The download of generated documents does not reliably start.
The problem seems to be a race condition between creating a FileDownloadResource and closing the modal window.
The solution is not to close the modal window automatically.

#3317 Quarantine order download does not reliably start

---

sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionListEntry.java

Please note that the background-color tag is still nonfunctional, as it would require to enable css inputs which is potentially unsafe.
Fixes #3193

[IMIS] Fix #3193 to re-enable html styling for event actions

---

sormas-api/src/main/java/de/symeda/sormas/api/ReferenceDto.java
sormas-rest/src/main/java/de/symeda/sormas/rest/swagger/AttributeConverter.java
sormas-rest/src/main/java/de/symeda/sormas/rest/swagger/SormasSwaggerExtensions.java
sormas-rest/src/main/java/de/symeda/sormas/rest/swagger/SwaggerConfig.java
sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionEditForm.java

Ticks partially one box of #3360 
This fix makes the `uuid` fields of all reference DTOs required. -> this makes the `uuid` fields in the openAPI description required -> clients generated from this api spec validate automatically that uuids are set correctly in the request -> this solves (partially) my problem
Please note that this does not add any server side validation, providing empty `uuid` values in references still triggers an internal server error (500) and is not gracefully handled (i.e., 400). This is left as future work, but having this change included in the repo would tremendously help me to debug the API.

[IMIS] 3360 reference dto required UUID

---

CONTRIBUTING.md
README.md
SECURITY.md

Include a `SECURITY.md` which states how we handle responsible disclosure as discussed internally.
Kudos to @chThie for creating the file!
@markusmann-vg @MartinWahnschaffeSymeda @kwa20

document responsible disclosure process

---

sormas-ui/src/test/java/de/symeda/sormas/ui/caze/importer/CaseImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/contact/importer/ContactImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignFormDataImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/eventparticipantimporter/EventParticipantImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/importer/CountryImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/importer/InfrastructureImporterTest.java

Fixes test in sormas-ui that fail when run on a local branch with blanks (' ').
The related issue described in #3480 for sormas-backend will be addressed in a separate pull request.
Additional cleanup:
- assignment of importResult in CaseImporterTest, l.66/67, removed, since the value is not used
- IOException removed from method declarations where it is not thrown

Fix failing tests in sormas-ui on local path with blanks (fixes #4024)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/resources/META-INF/persistence.xml

In the eventparticipant list of an event, the contact-count is calculated (depending on filters: with or without source case in event).
This PR implements improved queries which should perform much better on large databases (see #4084 for details)

#4084 improve eventparticipant contact queries

---

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/contacts/ContactsDashboardView.java

Closes #4052 
the Problem was that the related methods tried to change visibility of `networkDiagramRowLayout`, which only exists if you have special user rights (which contact officers miss).

#4052 Fix bug where contact officer could not expand map and chart

---

sormas-api/src/main/java/de/symeda/sormas/api/symptoms/SymptomsDto.java
sormas-api/src/main/java/de/symeda/sormas/api/symptoms/SymptomsHelper.java

Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
I think #4193 occurs because the two fields are public.
This PR makes them private and changes the access to a field by replacing the direct access by the getter

#4193 fields should not be public

---

sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/EventDocumentFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/QuarantineOrderFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/TemplateEngineTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/TemplateTestUtil.java

Clean line separators `\r\n` before text comparison.

fix text comparison in failing tests under Windows (#2906)

---

sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/window.scss

This should fix #2447 (As well as #3601 and #3850).
However this change might have unintended side effects as it changes some "top-level" css, so the UI should be tested thoroughly.
**Please not that you might need to do a full page-reload as most browsers store css in their caches!**  (Ctrl-F5 on Firefox)

#2447 Prevent unintended page scrolling on create forms

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4214
Outcome date is used for all countries in the case but it was exported only for Switzerland

#4214 Add "Date of outcome" to Detailed Export for Cases

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java
sormas-ui/src/test/java/de/symeda/sormas/ui/MockProducer.java

PR that replaces the usage of `Executors.newSingleThreadScheduledExecutor()` with `ManagedScheduledExecutorService` resource provided by container. It avoids [creation of uncontrolled threads](https://www.adam-bien.com/roller/abien/entry/can_i_start_threads_in).
#4243

Avoid creating ScheduledExecutorService

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

Remarks from  https://github.com/hzi-braunschweig/SORMAS-Project/issues/4243#issuecomment-778222278:
- `ExternalJournalService.notifyExternalJournalPersonUpdate` is called from `ExternalJournalService.handleExternalJournalPersonUpdate` only. Wether an external journal is active at all is checked there first (fixed in #4306).
- `ExternalJournalService.shouldNotify` is about detecting changes form updates where initially only the previous state is known. Unfortunately even `PersonDto.isEnrolledInExternalJournal()` may have been subject to change, so fetching the person data is necessary

refactor ExternalJournal update (#4243)

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbPseudonymizationTest.java

Closes #4193 
Samples of contacts and event participants are now considered as active samples if they are not deleted.
Does this have implications for the App @MateStrysewske ?

[#4193] include samples of contacts and event participants

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java

Unfortunately, `groupBy` is not sufficient to avoid the `maxSampleDateTime` comparison altogether: if an event participant is retested, it is the result of the last sample which is of interest.
fixes #4653

ignore deleted samples, only one entry per participant (#4653)

---

sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/table.scss

Adds 15px bottom padding to tables so this doesn't happen:
(Relevant e.g. for exposure tables)

#4053 Add bottom-padding to tables so that scrollbars wont cover content

---

.github/workflows/github_pages.yml
README.md
docs/CONTRIBUTING.md
docs/SERVER_SETUP.md
mkdocs.yml
sormas-base/doc/keycloak.md
sormas-keycloak-service-provider/README.md

Closes #5006 
preview [here](https://healthimis.github.io/SORMAS-Project/)
The following is changed:
1. Add an GitHub action which populates GitHub pages with the latest documents from `development` (we could change this to `master` if desired).
2. `GUIDE_ADD_NEW_DISEASE.md` and `GUIDE_ADD_NEW_FIELDS.md` were removed, therefore I removed the referencing links in `CONTRIBUTING.md`. If these two files were removed by accident, I can add them again in this PR.
3. A couple of links referenced non Markdown or HTML files, which causes problems with GitHub Preview + Pages, so I removed them
4.  `GUIDE_SORMAS2SORMAS_CERTIFICATE.md` was removed but was still referenced from `SERVER_SETUP.md`, so I removed the link as well. I feel this file should be included again as S2S is a complex feature and …

[#5006] add mkdocs github pages

---

.github/workflows/ci.yml
.github/workflows/openapi_canary.yml

@FredrikSchaeferVitagroup Here are my changes :)
Logistic-wise I think it is better to ship this with your PR (base of this PR is your branch)
1. A new CI action is introduced which runs only on development after the tests are successful: It commits the build swagger files automatically to development. This gives us a reliable single source of truth regarding the openAPI files
2. A canary workflow is introduces which checks once per day if there are any changes between development and master. This will start to work after the next release when develop becomes the new master b/c then the files from (1) are also present on master and a diff can happen. See [here](https://github.com/healthIMIS/SORMAS-Project/runs/2324753779?check_suite_focus=true) for an example failure.
The action is based …

[#3383] add GitHub Action openAPI canary

---

sormas-backend/src/main/resources/sql/sormas_schema.sql

#5111: Retrospectivly make DROP commands compatible with PostgreSQL 9.6

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java

closes #4138 
Fixes the finding from the internal review ("Information is not shown when follow-up is resumed")

#4138: Fix missing info after resume

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseLogic.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactLogic.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactServiceTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java

* Automatically reset follow-up until to expected follow-up until when "overwrite follow-up until" is unchecked
* Automatically extend follow-up until to expected follow-up until when contact/case start date is changed
* Expected follow-up until date is now always correctly calculated and does not take into account the currently filled in follow-up until date
* Automatically uncheck "Overwrite follow-up until" when the date is automatically changed to a later date than the current follow-up until date
Fixes #4191

#4191 - Fixed issues in follow-up until calculation logic

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java
sormas-base/setup/sormas.properties

Fixes #4936 
The whole epsg4326_wkt string is now also configurable, to give users more flexibility when using custom shapefile sources

#4936 fix lat/long order and add EPSG4326_WKT String to sormas.properties

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java

#5153: Add read timeout for sending external surveillance requests to prevent endless loading in case something goes wrong

---

.github/workflows/ci.yml

Fixes #5355 
We now check if the PR comes from this repo base or is a fork. Depending on this we checkout differently.
Have a look at the [CI run](https://github.com/hzi-braunschweig/SORMAS-Project/pull/5358/checks?check_run_id=2526572196) from this PR: Token was checked out and cache was used.
In my example PR [run](https://github.com/hzi-braunschweig/SORMAS-Project/pull/5359/checks?check_run_id=2526558475) from a fork, the checkout without token is used and caching is skipped due to security implications.

[#5355] checkout without token on fork PRs

---

sormas-e2e-tests/README.md
sormas-e2e-tests/build.gradle
sormas-e2e-tests/scripts/runGivenTimes.sh
sormas-e2e-tests/src/main/java/org/sormas/e2etests/common/CommonInjectorSource.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/common/CommonModule.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/CaseService.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/ui/DriverMetaData.java
sormas-e2e-tests/src/main/java/org/sormas/e2etests/ui/DriverModule.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/AssertHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/LoginSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/NavBarSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/cases/CaseDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/cases/CreateNewCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/cases/EditCasePersonSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/contacts/ContactDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/contacts/CreateNewContactSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/events/CreateNewEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/application/events/EventDirectorySteps.java
sormas-e2e-tests/src/test/resources/allure.properties
sormas-e2e-tests/src/test/resources/allurefiles/categories.json
sormas-e2e-tests/src/test/resources/allurefiles/environment.properties
sormas-e2e-tests/src/test/resources/features/sanity/Login.feature

Description ->
After this feature we are able to have the allure reports without using the `allure serve` command, and we can have very nice history.
1. Now you need to start the tests by using the command : `./gradlew startTests -Dcucumber.tags="@Login"`
2. After running the tests you will be able to find the allure report in the root of the project, in the `allureReports` folder
3. From now we can add `@issue=ticketNumber` to link Github bugs/tickets 👇

#5423-Update the automation framework reporting

---

sormas-backend/src/main/java/de/symeda/sormas/backend/crypt/CmsCreator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeHelper.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java

Fixes #5625 
- `encrypt` renamed to `signAndEncrypt`
- `decrypt` renamedt o `decryptAndVerify`
- remove duplicate code from the crypto functions and move it to dedicated functions
No functionality was changed

[#5625] refactor s2s encryption service

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ReceivedDataProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ReceivedDataProcessorHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/ReceivedCaseProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/caze/SormasToSormasCaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/contact/ReceivedContactProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/contact/SormasToSormasContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/ReceivedEventProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/event/SormasToSormasEventFacadeEjb.java

Fixes #5635 
This is a spin off from #5599, I want to keep the PRs small and easy to review.
While working on #5597, I noticed a lot of potential for code cleanup and deduplication which once resolved would make my life easier.
`SharedDataProcessor` is a little bit of a misnomer. Sharing in S2S means the operation of passing an entity to another instance (opposed to sync and return). However, `SharedDataProcessor` is always invoked on any _received_ data during the save phase of share, sync, and return operations. Therefore I suppose to rename it to `ReceivedDataProcessor`. This change nicely aligns with other changes I have planned for `AbstractSormasToSormasInterface` making the resulting code easier to understand.
Also this PR unifies some variable naming which will make the diff for …

[#5635] rename SharedDataProcesser to ReceivedDataProcessor

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java

Fixes #5671 
This is a spin off from #5599, I want to keep the PRs small and easy to review.
While working on #5597, I noticed a lot of potential for code cleanup and deduplication which once resolved would make my life easier.
`AbstractSormasToSormasInterface` has code duplication and can be simplified for my work on #5597.
This unifies the handling of the received S2S entities. We have two cases:
1. An entity is newly shared and does not exists in the system ("sharing"). Code paths handling existing entities are ignored.
2. An entity already exists in the system ("returning" and "syncing"). Code paths handling existing entities are executed.

[#5671] deduplicate code in AbstractSormasToSormasInterface

---

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/SormasToSormasEntityInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEncryptionService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/labmessage/SormasToSormasLabMessageFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasCaseFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasEventFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasLabMessageFacadeEjbTest.java

@vidi42 I currently try to establish correct interfaces to move forward with the 2nd gen S2S approach. I noticed that a lot of interfaces are leaky and there is 0 reason to let the developers handle the bytes on their own.
This is the first part of my changes to handle encryption and rest calls better.

[#5693] avoid leaky abstraction in SormasToSormasEncryptionService

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java

Added an extra person validation during the pseudonomyzation. In case the person is missing or the reference is invalid the creation of the event participant is failing.
Fixes #5601

5601_fix_null_person_event_participant

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/eventimport/EventImportFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java

Fixes #
There is no ticket, just found the issue by trying to import events

Fix string format exception when import fails because of wrong date format

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java

Fixes #6080 
Side effect: Auditlog is not triggered (the same with batch archive/dearchive of cases).

#6080 persist case completeness without changedate

---

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestLayout.java

Not related to the fix of the defect described in the issue.
The original issue cannot be reproduced anymore.
Closes #6067

Fix opening older share requests which don't have contacts or event participants

---

sormas-backend/src/main/resources/sormas_import_all_continents.csv
sormas-backend/src/main/resources/sormas_import_all_countries.csv
sormas-backend/src/main/resources/sormas_import_all_subcontinents.csv

Fixes #6712 
Turns out the existing logic can figure out the property path on its own, so just adding the UUID column was sufficient :)
Import works and I checked the UUIDs they are written to the DB as they should.

[#6712] add uuids to continents, subcontinents, and countries

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/DefaultEntityHelper.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/DefaultEntityHelperTest.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserTestHelper.java
sormas-rest/src/main/java/de/symeda/sormas/rest/security/MultiAuthenticationMechanism.java
sormas-ui/src/main/java/de/symeda/sormas/ui/login/DefaultPasswordUIHelper.java

Fixes #6696 
This is intentionally leaving out point of entry and facility. This is because they are (not yet included) in central, meaning UUIDs of these two types will also vary in the wild. To mimic this behavior while testing, both of the corresponding default entities will have random UUIDs.

[#6696] use constant UUIDs for region, district, community

---

sormas-api/src/main/java/de/symeda/sormas/api/InfrastructureDataReferenceDto.java
sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/GeoLocationFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/InfrastructureBaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/area/AreaReferenceDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/AbstractBaseEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractDomainObject.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/area/AreaFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/community/CommunityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/continent/ContinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/country/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/district/DistrictFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/pointofentry/PointOfEntryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/region/RegionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/subcontinent/SubcontinentFacadeEjb.java

Fixes #6587 
@MateStrysewske @MartinWahnschaffe @StefanKock you might want to take a look at this :)
What I did is the following:
I created an abstract class `AbstractBaseEjb` which in the future should implement default versions for all methods in `BaseFacade`. There is also `AbstractInfrastructureEjb` which currently works around some issue `AbstractBaseEjb` has. Every infrastructure ejb now extends the `AbstractInfrastructureEjb` and uses constructor injection to instantiate the used service.
In this PR, I only cleanup up (de)archiving, but you can do the same for e.g., `save` as well as, at least in the infra facades, its just copy pasted. Prospectively, I think we should apply this to more facades/ejbs and let them extend `BaseFacade` and `AbstractBaseEjb` respectively. 
Doing this …

[#6587] abstract class for shared functionality

---

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/InfrastructureBaseFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/area/AreaFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/community/CommunityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/continent/ContinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/country/CountryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/district/DistrictFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/pointofentry/PointOfEntryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/region/RegionFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/subcontinent/SubcontinentFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java

Fixes #6885 
Apparently, CDI did not like that there  were two methods with the same name in parallel types that did validation on the parameters. 
> If a sub type overrides/implements a method originally defined in several parallel types of the hierarchy (e.g. two interfaces not extending each other, or a class and an interface not implemented by said class), no parameter constraints may be declared for that method at all nor parameters be marked for cascaded validation.
See offical docs [here](https://beanvalidation.org/1.1/spec/#constraintdeclarationvalidationprocess-methodlevelconstraints-inheritance)
The resolution to this introduce a clear hierarchy in the object tree.
Tested the application as well, a long string exceeding 255 chars will not be accepted as region name.

[#6885] clear inheritance to enable argument validation

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/ExtendedReduced.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java

Fixes #6782
@MateStrysewske this PR contains some refactoring and should make field visibility related to previous quarantines more consistent. Please check if the behaviour is implemented as intended for multiple subsequent changes (extensions/reductions) of the quarantine end..

show previous quarantine end date in UI on creation #6782

---

sormas-rest/src/main/java/de/symeda/sormas/rest/RestConfig.java
sormas-rest/src/main/java/de/symeda/sormas/rest/security/KeycloakFilter.java

With this change the `sormas-rest` artifact cannot be deployed without having the `sormas-ear` deployed first.
I chose this instead of falling back to the legacy login because that might introduce more uncertainty that simply failing with an error message.
Fixes #5144

#5144 Fix sormas rest deploy inconsistency

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/ProcessedEntitiesPersister.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/ReceivedEntitiesProcessor.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/data/received/ReceivedEntitiesProcessorTest.java

|old|`de.symeda.sormas.backend.sormastosormas.entities.ReceivedDataProcessor`|
|---|:---|
|new|`de.symeda.sormas.backend.sormastosormas.entities.ReceivedEntitiesProcessor`|
|old|`de.symeda.sormas.backend.sormastosormas.entities.ProcessedDataPersister`|
|---|:---|
|new|`de.symeda.sormas.backend.sormastosormas.entities.ProcessedEntitiesPersister`|
Fixes #7200

#7200 Rename s2s classes with similar names

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseLineListingSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewVisitSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactPersonSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventActionsTableSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature

1. Added a potentially fix for combobox select where values can be selected twice due to selenium speed.
2. Added logs to investigate Date parsing issue on jenkins
3. Updated Edit person test by changing UI navigation to edited Person with URL navigation, due to environment's performance issues
4. Added fix for Create a new event and change its status multiple times
5. Added logger to investigate time parsing issue for: Add a New action for an Event and verify the Action in EventActions table
6. Added a small fix to check in jenkins for table row data parsing for: Change the source case contact and then delete
7. Added some small fixes for: Edit all fields from Follow-up visits tab
8. Added small fix for Create cases using Line Listing feature and validate the entries to check if is …

#7131-fix-flaky-UI-tests

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewVisitSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactPersonSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/UserManagementSteps.java

1. Updated wait for loading spinner to disappear in order to fix: Edit a new Sample
2. Added fixes for Create a new user (noticed flaky situations on local execution and jenkins)
3. Updated and fixed test with the latest changes: Add a participant to an event
4. Corrected jenkins failing assert for test Edit all fields from Follow-up visits tab in order to identify why it fails only during jenkins execution

#7131-FixFlakyUITests

---

sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/label.scss

Fixes #7213
This solution is generic and affects all v-labels in side components, s.screenshot.

cut label overflow in side components #7213

---

.github/workflows/ci.yml

Fixes #7543 
Here we go again...
Problem is apparently that the CI checkouts the commit of the branch rather then doing a full checkout with all refs, so updating will not work until everything is in place.

[#7543] ensure proper checkout and pull

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ValidationHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/infra/InfrastructureValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasShareable.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/SormasToSormasCaseDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/SormasToSormasContactDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/SormasToSormasEventDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/SormasToSormasEventParticipantDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/SormasToSormasImmunizationDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/labmessage/SormasToSormasLabMessageDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/SormasToSormasSampleDtoValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java
sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/validation/InfraValidationSoundnessTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/VaadinUiUtil.java

Fixes #6470 
This fixes the following:
----

[#6470] better S2S errors

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/webdriver/RemoteDriverFactory.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java

This changes file paths to use regular slashes instead of backslashes for Linux compatibility

Path fix for Linux

---

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java

Where fixed: 1. Window size that header with health department is displayed totally. 2. Was added new line passing for header line (prior all errors) 3. Was added new line passing for all errors. 4. Was adjusted width for groupErrorsLayout in order to see all complete words in errors(as sometime 1 word is missing)
Fixes #7757

#7757 - Info dialog does not show whole content. 

---

sormas-app/app/build.gradle
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/epidata/EpiDataPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/hospitalization/HospitalizationFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/symptoms/SymptomsPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskServiceTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/therapy/PresicriptionFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/therapy/TreatmentFacadeEjbPseudonymizationTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/visit/VisitFacadeEjbPseudonymizationTest.java
sormas-base/pom.xml
sormas-ui/src/test/java/de/symeda/sormas/ui/caze/importer/CaseImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/dashboard/campaigns/GridTemplateAreaCreatorTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/importer/EventImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/utils/DownloadUtilTest.java
sormas-ui/src/test/java/travelentry/importer/TravelEntryImporterTest.java

- hamcrest 1.3 -> 2.2
- junit 4.13.1 -> 4.13.2
- mockito 3.5.15 -> 4.3.1
Fixed imports:
- org.mockito.runners.MockitoJUnitRunner ->
org.mockito.junit.MockitoJUnitRunner
- org.mockito.Matchers.anyObject -> org.mockito.ArgumentMatchers.any
- org.mockito.Matchers -> org.mockito.ArgumentMatchers

#7978: Update test dependencies

---

sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/CleanHtmlReference.java
sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/NoIncludesEventHandler.java
sormas-backend/src/main/java/de/symeda/sormas/backend/docgeneration/TemplateEngine.java
sormas-backend/src/test/resources/docgeneration/eventHandout/EventHandout.cmp
sormas-backend/src/test/resources/docgeneration/eventHandout/EventHandoutPreformatting.cmp
sormas-base/pom.xml

- xdocreport 2.0.2 -> 2.0.3 (some breaking changes)
- velocity 1.7 -> velocity-engine-core 2.3
- commons-lang 2.6 -> removed
Initiating text templates in unit tests is broken:
```
EventDocumentFacadeEjbTest.generateEventHandoutTest
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'EventHandout.html'
at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:465)
at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:346)
at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1677)
at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1656)
at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:286)
at …
```

#7978: Updated xdocreport

---

sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRightsFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/util/XssfHelper.java
sormas-backend/src/test/java/de/symeda/sormas/backend/doc/UserRightsGenerator.java
sormas-base/pom.xml

Fixed breaking changes:
- color definition not with awt, directly with rgb colors (new helper)
- table configuration after filling cells with reference (new helper)
Refactorings along the way:
- Suppressed a warning locally
- Added a private constructor for helper class
- Removed commented code in Generator class
Fixes #6830

#6830: Update poi-ooxml

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/VaadinUiUtil.java

Fixes #7812
This was a bit tricky because my initial fix - simply making sure that the hospitalization is only saved after the user has submitted a facility - fixed the bug, but introduced other problems (e.g. the hospitalization form being kind of detached when discarding the popup to choose a facility, resulting in the Discard button of the form no longer working properly).
Introducing a pre-commit listener seemed like a good idea to me that we could potentially also utilise in other forms.

#7812 - Added pre-commit listener to hospitalization form

---

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java

Fixes #8090
backport from develop branch

#8090 Update disease variant prompt navigates to case when only save was selected

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature

This includes content from https://github.com/hzi-braunschweig/SORMAS-Project/pull/8050 manually applied on top of a fresh development branch clone, due to problems with rebasing the old branches.
The only change is the suggested removal of German wording from step definition.

Rebased tests for SORQA-69

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/TaskManagementFilter.feature

Razvan, that test should be not ignored. When I changed parsing for DE specific datetime test is passing. There is a bug in the Service and until developers will not fix it, the test should be red.
Bug: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8019
Report after changing date time parse for DE format: https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/91/allure/

sordev 5688

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-backend/pom.xml
sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLogger.java
sormas-backend/src/main/java/de/symeda/sormas/backend/audit/LogSink.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-base/pom.xml
sormas-base/setup/sormas.properties

Fixes #8029 
```json
{
"resourceType": "AuditEvent",
"type": {
"system": "https://hl7.org/fhir/R4/valueset-audit-event-type.html",
"code": "110100",
"display": "Application Activity"
},
"subtype": [
{
"system": "https://hl7.org/fhir/R4/valueset-audit-event-sub-type.html",
"code": "110120",
"display": "Application Start"
}
],
"action": "E",
"recorded": "2022-03-10T13:21:46.875+01:00",
"outcome": "0",
"outcomeDesc": "Application starting",
"agent": [
{
"type": {
"coding": [
{
"system": "https://www.hl7.org/fhir/valueset-participation-role-type.html",
"code": "110151",
"display": "Application Launcher"
}
]
},
"name": "SYSTEM"
}
],
"source": {
"site": "sormas_b",
"type": [
{
"system": "http://terminology.hl7.org/CodeSystem/security-source-type",
"code": "4",
"display": "Application Server"
} …
```

[#8029] add audit logging for server start

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java

Fixes #8500 
@syntakker Pointed the error out to me, will likely cause the latest deployment to fail.

[#8500] remove geocoding template from check as it is not an URL

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java

Fixes #8602 
Fixes https://github.com/hzi-braunschweig/SORMAS-Security/issues/36
Fixes https://github.com/hzi-braunschweig/SORMAS-Security/issues/35
I checked back with NL, they area already using https everywhere where we are going to enforce it.
Testbed will be adapted to this once it is merged

[#8602] enforce https where possible

---

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/PersonDirectoryPage.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDetailedTableViewSteps.java
sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature

https://jira.sormas-tools.de/browse/SORQA-121
Please note that this test differs slightly from the manual scenario - instead of clicking on a black arrow in the column header we click on the column header itself. This is due to the fact that said arrow is a pseudo-element, which are by definition non-clickable. A click on the arrow would register as a click on the header anyway.

Added a test for Person directory columns

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupFacadeEjb.java

Fixes #8850
The problem was that ContSup has EVENTGROUP_CREATE-right but not EDIT and in the code there was a check for EDIT right only. 
Removed all old right checks and kept only @RolesAllowed annotation

#8850 [User rights] Contact Supervisor cannot create new Event Group

---

sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java

Fixes #8909 
For a while I was wondering, whether it should be allowed to call LabMessageFacadeEjb.getIndexList(...) with null criteria.
I could not find a clear answer, so I left the current behaviour as is. Alternatively, one could not check `if (criteria != null)`.
This should only be merged after the hotfix was released.

#8909 only set filter when not null

---

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java

Added wait for spinner as a sleep, and waiting for spinner disappear with 50 seconds timeout. It was needed because tests started to check unloaded records in event tab

SORQA-203fix

---

sormas-api/src/main/java/de/symeda/sormas/api/dashboard/DashboardFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/PathogenTestResultDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/dashboard/DashboardFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleServiceTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DashboardDataProvider.java

Fixes #8704, replaces #8973.
Further improvements:
1. Fresh start from `development`, picked needed (and currently missing) method signature ` CaseService.createUserFilter(CaseQueryContext)`.
2. Removed some superfluous change noise on removed signatures.
3. Code comments within the new method `DashboardService.getNewTestResultCountByResultType`, some refactoring for better readable code.
4. Moved the DTO class out of the EJB (in favor for separate java file instead of inner class to have less cluttered EJB class code).
5. Documented SQL queries before/after here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8704#issuecomment-1112990750
I think we still need to move/integrate `SampleFacadeEjbTest.testGetNewTestResultCountByResultType` into `DashboardFacadeEjbTest`.

#8704 rewrite case tests results count

---

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/InfrastructureChangeDatesDto.java
sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/InfrastructureSyncDto.java
sormas-api/src/main/java/de/symeda/sormas/api/user/DtoViewAndEditRights.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DtoUserRightsHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/infrastructure/InfrastructureHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/outbreak/OutbreakDtoHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/ClientInfraSyncFacadeEjb.java

Fixes #8989
The simple solution from comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/8989#issuecomment-1112097217 was not workable (lack of separation between real 403 exceptions and intendedly catched ones, unclear interference with the overall synchronization mechanism), so I implemented the second option:
> I'd propose to do the following now:
> 
>     * [ ]  catch this exception for every entity type (can probably be put into a generic method) and ignore it for now. Instead go on with the next entity type
> 
> 
> Maybe in a separate issue that can go into the next sprint:
> 
>     1. Don't pull entity types the user cannot VIEW
> 
>     2. Don't push entity types the user cannot EDIT
Some Facades can be accessed with different UserRights, e.g., `VisitFacadeEjb` with …

edit/view rights in mobile app synchronization #8989

---

sormas-base/pom.xml

Fixes #9313 
Only relevant for S2S. And since we are doing the the hotfix anyway...
Already tested S2S works as usual.

[#9313] bump com.google.oauth-client

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java

- Distinct already was present: grouping not needed and might fail with
different user filter or jurisdiction selection
Fixes #9097

#9097 Removed group by clause, reuse Joins

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java

only update external system users on startup if userroles are found
This is the suggested solution for #4461 finding no. 31 (https://wiki.vitagroup.ag/pages/viewpage.action?pageId=87001413)
Fixes #

#4461: only create external system users on startup if userroles are found

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/DateHelper.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/DateHelperTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/AggregateReportsEditLayout.java

Fixes #9121 
As it was not specified what "same epi week" means, I assumed it is the week number and not the same begin or end date of the epi week. Edge cases with 53 weeks are 2017 and 2023.

#9121 Adjust selected epiWeek if selected year changes

---

sormas-api/src/main/java/de/symeda/sormas/api/BaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/pointofentry/PointOfEntryFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/location/LocationDto.java
sormas-api/src/main/java/de/symeda/sormas/api/travelentry/TravelEntryFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/CaseShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ContactShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/EventShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/EventParticipantShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ImmunizationShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/SampleShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasContactFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasEventFacadeEjbTest.java

Fixes #8674
This PR ensures that the validation logic of the EJBs runs after the shares have been built to ensure that the remote instance can process them correctly (recall that the save method on the remote will call `validate` as well, so we avoid a network round trip other problems as well).
The underlying issue is that our pseudonymizers can return data which does not pass the `validate` method of the EJBs. I made  some adjustments and I would appreciate @MateStrysewske to comment on the changes to
* LocationDto.java (more PersonalData )
* ShareDataBuilderHelper (i.e., should a valid `ContactDto` contain a reporting user?)
* SormasToSormasContactFacadeEjbTest: same w.r.t. `ContactDto`
I'm quite certain that more pseudonymizers show this behaviour and I'm going to file an issue about …

[#8674] validate shares after building them

---

sormas-api/src/main/java/de/symeda/sormas/api/audit/Constants.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseContactsView.java

Fixes #9838
This allows users to edit the contact of cases when received via S2S, independently of the handover status.

[#9838] contact editable for not handed over case

---

sormas-api/src/main/java/de/symeda/sormas/api/BaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java
sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantDto.java
sormas-api/src/main/java/de/symeda/sormas/api/immunization/ImmunizationDto.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/DataHelperTest.java
sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/pointofentry/PointOfEntryFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java

Fixes #9701 
@MateStrysewske This PR adds a validation to the API, however, the reporting user was either already checked in the validate method or it has a not null constraint in the DB. 
I went through the general setup here and I think we should start to phase out `@Required` over time, I'm going to write a dedicated issue for that.

[#9701] better user validation through annotations

---

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/contactfield/ContactLineField.java

Fixes #9530
The tooltip feature for hovering over combo box items is not available for Vaadin 8.:
https://vaadin.com/forum/thread/17044583/mouseover-tooltip-for-combobox-items
Due to the end of the sprint and the planned release, this PR provides a preliminary fix which increases readability of the combo box texts by increasing the width of the affected input fields.
Possibilities to provide the tooltip-on-hover feature within Vaadin 8 will be further investigated.

increase combobox width in contact line listing #9530

---

sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfo.java
sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoFacadeEjb.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalsurveillanceservice/ExternalShareInfoList.java

Fixes #10279
The problem was that automatic archiving triggers a share with archived flag to survnet that creates an external share info with SHARED status.
As it's called as SYSTEM there is no user to set the sender user of the external share info. I don't see why the automatic archivation did not fail when creating the share info without user.
Maybe we can create a ticket for better handling the shares did by the system

#10279 cases are not accessible

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/test/java/de/symeda/sormas/backend/externaljournal/ExternalJournalServiceTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/visit/ExternalVisitTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/visit/VisitFacadeEjbTest.java

Fixes #10390
Moved test cases from several test classes into a single test class and using the external visits user for calling backend facade methods related to the external visits resource.

#10390 create test suite for external visits

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseIndexDetailedDto.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseGridDetailed.java

Hide Event columns from Case Detailed View if the user doesn't have rights
- if the user is missing "EVENT_VIEW" rights than hide the event related collumns
- do not load Event fields for CaseIndexDetailedDto

#10346 Hide columns if missing right

---

sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/KeycloakService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRoleFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java

Fixes #9091 
@MartinWahnschaffe Just like we cannot add a client role to a normal user representation in an update, we cannot remove it.

[#9091] explicitly remove client role from keycloak user

---

sormas-api/src/main/java/de/symeda/sormas/api/utils/fieldaccess/FieldAccessCheckers.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/Pseudonymizable.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/PseudonymizableDto.java

Fixes #10547
Pseudonymization of not personal and/or sensitive data will not mark the DTO as pseudonymized.
The pseudonymized flag is used to mark sensitive and/or personal fields on the UI. The other inaccessible fields are not shown on the UI
The solution was discussed with @MateStrysewske

National User can no longer edit multiple sections from cases #10547

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderDocumentsComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalsurveillanceservice/ExternalSurveillanceServiceGateway.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataView.java

Fixes #10489
Survnet and Document template boxes where not added correctly to the view, so they weren't disabled together with the other ones

#10489 S2S_read only leads to active box 'send to reporting tool'

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java

Fixes #
#10165 Disable bulk action dropdown when EDIT_ARCHIVE_ENTITIS is false

#10165 Disable bulk oprations dropdown

---

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DtoFeatureConfigHelper.java
sormas-app/app/src/main/java/de/symeda/sormas/app/backend/feature/FeatureConfigurationDao.java
sormas-app/app/src/main/java/de/symeda/sormas/app/component/dialog/SynchronizationDialog.java
sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java

- in case an entity is not enabled (FEATURE_CONFIG) or the user does not have rights to view the specified Entity, then sync dialog callbacks should be synced with the available to view entities list
Fixes #10520

#10520 Fix Synchronization Dialog callbacks for Additional Test

---

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRoleFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRoleFacadeEjb.java

Fix Class Cast exception when generating statistics reports for Report User Role
Fixes #10645

#10645 Fix class cast exception when generating statistics reports

---

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractBaseEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/CaseShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ContactShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/EventShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/EventParticipantShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ImmunizationShareDataBuilder.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java
sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/TravelEntryFacadeEjb.java

Found opportunity to refactor this while working on #9708.
* convertToDto -> toPseudonymizedDto
* Moved abstract core methods up to base
* renamed/changed Person methods such that they override the new base methods

[#9708] move pseudonymization logic up to base

---

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonAssociation.java
sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/DirectoryImmunizationService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJurisdictionPredicateValidator.java
sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbUserFilterTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonServiceTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java

Fixes #10414
Progress:
Challenges to solve:

#10414 limit persons by config and user rights

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java

Remove the duplicate popup that appears when a person is already an event participant and the user links the person's case to that event
Fixes #10804

Pop-up to let the user know that the person is already an event participant is triggered twice #10804 

---

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java

- seems like Vaadin is throwing an error with "null" text so it has to be ignored
Fixes #10644

#10644 Do not append error messages with "null" text

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java

The checkboxes associated with reinfection are cleared only if the user save the changes made.
Fixes #10803

#10803 reinfection related checkboxes on case page remain unchecked

---

sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationFacade.java
sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java

Needed for vaccination refactoring in #9708
I'm a little bit unsure about the content of `createCiriteriaFilter` and consequentially about the function of `count` and `getByCriteriaFilter` as some fields of the criteria are/were not covered. Would be great to receive some feedback if this is correct or if I should add the other fields.

[#9708] add count method to vaccination

---

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java
sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesFilterComponent.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractMergeGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/QueryDetails.java

Fixes #9054
I have not adjusted the content of the existing warning in the duplicate view, because I have added a drop-down for the result count and was not sure how to adjust the existing text anyway.
I have tested it on a database with 85000 cases that result in 82000 potential duplicates, because they are generated. Using the limit of 100 or 1000 resulted in an execution of 1-3 seconds. Leaving the limitation away took more than 2 minutes.

#9054 case merge limit

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java

Inform the user when trying to link a contact to an event its person is already a participant of
Fixes #11244

#11244 - Inform user about person in event

---

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java

Ignore symptom journal status when pushing persons through the mobile app
Fixes #10858

#10858 - Sync person problem

---

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java

Don't show event participants with two or more samples on the same day multiple times
Fixes #11697

#11697 - Fix event participants index list

---

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java

Ensure that region and district are required when there's at least one event participant without a jurisdiction in the event
Fixes #11502

#11502 - Handle region requirement

---

sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationTemplate.json
sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationTemplateTelcom.json
sormas-e2e-tests/src/main/resources/demisJsonTemplates/labNotificationWithLoincTemplate.json
sormas-e2e-tests/src/main/resources/demisJsonTemplates/testLabRequestFile.json

Composition date in lab notification template JSON has changed to date prior receivedTime
Fixes #

qu-auto/SORQA-880 Stabilize "Test [DEMIS2SORMAS] Add new userflow for lab message processing [1]"

---

sormas-api/src/main/java/de/symeda/sormas/api/location/LocationDto.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/LocationHelper.java
sormas-api/src/test/java/de/symeda/sormas/api/utils/LocationHelperTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonCreateForm.java
sormas-ui/src/test/java/de/symeda/sormas/ui/caze/importer/CaseImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/contact/importer/ContactImporterTest.java
sormas-ui/src/test/java/de/symeda/sormas/ui/event/eventparticipantimporter/EventParticipantImporterTest.java

#8213 - Enter home address for existing persons

---

sormas-api/pom.xml
sormas-api/src/main/java/de/symeda/sormas/api/caze/classification/ClassificationExposureCriteriaDto.java
sormas-api/src/main/java/de/symeda/sormas/api/disease/DiseaseVariant.java
sormas-api/src/main/java/de/symeda/sormas/api/person/OccupationType.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java
sormas-api/src/main/java/de/symeda/sormas/api/utils/CsvStreamUtils.java
sormas-app/app/build.gradle
sormas-backend/pom.xml
sormas-base/pom.xml
sormas-keycloak-service-provider/pom.xml
sormas-rest/pom.xml
sormas-rest/src/main/java/de/symeda/sormas/rest/security/KeycloakIdentityStore.java
sormas-rest/src/main/java/de/symeda/sormas/rest/security/SormasIdentityStore.java
sormas-serverlibs/pom.xml
sormas-ui/pom.xml

Fixes #11963
Progress:
- `sormas-api`
- All Vaadin dependencies (`sormas-ui`)
- `gt-shapefile` (`sormas-backend`), see problem 3
Problems:
1. I needed to add more test dependencies explicitly for sormas-ui to keep EJB tests running (changing dependencies on sormas-backend from compile to provided meant there were not in the test classpath in sormas-ui any longer).
2. I struggled to move `resteasy` to serverlibs but was able to do it by updating it from 3.15.3 to 4.7.7 and exclude Jakarta APIs that had invalid POMs.
```
sormas-base\build.xml:88: Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'org.jboss.resteasy:resteasy-client:jar': Invalid JDK version in profile 'compile-java8-release-flag': Unbounded range: [9, for project …
```

#11963 compile dependencies to serverlibs

---

sormas-base/pom.xml
sormas-serverlibs/pom.xml

- Avoids conflicts with sormas-demis-adapter
Fixes #11963

#11963 Keep hapi-fhir as compile dependency

---

sormas-base/pom.xml

Reverts SORMAS-Foundation/SORMAS-Project#12146 because logback 1.4.x requires Jakarta 9.

Revert "Bump logback.version from 1.3.5 to 1.4.8 in /sormas-base"

---

sormas-backend/pom.xml
sormas-base/pom.xml
sormas-serverlibs/pom.xml

Fixes #12094 
Something odd I found: I did not have any regions. When I added "Niedersachsen", it showed up on the area where "Sachsen" is. After I added "Sachsen", "Niedersachsen" is shown correctly but "Sachsen" is now where "Sachsen-Anhalt" is. I assume it hase nothing to do with my ticket.

#12094 g-shapefile as serverlibs

---

sormas-base/pom.xml

Fixes problem described here https://github.com/jeremylong/DependencyCheck/issues/4539#issuecomment-1137183801

Disable dependency check oss index to workarround rate limit issue

---

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleQueryContext.java

Fixes #12940
This ticket needs to be merged AFTER https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12945 in order to use joins.getEventParticipantDistrict().

#12940 - Display the event participant's district

---

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestCriteria.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTest.java
sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/DeleteOldPathogenTestsAndSamplesTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleServiceTest.java
sormas-base/setup/sormas.properties

Change #13159 automatic soft delete negative covid tests and samples

---

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationCreationForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/selfreport/SelfReportDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java

#13157 - Disable Contact Management for RSV Cases

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/resources/captions.properties
sormas-api/src/main/resources/strings.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/surveillancereport/SurveillanceReportList.java

#13209 Update Person when case outcome is changed to "Deceased"

---

sormas-api/src/main/java/de/symeda/sormas/api/selfreport/processing/AbstractSelfReportProcessingFlow.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/selfreport/processing/SelfReportProcessingFLow.java

#13226 Add Manual Case Classification for Self-Report Processing

---

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/AbstractProcessingFlow.java
sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/labmessage/AutomaticLabMessageProcessorTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/processing/labmessage/AbstractLabMessageProcessingFlowTest.java

#13207 - [LUX] Automatic case processing for Pertussis cases

---

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/AbstractMessageProcessingFlowBase.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/AbstractProcessingFlow.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/EventValidationResult.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/ExternalMessageProcessingFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/PersonAndPickOrCreateEntryResult.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/PickOrCreateEventResult.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/PickOrCreateSampleResult.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/doctordeclaration/AbstractDoctorDeclarationMessageProcessingFlow.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/labmessage/AbstractLabMessageProcessingFlow.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/AutomaticLabMessageProcessor.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/labmessage/ExternalMessageProcessingFacadeEjbLocal.java
sormas-backend/src/main/java/de/symeda/sormas/backend/systemconfiguration/SystemConfigurationValueEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbMappingTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbUnitTest.java
sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/processing/labmessage/AbstractLabMessageProcessingFlowTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGrid.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/doctordeclaration/DoctorDeclarationMessageProcessingFlow.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/doctordeclaration/DoctorDeclarationSlider.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/doctordeclaration/DoctorDeclarationUiHelper.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/AbstractPhysiciansReportProcessingFlow.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportProcessingFlow.java
sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/EntrySelectionComponentForExternalMessage.java
sormas-ui/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java

Feature 13294 doctor declarations xml esante adapter

---

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java

The problem was cause by missing annotation on the ExternalMessage class. Field CaseClassification was not annotated with String enum type.
- Added correct annotation to the CaseClassification field in the ExternalMessage class.
Fixes #

#13337 - Fixed unable to process lab messages

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java
sormas-api/src/main/resources/captions.properties
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
sormas-ui/src/main/java/de/symeda/sormas/ui/caze/notifier/CaseNotifierSideViewComponent.java

Updated the `CaseDataView` to show the notification box even if there is no notifier.
In case there is no notifier, the notification
box will show a text message.
- `Captions`
- `captions.properties`
- `CaseDataView`
- `CaseNotifierSideViewComponent`
Fixes #13356

#13356 - Notification box will always be visible

---

sormas-api/src/main/java/de/symeda/sormas/api/systemconfiguration/SystemConfigurationValueDiseasesProvider.java
sormas-api/src/main/resources/enum.properties
sormas-api/src/test/java/de/symeda/sormas/api/systemconfiguration/SystemConfigurationValueDiseasesProviderTest.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationController.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationValueDynamicInput.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationView.java
sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss

Fixed issues with system configuration admin UI
Added ordering for the grouped checkbox values and allowed empty values:
- `SystemConfigurationValueDynamicInput`
- `SystemConfigurationValueDiseasesProvider`
- `SystemConfigurationController`
Fixed issue with reset filter not working:
- `SystemConfigurationView`
Added missing translations for system configuration:
- `enum.properties`
Fixes #13353

Bugfix 13353 changes system configuration admin UI

---

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java
sormas-api/src/main/java/de/symeda/sormas/api/systemconfiguration/SystemConfigurationValueDto.java
sormas-api/src/main/java/de/symeda/sormas/api/systemconfiguration/SystemConfigurationValueFacade.java
sormas-api/src/main/java/de/symeda/sormas/api/systemconfiguration/SystemConfigurationValueIndexDto.java
sormas-api/src/main/resources/strings.properties
sormas-backend/src/main/java/de/symeda/sormas/backend/systemconfiguration/SystemConfigurationValue.java
sormas-backend/src/main/java/de/symeda/sormas/backend/systemconfiguration/SystemConfigurationValueEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationValueEditForm.java
sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/system/SystemConfigurationValuesGrid.java

Introduced a description field, and update backend, API, and UI to support displaying and editing the description. :
- `SystemConfigurationValue`
- `SystemConfigurationValueDto`
- `SystemConfigurationValueFacade`
- `SystemConfigurationValueEjb`
- `SystemConfigurationValueIndexDto`
- `SystemConfigurationValueEditForm`
- `SystemConfigurationValuesGrid`
Updated SQL schema to add value_description column:
- `sormas_schema.sql`
Added i18n keys and English texts for email and SMS configuration value descriptions :
- `Strings`
- `strings.properties`

#13357 - Add description field to system configuration values

---

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java
sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/processing/doctordeclaration/AbstractDoctorDeclarationMessageProcessingFlow.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java
sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java
sormas-backend/src/main/resources/sql/sormas_schema.sql

Added fields for activities as case and exposures to external message:
- `ExternalMessageDto`
- `ExternalMessage`
- `ExternalMessageFacadeEjb`
Added handling of EPI data in `AbstractDoctorDeclarationMessageProcessingFlow`:
- creation of `Exposure` entries based on the `ExternalMessage.exposures` fields
- creation of 'ActivityAsCase` entries based on the `ExternalMessage.activitiesAsCase` fields' accordinlgy to the Pertussis documentation.
Fixes #

#13375 - Added EPI data hanling for doctor declaration processing
