sormas-ui/src/main/java/de/symeda/sormas/ui/document/DocumentListComponent.java
=> #5513 - Wrap file name

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/GeoLocationFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/InfrastructureBaseFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/area/AreaFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/community/CommunityFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/continent/ContinentFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/country/CountryFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/district/DistrictFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/region/RegionFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/subcontinent/SubcontinentFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/area/AreaFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/community/CommunityFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/district/DistrictFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/infra/InfrastructureValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/received/ReceivedDataProcessorHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ReceivedCaseProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/ReceivedEventProcessor.java
Ticks boxes in #6758 
If you review this, you should enable the hiding of white space changes in GitHub, InfrastructureValidator was not formatted correctly.
=> [#6758] unify local entitiy loading and rename functions

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactCriteria.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFollowUpGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactFollowUpGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java
=> Bugfix 6371 date range of follow up visits gets lost after opening contact or case

sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjbTest.java
=> #6327 fixed NPE and initialization of unspecifc custom enums + unit test

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/tasks/CreateNewTaskPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/TaskService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/Task.feature
=> #6747-FixTest-CreateTasks

sormas-e2e-tests/build.gradle, sormas-e2e-tests/gradle.properties
=> Fix for allure reports

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDataProvider.java
=> #6717 - Show campaign diagrams for all subtabs

sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/transformers/ImmunizationListEntryDtoTransformer.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventParticipantLink/EventParticipantListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentLayout.java
=> Bugfix 5828 restore changes lost by merging

sormas-ui/src/main/java/de/symeda/sormas/ui/action/ActionListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/document/DocumentList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/document/DocumentListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java, sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/label.scss
=> Bugfix 5513 long document names

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java, sormas-api/src/main/java/de/symeda/sormas/api/statistics/StatisticsCaseAttribute.java, sormas-api/src/main/resources/validations.properties, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseStatisticsFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/EventDocumentFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/QuarantineOrderFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/TestDataCreator.java
=> #6673: Make Person.sex required in backend and db

sormas-api/pom.xml, sormas-app/pom.xml
Fixes #6686 . Should be merged after the release of 1.64.0
=> #6686 increase the Java build version of SORMAS API to 1.8

sormas-e2e-tests/src/main/resources/configuration/properties/common.properties, sormas-e2e-tests/src/main/resources/configuration/properties/environment/test-performance.properties, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/RestAssuredClient.java
Created restassured logging enable/disable handle
=> #6808-DisableFrameworkAPILogging

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
=> disable overwrite follow-up when follow-up canceled or lost #6803

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java
=> fix travel entry conversion #6283

sormas-base/doc/keycloak.md
=> [#6825] fix link

sormas-e2e-performance-tests/SormasPoc.jmx, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CreateNewCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/AssertHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/ImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/SamplesDirectorySteps.java
Added fix for **Check a new case data**
Added fixes for performance failures
=> #6747-FixTest-CheckNewCase-Plus-PerformanceFix

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> #4660 - fix location fields overlap

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/CommunityUUIDs.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/CaseApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java
fixed test and refactored uuids usage
=> #6747-FixTest-SelectedSourceCase

sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/user/UserDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/util/DataUtils.java
=> Bugfix 6715 task reassignment android

sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SymptomService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java
Fixed test and added small improvement on how data is selected from dropdowns
=> #6747-FixTest-EditSymptoms

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
=> #6833 - fix merging of activityAsCase on case merge

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/immunizations/StatusValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/TaskService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/ImmunizationApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
Fixed test and added corrections
=> #6747-FixTest-TasksUi

sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> fix Android tests for API 24 to 29 #6714

sormas-e2e-tests/src/main/java/org/sormas/e2etests/ui/RemoteDriverFactory.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java
refactored browser's resolution
=> #6747-FixTests

sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java
=> [#6884] transaction for audit DB

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ReceivedCaseProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ReceivedContactProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/ReceivedEventProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/ReceivedEventParticipantProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ReceivedImmunizationProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ReceivedSampleProcessor.java
=> [#7071] EJBs need public default constructor

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
=> unlink deleted case in immunizations #7129

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ReceivedSampleProcessor.java
=> #7014 Fix pathogen test sharing for S2S

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #7068 Allow to store external data for a case - change column type to jsonb

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Task.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SampleService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/TaskService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
fixed tests from tasks and samples
=> #7131-FixFlakyUITests

sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantNewFragment.java, sormas-app/app/src/main/res/layout/fragment_event_participant_new_layout.xml, sormas-app/app/src/main/res/layout/fragment_person_edit_layout.xml
=> make sex mandatory for new eventparticipant #7143

sormas-api/src/main/java/de/symeda/sormas/api/caze/Vaccine.java, sormas-api/src/main/java/de/symeda/sormas/api/caze/VaccineManufacturer.java, sormas-api/src/main/java/de/symeda/sormas/api/utils/fieldvisibility/FieldVisibilityCheckers.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/vaccination/VaccinationEditFragment.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationsField.java
=> Bugfix 7149 vaccine visibility

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/Sormas2SormasDataValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/data/received/ReceivedDataProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/ReceivedDataProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ReceivedCaseProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ReceivedContactProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/ReceivedEventProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/ReceivedEventParticipantProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ReceivedImmunizationProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ReceivedSampleProcessor.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/data/received/ReceivedDataProcessorTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/data/received/Sormas2SormasDataValidatorTest.java
Fixes #7133 
All remaining processing logic is removed from validation logic.
=> [#7133] split validation from processing

sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/list/ImmunizationListActivity.java
=> initialize date filter fields #7171

sormas-app/app/src/main/res/layout/fragment_immunization_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_immunization_read_layout.xml
=> display immunization UUID #7168

sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/component/validation/ValidationHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/PersonContactDetailDialog.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/PhoneNumberValidator.java
=> Validate phone and email in Android #7157

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventJurisdictionPredicateValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJurisdictionPredicateValidator.java
=> #7189 - Fixed various NPEs when initializing New task popup

sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationEditFragment.java, sormas-app/app/src/main/res/layout/fragment_immunization_read_layout.xml
=> fix immunization positiveTestResultDate and recoveryDate #7158

sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantEditActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/read/EventParticipantReadActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewFragment.java
=> fix eventparticipant immunization #7167

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/AbstractCaseGrid.java
=> #7174 - Show outcome of case after filtering

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java
=> #7150 - Move the responsible user filter in the event directory filter form

sormas-api/src/main/java/de/symeda/sormas/api/immunization/MeansOfImmunization.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/read/ImmunizationReadFragment.java, sormas-app/app/src/main/res/layout/fragment_immunization_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_immunization_read_layout.xml
=> fix immunization fields visibility and update #7176 #7164

sormas-base/setup/sormas.properties
=> #7208 Update `central.location.sync` property description

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
=> # 7268 set specimen condition based on lab message

sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-app/app/src/androidTest/java/de/symeda/sormas/app/EventBackendTest.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/event/EventDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/event/EventParticipant.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditFragment.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventServiceTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> Feature 7234 event participant jurisdiction adjustments

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseListCriteriaBuilder.java
=> Add person UUID in CaseListCriteriaBuilder #7254

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java
Added small fixes for: Source case selected for contact and Change the source case contact and then delete
=> #7131-FixFlakyUITest

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java
=> Add person UUID in ContactListCriteriaBuilder #7254

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java
=> #7229 - Fix NPE when selecting disease variant

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureConfigurationCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/feature/FeatureConfigurationFacadeEjb.java
=> #7237 search parameter on the line listening criteria

sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java
=> skip person selection if immunization person already exists #7160

sormas-ui/src/main/java/de/symeda/sormas/ui/hospitalization/HospitalizationForm.java
=> Bugfix 7227 description box not disabled on hospitalization tab

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationListCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/vaccination/VaccinationListEntryDto.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjbTest.java, sormas-rest/src/main/java/de/symeda/sormas/rest/ImmunizationResource.java, sormas-ui/src/main/java/de/symeda/sormas/ui/ControllerProvider.java, sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/SormasFieldGroupFieldFactory.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/VaccinationsField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListReferenceData.java
=> #7105 - Added reduced immunizations to the frontend

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
=> #7131 fix flaky UI tests

sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/immunization/edit/ImmunizationNewFragment.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java
=> no status update on open edit form #7164

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
=> #7163 - Use distinct when counting search results for contacts

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #7355 - Hide date of investigation when investigation status is pending

sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/CustomExportController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/ExportConfigurationsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/customexport/ExportConfigurationsLayout.java
=> #7019 - Fix caption title for export window

sormas-e2e-tests/customReports/data/results.txt, sormas-e2e-tests/scripts/runPagesMeasurements.sh, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java
Updated data to be handled only within existent text file without deleting it.
=> #6921-Fix_Custom-Report

sormas-e2e-tests/src/main/java/customreport/template/customReport.txt
added correction in html template
=> #6921 fix custom report

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java
=> Bugfix 7172 skip edit person popup

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjbTest.java
=> #7406 - Rewrote queries to update vaccination statuses

sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationList.java
=> #7415 - Fixed vaccine list when accessing vaccinations from persons

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleList.java
=> #7413 - Show ep samples for national users with limited disease

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/SourceContactListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/CaseEpiDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractDetailView.java
=> Bugfix 7425 confirm navigation

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java
=> #7430 trigger diseaseVariantFieldUpdate when adding fields

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListEntry.java
Fixes #7431 
Title says it all...
=> [#7431] remove unused top right layout

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/caselink/CaseListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/contactlink/ContactListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/immunizationlink/ImmunizationListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/travelentrylink/TravelEntryListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/PaginationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/event/EditSideComponentFieldEvent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/event/EditSideComponentFieldEventListener.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListEntry.java
=> Bugfix 7404 confirm navigation

sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGridFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DateComparisonValidator.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DateTimeField.java
=> date time filter for labmessage date #7426

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
=> #7449 - do not allow linking of deleted cases

sormas-api/src/main/java/de/symeda/sormas/api/user/UserFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
=> #6909 @notnull bug fix

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseValidator.java
=> #7250 - extend hospitalization fields validation on mobile app

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/popupmenu/PopupMenu.java
=> Bugfix 7462 event overview overlapping UI

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java
=> #3815 - Add quarantine filters for cases

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java
=> #3815 - Added field visibility checkers to CAseFilterForm

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> Bugfix 7523 vaccination table missing snapshot column

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/labmessage/LabMessageServiceUnitTest.java
=> Bug 7518 screen disturbances when filtering for unprocessed lab messages

sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/labmessage/LabMessageServiceUnitTest.java
=> Feature 6981 update

.github/workflows/skip_required_status.yml
Fixes #7543 
@MateStrysewske Please merge after the build failures on `development` are resolved.
=> [#7543] skip mergefreeze on openAPI push

.github/workflows/skip_required_status.yml
Fixes #7543 
Taking a closer look the docs, the are rather specific that the name must match so try again.
=> [#7543] remove name

.github/workflows/ci.yml
=> [#7543] fix typo

.github/workflows/ci.yml
Fixes #7543 
It's really time for :christmas_tree: holidays now :D
=> [#7543] cp directory

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactListCriteriaBuilder.java
=> #7565 - Sort contacts by age and sex in details view

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/ContactsDashboardPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/SurveillanceDashboardPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/contacts/ContactsDashboardSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/surveillance/SurveillanceDashboardSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature
Fixes #7472 create automated tests to cover data counting in dashboard directories
adds automated E2E/UI tests to test Dashboard counters for Surveillance Dashboard and Contacts Dashboard
=> #7472 create automated tests to cover data counting in dashboard directories

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/api/Person.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/CaseService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/ContactService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/ContactsLineListingService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/PersonService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/UserService.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/api/PersonApiService.java
refactored POJO service classes
=> #7444-Refactor-Email-Generation

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonFilterForm.java
=> #7241 - Person directory - does not stay selected

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbUserFilterTest.java
=> #7514 - Exclude inactive users from entity-specific user lists

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> Feature 7064 directly enter the home address on case creation form

sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/ExternalJournalFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryConfig.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/PatientDiaryClient.java, sormas-base/setup/sormas.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java
=> #6478 add frontend token retrieval

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
=> #7467 - Fixed initial point of entry list being empty

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/caze/read/CaseReadFragment.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #5418 - Allow all sexes to have pregnancy attributes

sormas-e2e-performance-tests/README.md, sormas-e2e-tests/README.md
Update readme files for automation framework and performance
=> #7602 frameworks read me update

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> #7529 - Conversion of multiple entities pop-up does not get triggered

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> #7631 - Refactor filters, add default filter to sample list

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java
=> #7310 set eager data provider in reload()

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessagesView.java
=> #7310 always update status filter buttons

docs/SERVER_UPDATE.md
=> #7575: Documented how to Migrate to new Payara Server

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/PathogenTestedDisease.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/EditSamplePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/PathogenTest.feature, sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java
=> pathogen test

sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java
=> #7310 enable single unassign

docs/TROUBLESHOOTING.md
=> #4601: Documented how to deal with quarantined payara module war-util.jar

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/DiseaseStatisticsComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/components/statistics/summary/DiseaseSummaryComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/surveillance/components/statistics/summary/FatalitiesSummaryElementComponent.java
=> Bugfix 7464 dashboard overlapping

sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionIndexDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/transformers/EventActionIndexDtoReasultTransformer.java
=> Bugfix 7701 duplicate rows in actions directory

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> small event fix

sormas-app/app/src/main/res/layout/dialog_root_three_button_panel_layout.xml, sormas-app/app/src/main/res/values/dimens.xml
=> #7480 - [Android App] Hospitalization | Buttons are overlapping

sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/EpiDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/NullableOptionGroup.java, sormas-ui/src/main/webapp/VAADIN/themes/sormas/global.scss
=> Bugfix 3659 text cutoff in epidemiological data view

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/mock.feature
added missing steps causing allure failures
=> #7747-Fix-Allure-Report

sormas-api/src/main/java/de/symeda/sormas/api/dashboard/CaseDataTypeDashboardCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/dashboard/SurveillanceDashboardCriteria.java, sormas-rest/src/main/java/de/symeda/sormas/rest/DashboardResource.java
=> #7694 endpoints for map

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
Fixes #7752 
Interestingly, I could not reproduce the failure locally, but if IIRC I saw this error last week in one of my branches.
IDE showed some warnings that missing array tape might cause trouble, so refactored the call site a little bit.
While I was at it, I also fixed some low hanging warnings.
Cheers
=> #[7752] fix warning about array type inference

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/CaseClassification.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
added fixes based on jenkins findings
=> #7677 fix tests for removed fields

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java
=> SORQA-2 spinner fix

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java
=> SORQA-3 spinner fix

sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormData.java
=> #7746 Exporting database campaign form data is missing the first row

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/RouteValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/TreatmentValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/TherapyPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pojo/web/Therapy.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/TherapyService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditTherapySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> SORQA-36 SORDEV 5527

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java
=> SORQA-3 jenkins-fix

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> SORQA-34 jenkins-fix

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/common/messaging/MessageContents.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java
=> Add a specific message for observer users in task notifications #7756

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> #7825 update lab field required status

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationCreationForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSearchField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java
=> Feature 6599 person search

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java, sormas-ui/src/main/java/de/symeda/sormas/ui/UiUtil.java
=> (#7811) Dashboard feature config

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
=> #7818 - Do not duplicate follow-up messages

sormas-rest/src/main/java/de/symeda/sormas/rest/EntityDtoResource.java
=> #7703 - do not use jdk.internal package for empty string

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
=> SORQA-51 refactor of Edit Person

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactPersonSteps.java
=> SORQA-51 refactor

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
=> WebDriverHelpers method check

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsController.java
=> #6599 - fix creation of new event participant

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/java/de/symeda/sormas/api/info/InfoFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java, sormas-api/src/main/resources/captions.properties, sormas-api/src/main/resources/enum.properties, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java, sormas-backend/src/main/java/de/symeda/sormas/backend/info/FieldData.java, sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExportEntityName.java
=> #7679 Data Dictionary with Data Security Information

sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java
=> WebDriverHelpers clearAndFillInWebElement fix

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
=> #7824 - Clear home address fields when deselecting it

sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/utils/checkHistoryTables.sql
=> #7113 Add missing history tables

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/TestReportDto.java
Fixes #
Part of https://git.vitasystems.dev/sormas/sormas-demis-adapter/-/merge_requests/55
=> #11 [DEMIS2SORMAS] Automatically prefill PathogenTest.testType

sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/SormasFieldGroupFieldFactory.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/MultiSelect.java
=> Modify the Observers field inside the Task form #7644

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
=> Test scenario for adding follow-up for a contact

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/ContactFilters.feature
=> Added test scenario for contact directory page filters

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsFilterForm.java
=> #7826 - Populate day of birt in event participant filter form

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/TestReportDto.java
=> #7913 fix I18N_PREFIX

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/ClinicalCourseTabCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/ClinicalCourseVisitService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/ClinicalCourseTabCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> Test scenario for Fill Clinical course tab

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
https://jira.sormas-tools.de/browse/SORQA-14
=> Added missing tests for creating samples

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java
=> #7798 - Don't iterate over null lists

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
=> Use parameterized queries in databasehelper

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationCreationForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java
Fixes #7743
This is a quick fix of the issue for the current release. A refactoring as described in #7935 will provide a better solution for the issue.
=> hide passport and health Id fields #7743

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/PersonDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/PersonContactDetailsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
https://jira.sormas-tools.de/browse/SORQA-50
=> Added a test for error messages when editing a Person

sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java
=> #7784 - discard override checkbox on immunization discard

sormas-backend/src/main/java/de/symeda/sormas/backend/common/CoreAdo.java, sormas-backend/src/main/resources/sql/sormas_schema.sql
…don't have this flag mandatory yet
Fixes #7246
=> #7246 - fill contact and EvP archived flags

sormas-api/src/main/java/de/symeda/sormas/api/customizableenum/CustomEnumNotFoundException.java, sormas-api/src/main/java/de/symeda/sormas/api/customizableenum/CustomizableEnumFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/labmessage/TestReportDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/TestReport.java, sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/TestReportFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/FollowUpTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/HospitalizationTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/FollowUpVisitService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/FollowUpStep.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/HospitalizationTabSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseHospitalization.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageMapper.java, sormas-ui/src/test/java/de/symeda/sormas/ui/labmessage/LabMessageMapperTest.java
=> Added scenario [SORDEV 5570] to Event.feature

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
=> #7957 [Custom Case Export] Hide 'Education' field in German systems

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-rest/src/main/java/de/symeda/sormas/rest/PersonResource.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java, sormas-ui/src/test/java/de/symeda/sormas/ui/caze/importer/CaseImporterTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/contact/importer/ContactImporterTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/event/eventparticipantimporter/EventParticipantImporterTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/event/importer/EventImporterTest.java
=> #7674 getSimilarPersons

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java
=> #7787 - Discard facility fields

sormas-app/app/src/main/java/de/symeda/sormas/app/rest/ImmunizationFacadeRetro.java
=> #7987 - Immunization synchronization does not work (backport of #7980)

sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignService.java
=> Bugfix 7982 campaign synchronization not working

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/common/DefaultEntitiesCreator.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/outbreak/OutbreakOverviewGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/sharedinfo/SharedInfoField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/hospitalization/PreviousHospitalizationsField.java
=> #7910 - Fix translations for table headers in data dictionary

sormas-api/src/main/java/de/symeda/sormas/api/externaljournal/PatientDiaryConfig.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/PatientDiaryClient.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java, sormas-base/setup/sormas.properties, sormas-rest/src/main/resources/workflow-documentation.properties
Fixes [#24](https://github.com/hzi-braunschweig/SORMAS-Security/issues/24).
=> #24 configurable token lifetime

sormas-backend/pom.xml, sormas-base/pom.xml
=> remove freemarker dependency #7978

sormas-base/pom.xml
- fop-events 2.6 -> 2.7
- xmlgraphics-commons 2.4 -> 2.7
Fixes #7978
=> #7978: Update xmlgraphics

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-base/setup/sormas.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/map/LeafletMap.java, sormas-ui/src/main/webapp/VAADIN/map/leaflet-connector.js
=> #7792 Make tile server used for map configurable

sormas-api/src/main/java/de/symeda/sormas/api/person/SimilarPersonDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CustomizableGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/SormasGrid.java
=> Feature 7815 hide grid columns

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java
=> reset place of stay on discard #7783

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
=> #8060 - Reset investigation dates when status is changed to pending

sormas-api/pom.xml, sormas-api/src/main/java/de/symeda/sormas/api/utils/DataHelper.java, sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java, sormas-api/src/main/resources/version.txt, sormas-api/src/test/java/de/symeda/sormas/api/utils/InfoProviderTest.java, sormas-base/pom.xml, sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java
Fixes #7786, see visual change here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7786#issuecomment-1047059711
=> #7786 integrate git commit in version info

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonFilterForm.java
=> #8044 - Reset community field when region is changed

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryFilterForm.java
=> #7451 - show more filters as default on travel entry filter form

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java
=> #7681 set minimum width for process column

sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/PatientDiaryClient.java, sormas-rest/src/main/resources/workflow-documentation.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExternalJournalUtil.java
=> #7964 Don't default to backend tokens for frontend calls

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntriesView.java
=> #7451 - remove more dropdown for entering bulk edit on travel entries

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/PersonDependentEditForm.java
=> Bugfix 8098 error when selecting existing person in case creation

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java, sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java
=> feature property free task editing #7960

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> #8090 Update disease variant prompt navigates to case when only save was selected

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
=> Bugfix 8102 person search no restrictions

sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> #7787 - Do not trigger facility validation on discard

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseValidator.java
=> Bugfix 8094 intensive care unit dates reversed

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
=> #8105 - Set disease variant when converting travel entry to case

sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java
=> show vaccination selector #8099

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java
=> #7247 - CoreAdo: Introduce "end of processing date"

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
=> #8105 - Set disease variant details when converting travel entry to case

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/MergeContactsView.java
=> #8016 - Fix heading

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/immunizations/CreateNewImmunizationPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/immunizations/ImmunizationsDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/CreateNewSamplePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/SamplesDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/CaseService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/CreateNewImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/ImmunizationDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Pathogen.feature
=> fixes after rebase

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java
=> fixed #8159

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sharerequest/SormasToSormasShareRequestFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/sharerequest/SormasToSormasShareRequestFacadeEJB.java, sormas-rest/src/main/java/de/symeda/sormas/rest/ShareRequestResource.java
=> #7946 shareRequest endpoints (getIndexPage, getByUuid)

sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataView.java
=> #8133 - Save travel entry before creating a case

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
=> #8168 - fix saving sample with pathogen test for case & contact

sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature
Removed step which failed because of lack of data in combobox
=> fix for test regarding filtering

sormas-api/src/main/resources/enum.properties
=> #2802: Added caption

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> Bugfix 8186 location popup case creation

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupList.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupListComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupListEntry.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponent.java
=> Bugfix 8131 a problem has occured when trying to save an event

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java
=> #8184 - Clear home address checkbox when selecting a person

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
=> #8033 - Change travel entry reference when merging cases

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java
=> #8065 UI validation for create new sample in lab message processing does not correctly update to valid

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java
Refactored login method
Stable passes:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/87/
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/86/
=> #8205-RefactorLoginMethod

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/ContactFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/EpidemiologicalDataCase.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/EventFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/LineListing.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Pathogen.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> #8212-IgnoreFailingTests

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/RiskLevelValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/cases/epidemiologicalData/TypeOfPlace.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/EventApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
Stable fix
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/100/
=> #8212-FixFailingTests-API-Tasks

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/TherapyPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/ContactService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/api/EventApiService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditTherapySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/EventFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
FIxes:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/110/allure/
=> #8212-FixFailingTests-DocumentsUploadFixes

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/TherapyPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/AssertHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/ContactFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/121/allure/
=> #8212 fix failing tests and correct loading spinner method failure

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #8229 - Change travel entry person on merge

sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java, sormas-api/src/test/java/de/symeda/sormas/api/utils/InfoProviderTest.java
=> #8286: Build history url if git checkout was done with SSH

docs/SERVER_SETUP.md, sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-backend/pom.xml, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/LogSink.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java, sormas-base/setup/audit-logback.xml, sormas-base/setup/sormas.properties
=> [#8030] add audit logger

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/PresentCondition.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/ImmunizationService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/UserService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/surveillance/SurveillanceDashboardSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/EditImmunizationPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/ImmunizationDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/pagesperformance/PagesLoadMeasurements.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
Users stable tests:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/190/allure/
Dashboard stable tests:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/184/allure/
Sample stable test:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/193/allure/
Fixed test: **Check Filters on Person page work as expected**
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/201/allure/
=> #8212-FixFailingTests - fix tests from dashboard, immunization, samples, filters, users

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> regresion test

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/FollowUpVisitService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/FollowUpStep.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFollowUpVisit.feature
=> stabilisation CaseFollowUpVisit

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> regression test - sorqa-75

sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/EventParticipantSection.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantEditActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/edit/EventParticipantEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/read/EventParticipantReadActivity.java, sormas-app/app/src/main/java/de/symeda/sormas/app/event/eventparticipant/read/EventParticipantReadFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/PersonContactDetailDialog.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/PersonFragmentHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/read/PersonReadFragment.java, sormas-app/app/src/main/res/layout/fragment_event_participant_edit_layout.xml, sormas-app/app/src/main/res/layout/fragment_event_participant_read_layout.xml
=> #7881 - Moved event participant person to individual fragment

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantDataView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListComponent.java
=> Bugfix 8193 two positive test results of different diseases duplicates the sample

sormas-rest/src/main/java/de/symeda/sormas/rest/security/KeycloakHttpAuthenticationMechanism.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
=> #8210 Fix disease variant field not being displayed

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/PointOfEntryValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/entries/EditTravelEntryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/CreateNewTravelEntrySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntry.feature
quick simple fix for data parse for task management filter tests
=> Qu auto/task management fix

sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java
=> #8111 - Clear Date of symptom onset when there are no symptoms selected

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> #8191 - Save associated case after updating a sample

sormas-api/src/main/resources/enum.properties
=> #8155 - Add translation for deletion configuration

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> Bugfix 8200 case is linked when adding a positive test result

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractDomainObject.java
=> Fixed SQL recursion introduced by #7323

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java
Fixes #8319
~To be merged after testing~
Tested together with @abrudanancuta and got her approval
=> #8319 Prefill home address

sormas-base/setup/sormas.properties
=> #7981 add warning boolean parsing

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
Fixes #8170 
Should be merged after the release of 1.69.0.
=> #8170 refresh view

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
=> #8272 - Remove warning message if validation is true

sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java
=> #8111 - Preserv symptom date if it was set

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/contactfield/ContactLineField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/layout/LineListingLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/sharedinfo/SharedInfoField.java
=> fix type of contact in line listing #7829

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
enabled tests and added corrections
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/337/allure/
=> 8379-EnableDELoginTests

sormas-backend/src/main/java/de/symeda/sormas/backend/info/InfoFacadeEjb.java
Reverts hzi-braunschweig/SORMAS-Project#8394
=> Revert "Feature/8097 show entities name"

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DateComparisonValidator.java
=> fix date validation in contact form #8122

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonContactDetailsField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/SormasFieldGroupFieldFactory.java
=> confirm leave after contact details edit #8290

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/sampleLink/SampleListEntry.java
=> #8404 - Display test time in sample card

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #7656 added index on externalshareinfo (caze_id, creationDate)

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java
=> #8247 - Mark fields as required

sormas-ui/src/main/java/de/symeda/sormas/ui/task/BulkTaskDataForm.java
=> #8326 - Make task assignee mandatory in bulk edit mode

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-rest/src/main/java/de/symeda/sormas/rest/ContactResource.java
=> #8134 gwt detailed contacts

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
=> #8301 Dupilcate uuids returned for events endpoint

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java
=> fix email and phone validator #7935

sormas-backend/src/main/java/de/symeda/sormas/backend/util/DtoHelper.java
=> #8315 - Handle Strings and booleans when merging

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonCreateForm.java
=> #8391 Populate home address when processing lab message

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/components/linelisting/LineListingLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/layout/LineListingLayout.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/linelisting/model/LineDto.java
=> Bugfix 8051 duplicate case not visible in directory

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> Bugfix 8191 update followup date

sormas-rest/src/main/java/de/symeda/sormas/rest/DiseaseConfigurationResource.java
=> #6931 get disease variant endpoint

sormas-e2e-tests/build.gradle, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/FacilitiesTabPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/pojo/csv/FacilityCSV.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/facilities/ConfigurationFacilitiesSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/facilities/FacilityTableColumsHeadres.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Facility.feature, sormas-e2e-tests/uploads/testFile.csv
=> Qu auto/sorqa 118

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java, sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantExportDto.java, sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java, sormas-api/src/main/java/de/symeda/sormas/api/person/PresentCondition.java, sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java, sormas-app/app/src/main/res/layout/fragment_person_edit_layout.xml, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationCreationForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/components/TravelEntryCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldHelper.java
Fixes #8072 
Many of the changes made here should be much more generic. Due to the high time pressure, it was decided to have an implementation for only the fields described in the ticket. This is faster to get merged and has a lower risk of breaking anything else.
=> Change 8072 hide buried within person present condition for covid 19

sormas-backend/src/test/java/de/symeda/sormas/backend/common/StartupShutdownServiceTest.java, sormas-backend/src/test/resources/testcontainers/Dockerfile
=> Fix history tables check unit test

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
=> Qu auto/sorqa 51 stabilization

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionFilterForm.java
=> #8388 clear validation errors

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SymptomService.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-100
=> Replaced dot with a comma which fixed the failing test

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
Fixes #7935 (findings from testing)
=> fix test findings #7935

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
=> #2804 fixed user roles join type def

sormas-api/src/main/java/de/symeda/sormas/api/user/UserRole.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/report/WeeklyReportService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/User.java
=> 2804 revert rest user changes

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
Fix conversion from contact to case
Fixes #7935
=> fix contact to case conversion #7935

sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature
https://jira.sormas-tools.de/browse/SORQA-133
=> Removed steps related to disease no longer present in DE version

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupList.java
=> Reinit the Events view when navigating to it from the Event Group view #7754

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/MultiDayContactField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/components/linelisting/contactfield/ContactLineField.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DateComparisonValidator.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/multidayselector/MultiDaySelectorField.java
=> fix contact date validation #8122

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java
Fixes #8500 
Minor change for now, we will come back and enforce `https` for certain URLs in the next step once I have an answer from NL.
=> [#8500] validate all URLs in config file

sormas-backend/src/test/java/de/symeda/sormas/backend/common/StartupShutdownServiceTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFilterForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> #8072 Update present condition from filters and person edit forms

sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
Fixes #8500 
@StefanKock FYI :rocket:
=> [#8500] remove map tiles URL from validation

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #8461 - Fix NPE when selecting surveillance officer

sormas-ui/src/main/java/de/symeda/sormas/ui/ActivityAsCase/ActivityAsCaseForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/exposure/ExposureForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/location/LocationEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FieldHelper.java
=> Bugfix 7838 archive facilities not displayed

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> #8052 fix value for burial fields

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/multidayselector/MultiDaySelectorField.java
Fixes #8122
finding from https://github.com/hzi-braunschweig/SORMAS-Project/issues/8122#issuecomment-1077935261
=> fix report date validation in contact line listing #8122

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjb.java
=> fix latest pathogen test in sample sidebox (case data view) #8457

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> Bugfix 8605 permanent sample deletion error

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> #8601 - do not use pseudonymization for journal person

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
=> #8592 fix cron authorization issues

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGrid.java
=> [#8589] give button enough space

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/CaseOutcome.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-138
=> Added German version of the case tab test

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> #8643 - delete case visits

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> #8633 Values related to present condition are not saved

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/HealthConditionsMapper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
=> #8638 Some External Journal API Endpoints can not be used by REST_EXTERNAL_VISITS_USER

sormas-api/src/main/resources/enum.properties
=> #8593 - Added missing translations for some user roles

sormas-e2e-tests/src/main/java/org/sormas/e2etests/envconfig/manager/EnvironmentManager.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditContactsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/commonSteps/ResponseChecksSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/api/Api.feature
added checks for response and json config file
=> 8625-AddjsonConfigurationValidations

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> Bugfix 8550 followup date in case created from contact

sormas-rest/src/main/java/de/symeda/sormas/rest/security/KeycloakHttpAuthenticationMechanism.java
=> #8661 NullPointerException in KeycloakHttpAuthenticationMechanism when calling the rest api with admin user

sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/RiskLevelValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/SourceTypeValues.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/cases/epidemiologicalData/TypeOfPlace.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/EventFilters.feature
https://jira.sormas-tools.de/browse/SORQA-137
=> Added German version of Event Directory Filter test

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/615/allure/
=> Fix for import and export case contact

sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
As requested by Alwin
https://jira.sormas-tools.de/browse/SORQA-155
=> Ignored failing test

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactPersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditPersonContactDetailsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/PersonContactDetailsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
https://jira.sormas-tools.de/browse/SORQA-110
=> Protection from server performance issues

sormas-cargoserver/pom.xml, sormas-cargoserver/src/main/resources/domain/domain.xml, sormas-cargoserver/src/main/resources/domain/logback.xml
Fix logging and debug for cargo server. This PR does not fix issue #8357, so do not close the issue.
Fixes #8357
=> fix cargoserver logging and debug #8357

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/CaseService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/EventFilters.feature
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/667/allure/
=> 8705-FixEventFiltersTest

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java
Stabilize "Check the edit of task from Case"
=> Stabilize "Check the edit of task from Case" sorqa-144

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventJurisdictionPredicateValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
Fixes #8637 for hotfix (replaces #8685)
=> #8637 reduce select complexity

sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/ExtendedH2Dialect.java, sormas-backend/src/test/java/de/symeda/sormas/backend/H2Function.java, sormas-backend/src/test/resources/META-INF/persistence.xml, sormas-base/pom.xml, sormas-ui/src/test/java/de/symeda/sormas/ui/AbstractBeanTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/ExtendedH2Dialect.java, sormas-ui/src/test/java/de/symeda/sormas/ui/H2Function.java, sormas-ui/src/test/resources/META-INF/persistence.xml
=> #8028: Update h2database

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java
=> Specimen condition should not be mandatory

sormas-e2e-performance-tests/SormasPoc.jmx, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java
=> 8710-ImplementEnvironmentValidation

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/surveillancereport/SurveillanceReportService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/IterableHelper.java, sormas-backend/src/test/java/de/symeda/sormas/backend/util/IterableHelperTest.java
=> #7971 Removed superfluous list size checks that executeBatched handles

docs/TROUBLESHOOTING.md, sormas-api/src/test/java/de/symeda/sormas/api/i18n/I18nConstantGenerator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/performance/PerformanceLogAnalysisGenerator.java, sormas-backend/src/test/resources/performance/exampleApplication.debug
This is not the final fix for #8357, please make sure not to close the issue when reviewing!
Fixes #8357
=> performance log analysis #8357

sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleReferenceDto.java
=> #8725 - Add parantheses to related entity uuids

sormas-api/src/main/java/de/symeda/sormas/api/user/UserFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserFacadeEjbTest.java
=> #8681 restore, document and test more relaxed user getters

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/EpidemiologicalDataCase.feature
=> Sorqa-172 Make facility selection on LocationForm more intuitive

sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleReferenceDto.java
=> #8725 - Remove warnings

sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java
=> #8753 fix duplicate key error on case directory

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ChooseSourceCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-174
=> Added test for creating a contact with source case

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
=> Clinicians cannot create samples for contact

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/EpidemiologicalDataCase.feature
=> Sorqa-170 Improve exposure table display

sormas-api/src/main/resources/strings.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/multidayselector/MultiDaySelectorField.java
=> Bugfix 8581 fix date validations

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #8730 - Update follow up for cases created from event participants

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java
=> #8312 - fix duplication of automatic message on contact merge

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java
Fixes https://github.com/hzi-braunschweig/SORMAS-Project/issues/8738#issuecomment-1092906304
=> Disable conversion of contact to case when user has no contact edit right

sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractDeletableAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/Contact.java, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/QueryHelper.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/labmessage/LabMessageServiceTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleServiceTest.java
=> Feature 8293 automatic permanent deletion

sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java
=> [#8787] remove diamond operator

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactReferenceDto.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbPseudonymizationTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbPseudonymizationTest.java
=> #8750 - Display uuid in contact caption

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/TravelEntryDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature
Date format adjustement for test-de
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/723/allure/
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/722/allure/
=> Fix for date format

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/MergeContactsGrid.java
=> #8805 - Add minimum width to button columns

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties
=> #8647 - Translations for location fields

sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardFacadeEjb.java
=> Add missing annotations to fix CI Builds

sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java, sormas-api/src/main/java/de/symeda/sormas/api/audit/AuditLoggerFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/audit/Constants.java, sormas-api/src/test/java/de/symeda/sormas/api/ArchitectureTest.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerInterceptor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java, sormas-rest/src/main/java/de/symeda/sormas/rest/SormasToSormasResource.java, sormas-rest/src/main/java/de/symeda/sormas/rest/audit/RequestAuditFilter.java, sormas-rest/src/main/java/de/symeda/sormas/rest/security/s2s/oidc/ClientCredentials.java, sormas-rest/src/main/java/de/symeda/sormas/rest/security/s2s/oidc/S2SAuthFilter.java
Fixes #8021 
Failed logins will be handled separately.
=> [#8021] add rest audit logging

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractDetailView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DetailSubComponentWrapper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DirtyStateComponent.java
=> #8752 - Don't navigate when form contains errors

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewActivity.java
=> #8338 - Skip person duplicate check on ep conversion

sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitJoins.java
=> #8688 minor refactoring

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/CommunitiesSteps.java
=> SORQA-194 fix SORDEV-8050

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #8295 - Remove deleted lab messages from test reports

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
=> #8807 allow relevant method calls with EXTERNAL_VISITS right

sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
Fixes #8820
Additionally fixed:
POE National User was able to create case, but could not open them due to even_view restriction
POE National User got an error when accessing the dashboard because of the event_view restriction
=> Allow POE users to create cases

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> #8832 - Assign case jurisdiction to contacts

sormas-api/src/main/java/de/symeda/sormas/api/audit/AuditLoggerFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java, sormas-rest/src/main/java/de/symeda/sormas/rest/security/MultiAuthenticationMechanism.java
Fixes #8815 
Fixes #8790
~~Do not merge yet, blocked on #8021 and #8816. Needs rebase and branch change.~~
=> [#8815] rest failed login audit

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/CreateNewTravelEntrySteps.java
fix for "inaktiv". I attach failing jenkins job log because of issue with "Special characters are displayed as question mark " but fix works
=> SORQA-161 fix SORDEV-8268

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/travelentry/services/TravelEntryService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> #8847 - Include deleted contacts and event participants

sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java
Fixes #8902 
Tested, everything works as expected.
=> [#8902] fix wrong annotation

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventGroupController.java
=> #8915 - Hide delete button

sormas-base/doc/keycloak.md, sormas-base/setup/keycloak/audit-logging/standalone-ha-logging.cli, sormas-base/setup/keycloak/audit-logging/standalone-logging.cli
=> [#8891] add keycloak event logging

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/pagesperformance/PagesLoadMeasurements.feature
=> 8928-UpdateNavBarSteps

sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageService.java
=> #8909 fix filter

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java
SORDEV-5490 fix. Sometimes test fails because of duplicated peron. Fix detecting 'Pick or create person' popup notification
=> SORQA-202fix

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java
Weak performance, added sleep before waiting for popup after created positive test result, tested several times
=> Qu auto/sorqa 204fix

sormas-backend/src/test/java/de/symeda/sormas/backend/performance/PerformanceLogAnalysisGenerator.java
Fixed: Division by zero if method call count is 0.
Fixes #8357
=> bugfix unfinished method count #8357

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
Fixes #8936.
I did not move the logic to `AbstractDeletableAdoService` despite my proposal in **Problem 1b** because there is a lot of shared logic with `getAutomaticDeletionInfo`.
=> #8936 automatic deletion with tx split

sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventGroupFacadeEjbTest.java
=> #8851 fix delete deadlock

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> 8814- fix the view of the cases in case of having casefollowup enabled

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestFacadeEjb.java
=> #8882 - Platelets fills and updates prothrombinTime in additional tests

sormas-api/src/main/resources/enum.properties
=> #8593 add english i18n properties

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactsLineListingPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactsLineListingSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
Create automated test to create new Contact using Line Listing and select Source Case
=> #7768 create new Contact using Line Listing and select Source Case

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactsLineListingPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactsLineListingSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
Test to validate selected Source Case data is correctly displayed while creating a new Contact via Line Listing feature
=> #7769 valid source case while creating a new contact via line listing

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchivingController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java
=> #8871 - Prevent archiving if date of report is a future date

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CreateNewCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
SORDEV-8048 - Test fixed and splited
=> SORQA-217 - SORDEV-8048 fix and split

sormas-api/src/main/java/de/symeda/sormas/api/utils/CsvStreamUtils.java
=> #9081 Avoid fetch of known empty step if current did not exceed stepSize

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseLineListingSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewVisitSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/CreateNewImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/reports/WeeklyReportsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/925/allure/
=> #8203-Remove-Useless-WaitForPageToLoad

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/951/allure/#suites/ba64af4344a5d1b16948f67eae90e934/a644c2db42ec9ead/
=> Fix for lacking steps, removed useless waitForPageLoaded()

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
=> #8747 Only do event participant join when needed for jurisd. level

sormas-api/src/main/java/de/symeda/sormas/api/labmessage/LabMessageDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGridFilterForm.java
=> #9025 fix type filter values

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleJurisdictionPredicateValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> #8610 avoid sample jurisdiction id joins

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #9118 - Fix mandatory Facility name and description bug

sormas-e2e-tests/customReports/pagesMeasurements/data/results.txt, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java
=> #9114-UpdatePagesLoadinTimeTests

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/993/allure/#suites/79882de23edbfe835172427429a21275/5276a367f14c886f/
=> Replaced click with double click to prevent failures because of performance issues

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePersonPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-230
=> Added test for the ability of all sexes to be pregnant

sormas-api/src/main/java/de/symeda/sormas/api/ConfigFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/RequestContext.java, sormas-api/src/main/java/de/symeda/sormas/api/RequestContextHolder.java, sormas-api/src/main/java/de/symeda/sormas/api/RequestContextTO.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java, sormas-app/app/src/main/java/de/symeda/sormas/app/rest/RetroProvider.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/Case.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbUserFilterTest.java, sormas-rest/src/main/java/de/symeda/sormas/rest/SessionFilter.java
=> Feature 7304 limit case sync

sormas-e2e-tests/build.gradle
=> #9110-ExposeJsonConfigInLogs-fix

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJoins.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleJoins.java
=> #8747 - Fixed multiple join types used

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java
=> hot fix because of performance

sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java
=> #9061 - Delete unassociated visits alongside persons

sormas-backend/src/test/resources/testcontainers/Dockerfile, sormas-base/pom.xml
Fixes #9177
See [#9177 ](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9177#issuecomment-1125130020) for a short guide on how to fix this in the future
=> Fix testcontainers

sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> #9019 - Don't show button for users without user right

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/ColumnSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDetailedTableViewSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Columns.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
https://jira.sormas-tools.de/browse/SORQA-176
=> Added tests for column sorting

sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/util/DtoHelper.java
=> #9064 - Don't set email address when merging

sormas-api/src/main/java/de/symeda/sormas/api/audit/AuditLoggerFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerInterceptor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ConfigFacadeEjb.java
=> [#8023] add logging for external lab message

sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
=> #8911 - fix filtering by contact community

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
=> #9135 - Check for existing cases first

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseContactsView.java
=> #9049 - Correctly set enabled status of case contacts view

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventParticipantsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> Qu auto/sorqa 223

sormas-api/src/main/java/de/symeda/sormas/api/RequestContextHolder.java, sormas-api/src/main/java/de/symeda/sormas/api/RequestContextTO.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbUserFilterTest.java
=> #7304 - cleanup & fix sonar issues

sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java
=> #9175 - Don't re-initialise dropdowns in onAfterLayoutBinding

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/vaccination/VaccinationDtoHelper.java
=> #9230 - Sync vaccine batch number

sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessagesView.java
=> #9205 close popup

sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/TherapyController.java
=> #8978 resize modal view

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePersonPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-227
=> Added test for hiding specific fields in DE version

sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
=> #9138 - eliminate unrequested requirement which caused the bug

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/CaseService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
=> common fixes, filtering cases by id, quarantine fix

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Case.feature
https://jira.sormas-tools.de/browse/SORQA-263
=> Added optional popup handling

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractMergeGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CustomizableGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/FilteredGrid.java
=> #8831 - set maximum width of columns in grids

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java
=> common fixes, delete reason popups, changed selectors etc.

sormas-app/app/src/main/AndroidManifest.xml
=> #9076 - Can't open campaign in the mobile app

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
and region and district to an event
=> and region and district to an event

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/change-request.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/support-request.md, .github/ISSUE_TEMPLATE/task.md, docs/CONTRIBUTING.md
=> #9296 Adjusted issue templates

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/AboutPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
=> small fixes

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Strings.java, sormas-api/src/main/resources/strings.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
=> #9078 S2S_missing update from the website after share was accepted and wrong error message afterwards

sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
=> #9097 update user role assignment

sormas-api/src/main/java/de/symeda/sormas/api/utils/InfoProvider.java, sormas-backend/src/main/java/de/symeda/sormas/backend/systemevent/SystemEventFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/systemevent/SystemEventFacadeEjbTest.java
Fixes #9304 
@FredrikSchaeferVitagroup Same commit, but I had to change the branches
=> [#9304] honor event type in query

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
=> #4461: Fixed stackoverflow issue

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/ColumnSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Columns.feature
https://jira.sormas-tools.de/browse/SORQA-264
=> Adjusted test for updated tables

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/TaskService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/CreateNewTaskSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Task.feature
=> SORQA-280 fix

sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/UserService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/tasks/TaskManagementSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/User.feature
=> common User.feature fixes

sormas-backend/src/main/java/de/symeda/sormas/backend/common/AdoAttributes.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/ChangeDateUuidComparator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/MockProducer.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbUserFilterTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/ChangeDateUuidComparatorTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java
=> #8946 Improve performance of PersonService.getAllAfter

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
=> Qu auto/sorqa 292fix2

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
=> SORQA-292fix3 flaky test

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/FollowUpVisitsTabPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/FollowUpVisitService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/FollowUpVisitsTabSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
https://jira.sormas-tools.de/browse/SORQA-283
=> Added test for displaying username in visit origin

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #9139 check view if event part edit right

sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjbTest.java
=> Change 9299 vaccination dupliate detection

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AdoServiceWithUserFilter.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/AdoServiceWithUserFilterTest.java
=> #9332 - Don't synchronize not a case contacts

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbPseudonymizationTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java
=> #9266 - Properly set classification info

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/report/AggregateReportDao.java, sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java
=> #8967 - fix age group sorting test

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactCriteria.java, sormas-api/src/main/java/de/symeda/sormas/api/task/TaskCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseUserFilterCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/common/AdoServiceWithUserFilterTest.java
=> #9286 - Task syn for not a case cases

sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
=> #8888 - Fixed issues with lab officers

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageMapper.java
=> #9383 [DEMIS2SORMAS] Correction are being proposed for the same report date

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
=> #9299 - Fixed missing vaccination data in exports

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/config/ConfigProvider.java
=> #4461 - Clear user rights on logout

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/user/UserDao.java
Fixes task creation problem in app
=> #4461: fixed task creation in app

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java
=> fix visibility and update of case confirmation fields #9280

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java, sormas-api/src/main/java/de/symeda/sormas/api/externalsurveillancetool/ExternalSurveillanceToolRuntimeException.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/shareinfo/SormasToSormasShareInfoService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/visit/VisitFacadeEjbTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/MergeCasesGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/processing/ExternalMessageProcessingUIHelper.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalsurveillanceservice/ExternalSurveillanceServiceGateway.java
Fixes #9425
Fixed the issue when there is a survnet converter configured but it is not running
=> #9425 'About' page on test-de3 can not be opened and an error message is displayed

sormas-backend/src/test/java/de/symeda/sormas/backend/common/StartupShutdownServiceTest.java, sormas-backend/src/test/resources/testcontainers/Dockerfile
=> #9446 StartupShutdownServiceTest testHistoryTablesMatch fails - remove forced dependency versions

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGridFilterForm.java
=> #8895: Fixed assignee filter

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessagesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/labmessage/LabMessageUiHelper.java
=> #8895: Fixed sonaqube findings

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
=> #9472 - Don't synchronize contact and ep samples

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java
=> #9276 - Fix internal sample creation

sormas-api/src/main/java/de/symeda/sormas/api/symptoms/SymptomsDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/symptoms/SymptomsForm.java
=> #9576 - Show all lesion-related symptoms

sormas-app/app/build.gradle, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/core/FeatureConfigurationService.java, sormas-app/app/src/main/java/de/symeda/sormas/app/core/TaskNotificationService.java
=> #9595 - Fix crashes on Android 12

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> update follow-up when sample is created #9447

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/CreateNewSamplePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
=> #8560 date and time dispaly for pathogen tests

sormas-e2e-tests/scripts/runApiMeasurements.sh, sormas-e2e-tests/scripts/runPagesMeasurements.sh
=> performance script filename changes

sormas-e2e-tests/src/main/java/recorders/StepsLogger.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/BaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Country.feature
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1378/allure/
Changes:
Logs will expose also process ID, so we can follow each test and its steps from main log file.
Screenshots will be available in teardown.
If screenshot after step is needed, in StepsLogger.class, change takeScreenshotAfterStep value to true
=> 9240 automation screenshots refactor

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFacilityChangeForm.java
=> #9445 - Validate place of stay field

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/report/AggregateReportDao.java, sormas-app/app/src/main/java/de/symeda/sormas/app/report/aggregate/AggregateReportsFragment.java, sormas-app/app/src/main/res/layout/fragment_reports_aggregate_layout.xml, sormas-app/app/src/main/res/values/strings.xml
=> Feature 9084 app msers view all reports

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java, sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
=> update contact follow-up when sample is created #9447

sormas-base/setup/keycloak/SORMAS.json
Fixes #8927
@jwijffels For some reason I cannot assign you as reviewer but please take a look. I'm adding a client with the basic config you provided which means you can hookup your application with it.
=> [#8927] add sormas-stats client to keycloak

docs/SERVER_SETUP.md, docs/SERVER_UPDATE.md, sormas-backend/src/main/java/de/symeda/sormas/backend/user/KeycloakService.java, sormas-base/pom.xml, sormas-base/setup/keycloak/audit-logging/standalone-ha-logging.cli, sormas-base/setup/keycloak/audit-logging/standalone-logging.cli, sormas-base/setup/keycloak/keycloak-setup.sh, sormas-base/setup/keycloak/themes/sormas/login/resources/css/styles.css
Resolves #8018
`KeycloakService` was reformatted, however, there is one significant code change:
`credential.setTemporary(true);` has ben added to make sure that users are always forced to update their password to enforce the usage of a secure provider.
=> [#8018] bump to keycloak 18.0.1

sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/audit/LogSink.java
=> #9677 keep fhircontext instance

sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1361/allure/
=> Test for merging duplicate contacts

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
Error caused by problem with user.
=> Qu test/sorqa 337

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java, sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
=> #9424 - Fix place of stay fields not filled

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #9632 - Don't duplicate samples when converting eps or contacts

sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java
=> #9334 - Fix event user filter

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/ValidationHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/ProcessedCaseDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ProcessedContactDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/ProcessedEventDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/ProcessedEventParticipantDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/externalmessage/SormasToSormasExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ProcessedImmunizationDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ProcessedSampleDataPersister.java
Fixes the error formatting part of #8674
=> [#8674] fix exception during format

sormas-backend/src/main/java/de/symeda/sormas/backend/sample/PathogenTestFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java
=> #8892 - Fix errors for external lab officer

sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java
=> #9623 - Validate age groups gracefully

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationEntityHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjbTest.java
=> Change 9265 vaccinations without a vaccination date should also be marked as relevant

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseEditComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java
=> Bug 9654 immunizations associated with cases created by processing a physician's report are not saved

sormas-app/app/src/main/java/de/symeda/sormas/app/util/InfrastructureFieldsDependencyHandler.java
=> #9424 - Properly fill facility details field

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditContactsPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/contacts/ContactsDashboardSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Contacts.feature
=> SORQA-371 implementation

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
=> SORQA-368 implementation

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java
=> #9435 - Show unsaved changes popup before deletion

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/HospitalizationTabPage.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature
=> case filter functionality and case hospitalization tab e2e tests fix

sormas-api/src/main/java/de/symeda/sormas/api/infrastructure/facility/FacilityFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/facility/FacilityFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CommunitiesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/ContinentsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CountriesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/DistrictsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/FacilitiesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/PointsOfEntryView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/RegionsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/SubcontinentsView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java
=> Bug 9727 infrastructure exports disregards bulk selection

sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbTest.java
=> #9334 - Fix inconsistent task user filter logic and usage

sormas-app/app/src/main/java/de/symeda/sormas/app/report/aggregate/AggregateReportsFragment.java, sormas-app/app/src/main/java/de/symeda/sormas/app/util/DiseaseConfigurationCache.java, sormas-backend/src/main/java/de/symeda/sormas/backend/disease/DiseaseConfigurationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java
=> #9073 Don't use primary for non-case-based diseases

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseEditComponent.java
=> #9722 disable disease field in edit form

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/users/CreateNewUserPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/ImmunizationService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/CreateNewImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/EditImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-271 Test pseudonymization in immunization

sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
=> #9350 allow region users to be set as surv user

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/CreateNewSamplePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/samples/EditSamplePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/CaseService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
=> SORQA-362 implementation

sormas-e2e-tests/src/test/resources/features/sanity/web/About.feature
=> ignore test

sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/DashboardDataProvider.java
=> #9658 Test results on the dashboard don't add up

sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantJoins.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbTest.java
Fixes #9779 for 1.73 and upstream for 1.74
=> #9779 avoid EventParticipant circle join 1.73

sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/SormasToSormasContactFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
=> #9784 S2S | When sharing back a Contact from target system to the source system the Contact can't be accepted

sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasListComponent.java
=> #9785 S2S | Share status does not get updated to the latest modifications for Contacts

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java
- Unified the dirty check into one internal method
Fixes #9435, successfully tested on event groups
=> #9435 Dirty check also for delete without reason function

sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java
=> #9659 - Combine confirmed classifications on dashboard

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java
=> Qu auto/sorqa 388fix

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/immunizations/EditImmunizationPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/CreateNewImmunizationSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/immunizations/EditImmunizationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-367 Automatize "Immunizations III: Immunization list for cases, contacts and event participants [5]"

sormas-backend/src/main/java/de/symeda/sormas/backend/ExtendedPostgreSQL94Dialect.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/H2Function.java
=> #9415 Create/Update/Delete of vaccination/immunization should be considered as change of a case for reporting tool

sormas-backend/src/test/java/de/symeda/sormas/backend/externaljournal/ExternalJournalServiceTest.java
=> #9824 All tests in ExternalJournalServiceTest are failing

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java
=> GDPR popup checxbox

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
Fixes #9447
Fix for this last finding: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9447#issuecomment-1169932367
All necessary updates have already been performed server side, so only a refresh of the UI is needed here.
=> refreshView after case create discard #9447

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
=> Qu auto/sorqa 402

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/CommunitiesTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/ContinentsTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/CountriesTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/DistrictsTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/RegionsTabPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/configuration/SubcontinentsTabPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/CommunitiesSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/DistrictsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/continents/ConfigurationContinentsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/countries/ConfigurationCountriesSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/regions/ConfigurationRegionsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/subcontinents/ConfigurationSubcontinentsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Community.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Continent.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Country.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/District.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Region.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Subcontinent.feature
https://jira.sormas-tools.de/browse/SORQA-343
=> Added tests for infrastructure data

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/entries/EditTravelEntryPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/CreateNewTravelEntrySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/TravelEntry.feature
=> SORQA-394 implementation

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/NavBarPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/environmentdata/manager/EnvironmentManager.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/LoginSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
Tested on local with invalid user :
=> #9594-AddUserErrorLoginHandle

sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFollowUpVisit.feature
=> scenario name fix

sormas-e2e-tests/src/test/resources/features/sanity/web/Columns.feature
https://jira.sormas-tools.de/browse/SORQA-391
=> Adjusted column sorting criteria

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/CommunitiesSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/configuration/DistrictsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/continents/ConfigurationContinentsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/countries/ConfigurationCountriesSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/regions/ConfigurationRegionsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/subcontinents/ConfigurationSubcontinentsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Community.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Continent.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Country.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/District.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Region.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Subcontinent.feature
https://jira.sormas-tools.de/browse/SORQA-344
=> Added tests for German infrastructure data

sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java
=> Bugfix 9885 duplicate summarization of aggregated reports by each juristiction level

sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/dashboard/DashboardServiceTest.java
Fixes #9850 (fixing not working PR #9760)
=> #9850 avoid duplicate confirmed classification

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
=> populate responsible contact officers field #9859

sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java, sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java
=> #9145: Introduced FeatureType for bulk actions in cases and contacts

sormas-api/src/main/java/de/symeda/sormas/api/sormastosormas/sample/SormasToSormasSampleDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/Sample.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/ShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasEntitiesHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/caze/CaseShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/contact/ContactShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/event/EventShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/eventparticipant/EventParticipantShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/immunization/ImmunizationShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ProcessedSampleDataPersister.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ReceivedSampleProcessor.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/SampleShareDataBuilder.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/SormasToSormasSampleDtoValidator.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasCaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasContactFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sormastosormas/entities/SormasToSormasEventFacadeEjbTest.java
=> #8950 S2S_Processed lab messages should be transferred

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CreateNewCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EditCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/vaccinations/CreateNewVaccinationPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/VaccinationService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/helpers/WebDriverHelpers.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/SymptomsTabSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/vaccination/CreateNewVaccinationSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
=> qu-auto/SORQA-232 Automatize "Test [Immunizations] Reduced entry option for vaccinations [3]"

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantExportDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java
=> refactoring export of cases, contacts and event participants #9193

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/CaseEpiDataView.java
=> #9817 fix demis2 sormas converting contacts while processing physician

sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseEditComponent.java, sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physiciansreport/PhysiciansReportCaseImmunizationsComponent.java
=> #9858 fix editing vaccination while processing phisicians report

sormas-api/src/main/java/de/symeda/sormas/api/event/EventParticipantExportDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/infrastructure/AbstractInfrastructureFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractSubNavigationView.java
=> #9929 fix nullpointer exception on startup

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/EpidemiologicalDataCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/EpiData.feature, sormas-e2e-tests/src/test/resources/features/sanity/web/EpidemiologicalDataCase.feature
=> qu-auto/SORQA-396 Automatize "[4777] Add continent and subcontinent to the location entity"

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/SurveillanceDashboardPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/surveillance/SurveillanceDashboardSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature
https://jira.sormas-tools.de/browse/SORQA-425
=> Added test for excluding "not a case" cases from total number of cases

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/grid/ImmunizationGrid.java
=> fix person Uuid navigation in event participant grid #9921

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbTest.java
=> #9938 save with fallback

sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java, sormas-ui/src/main/java/de/symeda/sormas/ui/epidata/CaseEpiDataView.java
=> #9817 [DEMIS2SORMAS] Converting contacts while processing physician reports can disable source cases in epiData (#9917)

sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java, sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
=> #9803 s2 s vaccinations are not synced after share

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/entries/CreateNewTravelEntrySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/mSers/MSersDirectorySteps.java
=> stabilization

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbTest.java
Fixes #4463
Moved user role edit ralated migrations at the end of sormas_schema and added databse migration on mobile to remove unused user rights
=> #4463 Edit and create user roles - fix migrations

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #9771 S2S_added sample after sharing a case/contact does not get shared - fixed failing migration

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/continents/ConfigurationContinentsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Continent.feature
=> Qu auto/sorqa 375

sormas-app/app/src/main/java/de/symeda/sormas/app/report/aggregate/AggregateReportsFragment.java, sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/AggregateReportsEditLayout.java
=> #9822 - Prevent submission of future aggregate reports

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseContactsView.java
Reverts hzi-braunschweig/SORMAS-Project#9947
=> Revert "[#9838] contact editable for not handed over case"

sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseContactsView.java
=> [#9838] edit archive check

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/SurveillanceDashboardPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/CreateNewContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/dashboard/surveillance/SurveillanceDashboardSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Dashboard.feature
=> qu-auto/SORQA-424 Automatize "Test Number of points on the dashboard map should be rendered by the time filter [2]"

sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/entities/sample/ProcessedSampleDataPersister.java
=> valid call to save method

sormas-api/src/main/java/de/symeda/sormas/api/visit/VisitExportDto.java, sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
=> #9857: Added visit user info to visit export

sormas-api/src/main/java/de/symeda/sormas/api/task/TaskStatus.java, sormas-api/src/main/resources/enum.properties, sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/report/WeeklyReportFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskServiceTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CssStyles.java
Fixes #6748 
Consider possible feature freeze before merging.
=> Change 6748 add task status progress 

sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
=> #9692 - Make poe place of stay optional in mobile app

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/dashboard/Surveillance/SurveillanceDashboardPage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Login.feature
=> qu-auto/SORQA-435 Automatize "Test Add new language (Urdu-Pk) in SORMAS [1]"

sormas-ui/src/main/java/de/symeda/sormas/ui/reports/aggregate/ReportDataGrid.java
=> #10026 - Fixed aggregate report data grid captions

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataView.java
=> #9773 - Don't display unsaved changes warning without changes

sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
=> #9932 - Use CASE_CLASSIFY right for confirmation fields

sormas-api/src/main/java/de/symeda/sormas/api/action/ActionFacade.java, sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/common/AdoServiceWithUserFilter.java, sormas-backend/src/main/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java, sormas-backend/src/test/java/de/symeda/sormas/backend/action/ActionFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventFacadeEjbTest.java, sormas-rest/src/main/java/de/symeda/sormas/rest/ActionResource.java
=> Feature 7930 event permanent delete

sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
=> #9883 - Proper annotations for contact category

sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractMergeGrid.java
=> #9648 - Show all merge actions upon loading data

sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java
=> #9892 - empty grouping does the same as region grouping

sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CreateNewCasePage.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/entities/services/SampleService.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/NavBarSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/EditSampleSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/SamplesDirectorySteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/statistics/StatisticsSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/Sample.feature
=> SORQA-431 implementation

sormas-api/src/main/java/de/symeda/sormas/api/user/UserFacade.java, sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java, sormas-backend/src/main/resources/sql/sormas_schema.sql, sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbUserFilterTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/WeeklyReportFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/sample/SampleFacadeEjbPseudonymizationTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/task/TaskFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserFacadeEjbTest.java, sormas-backend/src/test/java/de/symeda/sormas/backend/user/UserServiceTest.java, sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java, sormas-ui/src/main/java/de/symeda/sormas/ui/security/SormasOpenIdIdentityStore.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserController.java, sormas-ui/src/test/java/de/symeda/sormas/ui/AbstractBeanTest.java, sormas-ui/src/test/java/de/symeda/sormas/ui/TestDataCreator.java
Fixes #5058
Fixed user language change and added DB migration for missing required user rights on default user roles
=> #5058 Implement user right dependencies - fix findings during testing

sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CreateNewCaseSteps.java, sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCasePersonSteps.java, sormas-e2e-tests/src/test/resources/features/sanity/web/CaseFilters.feature
=> qu-auto/SORQA-432 Automatize "[4168] Handle accents gracefully in text filters"

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
=> #8723 - change filter to all event participants when event is archived

sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventParticipantsView.java
Reverts hzi-braunschweig/SORMAS-Project#10051
=> Revert "#8723 - change filter to all event participants when event is archived"

sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRoleFacadeEjb.java, sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRoleGrid.java
=> 4462 fixes part 3

sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactDataForm.java
=> #9883 - Fixed visibility issues for contact category

sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java
=> fixes #10041

sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/backend/infrastructure/InfrastructureHelper.java, sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java
=> #9385 - Fixed areas not being synced after enabling them

sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageCriteria.java, sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java, sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageService.java
=> #10050 - Remove case from external message when deleting

sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java
=> #9301 - Only display contact details change popup for primary contacts

sormas-api/src/main/java/de/symeda/sormas/api/i18n/Captions.java, sormas-api/src/main/resources/captions.properties, sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseFollowUpGrid.java, sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactFollowUpGrid.java
=> #9906 - Use proper captions for follow-up directories

sormas-backend/src/main/resources/sql/sormas_schema.sql
=> #4463 Edit and create user roles - add missing required user rights

sormas-ui/src/main/java/de/symeda/sormas/ui/IgnoreCancelDownloader.java, sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/infrastructure/CommunitiesView.java
=> fixed #9348

sormas-backend/src/main/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjb.java, sormas-backend/src/test/java/de/symeda/sormas/backend/report/AggregateReportFacadeEjbTest.java
=> #9892 - empty grouping summarizes everything
